### ISSUE TITLE
Cannot use wifi

### ISSUE THREAD

**Issue by polyzen** [copperhead/bugtracker#102]
The tasty bit seems to be line 55:
`Failed to create IpReachabilityMonitor: invalid interface 'wlan0':`

[logcat](https://ptpb.pw/-DgF)

**Comment by thestinger** [comment]
This is fixed in the new release. It was a missing hidepid exception.

**Comment by thestinger** [comment]
(specifically, system_server needs a hidepid exception via the proc group as a secondary group but the group id got desynchronized due to moving to AOSP which has a leaner group database)

**Comment by polyzen** [comment]
:+1:
