### ISSUE TITLE
Google Accounts cannot connect

### ISSUE THREAD

**Issue by polyzen** [copperhead/bugtracker#103]
When one opens Play Store, it says something like, "Cannot connect to accounts.google.com." Also checked Settings>Accounts, but didn't check the logs for that.

After you launch Play Store, this seems to be the relevant message:
`10-19 00:52:16.709   791   804 W BroadcastQueue: Permission Denial: broadcasting Intent { act=com.android.launcher3.action.LAUNCH flg=0x10 (has extras) } from com.android.launcher3 (pid=1279, uid=10008) requires 
com.google.android.launcher.permission.RECEIVE_LAUNCH_BROADCASTS due to receiver com.google.android.gms/.icing.proxy.ApplicationLauncherReceiver`

**Comment by thestinger** [comment]
Can you check if this is fixed in the new release? It could be caused by the same issue (proc group missing for system_server) as the WiFi issue.

**Comment by thestinger** [comment]
On the other hand, you might just need to grant a permission via Settings -> Apps. The gapps bundles have issues with the dynamic permission system in Marshmallow.

**Comment by polyzen** [comment]
This works without intervention :+1:

**Comment by thestinger** [comment]
I guess it was the hidepid issue then.
