### ISSUE TITLE
Play Store cannot download apps

### ISSUE THREAD

**Issue by polyzen** [copperhead/bugtracker#104]
[screenshot](https://ptpb.pw/giWg.png)
[logcat](https://ptpb.pw/E1sE)

**Comment by thestinger** [comment]
Can you try toggling on the location permission in Settings -> Apps? These problems seem to happen in 6.0 when gapps is flashed after the OS is installed. It seems like a bug in the gapps bundles rather than a bug in the ROMs.

**Comment by polyzen** [comment]
That did not do the trick

**Comment by thestinger** [comment]
You might not have added it for the right application. I really don't think this class of permission issues is related to the ROM. It's just how Android 6.0 works. Google Play Services assumes it has permissions but it doesn't if it's not bundled with the ROM. It likely works better if it's installed from the start before the OS is ever booted.

**Comment by polyzen** [comment]
chos and gapps were installed at the same time

**Comment by thestinger** [comment]
And that was with a clean userdata partition?

**Comment by polyzen** [comment]
cache, dalvik, data, and system were wiped. userdata was not

**Comment by thestinger** [comment]
If userdata was from before gapps was installed, you'll need to manually enable the permissions for the gapps apps until it works. This applies to every ROM without Google Play built-in, not just CopperheadOS. Nothing that can be done about it without being a Google Partner from our end.

**Comment by polyzen** [comment]
Do they need to have all the permissions enabled? or just location?

**Comment by thestinger** [comment]
Any of the permissions that they complain about. It's more than just location.

**Comment by thestinger** [comment]
If it's bundled from the start, then they likely get *all* the permissions enabled. So they're written with the assumption that they have all the permissions and can't handle Marshmallow's dynamic permission system as third party apps with API level >= 23 must do.

**Comment by polyzen** [comment]
Alright, will go ahead and try all permissions..

**Comment by polyzen** [comment]
Enabled all permissions in Play Services, Google Services Framework, and Play Store. No luck yet

**Comment by thestinger** [comment]
You need to look at the processes that are running, then cause the error to trigger and add it for the app that crashes due to the missing permission. It's clear that there's a missing permission from the log.

**Comment by thestinger** [comment]
And you'll need to do that whenever this comes up, which it will since gapps was installed after the OS (reinstalling the OS without wiping userdata won't change that).

**Comment by thestinger** [comment]
If gapps is installed before the initial boot (as in the initial time that userdata is used) then I don't think the problem will occur. It's the reality of gapps bundles with Android 6.0, not a CopperheadOS issue. You'll find lots of people with similar problems in /r/CyanogenMod, etc.

**Comment by polyzen** [comment]
Okay, still looking. This did not occur on ChOS pre-AOSP nor CM

**Comment by thestinger** [comment]
The same permission issues did exist there.

**Comment by polyzen** [comment]
I mean there was no problem installing apps from the play store. Did you notice this bit in the log?:
`12-19 21:00:04.187  3139  3236 E Volley  : [128] BasicNetwork.performRequest: Unexpected response code 500 for https://android.clients.google.com/fdfe/delivery?doc=com.dre.weather&ot=1&st=EM6517MFGZ7vtzN3ndVB&vc=25
12-19 21:00:04.198  3139  3139 D Finsky  : [1] InstallerTask$2.onErrorResponse: Received VolleyError 922 (Error retrieving information from server. [RPC:S-7:AEC-7 3UTV-T3CA-MAAOK])`

**Comment by thestinger** [comment]
The relevant error appears to be this: 12-19 21:00:06.392  3746  4316 E UploaderService: java.lang.SecurityException: "passive" location provider requires ACCESS_FINE_LOCATION permission. So you need to fix that before looking into other possibilities.

**Comment by polyzen** [comment]
The permissions kicked in after rebooting \o/

**Comment by polyzen** [comment]
After re-restricting the permissions to try to narrow down what's needed, Play Store doesn't want to connect at all.. even after loosening permissions again (and rebooting). Will try to see what's going on.
