### ISSUE TITLE
Browser crash  when downloading file (AOSP)

### ISSUE THREAD

**Issue by chifflier** [copperhead/bugtracker#107]
In the AOSP port, the browser crashes when downloading a file (missing android.permission.WRITE_EXTERNAL_STORAGE by default).

**Comment by thestinger** [comment]
This is a bug in AOSP, not one introduced by CopperheadOS. The browser isn't maintained anymore and needs to be switched out for something else.

**Comment by thestinger** [comment]
https://github.com/copperhead/bugtracker/issues/108
