### ISSUE TITLE
narrow down and fix applypatch access error

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#112]
This seems like it could be the same memory access error showing up elsewhere.

**Comment by thestinger** [comment]
cc @polyzen @vanitasvitae

**Comment by thestinger** [comment]
This has now been narrowed down to being caused by the Bionic changes. Need to narrow it down to a specific change next. Hopefully, it's the same issue causing the Chromium/WebView memory access errors.

**Comment by vanitasvitae** [comment]
Nice :+1:

**Comment by thestinger** [comment]
This is now fixed. It wasn't the same issue as the browser issues. However, the `pthread_atfork` memory protection code in Bionic had to be extended to cover the newly added code path (in Marshmallow) for removing handlers and that is likely the cause of those issues. Both fixes will be included in the next release.

**Comment by polyzen** [comment]
\o/

**Comment by thestinger** [comment]
A new release with the fixes is now available. Ignore the screwed up metadata on the downloads page. The over-the-air update server needs to be updated to cope with block-based updates.

**Comment by vanitasvitae** [comment]
Its working again! Thats great :+1: Thank you for the image from the past :D
