### ISSUE TITLE
Change default bluetooth device name

### ISSUE THREAD

**Issue by Kiwi** [copperhead/bugtracker#114]
Currently it is "AOSP on HammerHead"

Shouldn't this mention CopperHeadOS?

**Comment by polyzen** [comment]
This is also used by Syncthing to name the default folder for your photos.

Previously this was Nexus 5

**Comment by thestinger** [comment]
It makes sense for this to match Google's builds rather than the AOSP default. It's not very important though.

**Comment by thestinger** [comment]
This is now changed and will be part of the next release.

**Comment by Kiwi** [comment]
So that's why my car started calling it Nexus 5 ;)
