### ISSUE TITLE
add support for the Nexus 6

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#115]
Blocked until we have a Nexus 6 and a build server.

**Comment by thestinger** [comment]
This is no longer on the roadmap, but it could still happen.

**Comment by mitchelldavis44** [comment]
Would would it take to get support for Shamu?  Apologies for reopening this but I have a build server and am willing to maintain if it's something you guys would consider, plus I've been a maintainer for several ROM teams in the past and am currently involved in a project so I have the experience necessary.

**Comment by thestinger** [comment]
It would require funding. The Nexus 6 and 9 are going to be EOL in October 2017, so there isn't much of a future for them. Once devices are EOL, full security updates are no longer possible, so they stop making sense as CopperheadOS targets after that point. It's too late for it to make much sense to add it.

**Comment by thestinger** [comment]
You can of course use the CopperheadOS sources as you wish per the terms of the license, and with anything published based on it called something other than CopperheadOS since that trademark is for our official builds.
