### ISSUE TITLE
add support for the LTE Nexus 9

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#120]
This might just involve bundling the radio image without any changes to the operating system itself.

**Comment by DespairFactor** [comment]
The flounder is the same LTE and non LTE, the only difference is RIL/Radio IIRC

**Comment by thestinger** [comment]
It's mostly the same, but it's an extended build and there are different blobs.

**Comment by thestinger** [comment]
This is no longer on the roadmap, but it could still happen.
