### ISSUE TITLE
Correct date at downloads page

### ISSUE THREAD

**Issue by Bmme2GFTbU** [copperhead/bugtracker#125]
Since 12/24/2015 the date of the newer updates at https://copperhead.co/android/downloads ist shown as the Linux-Base-Date 01/01/1970

**Comment by polyzen** [comment]
Seemingly related: my hwclock seems to be set to 1970 since flashing the original AOSP-based factory image. Turn off automatic time and time zone -> reboot -> time's fubar'd. Time is also off in TWRP. Haven't looked into this enough..

**Comment by thestinger** [comment]
@polyzen: That's not related.

**Comment by thestinger** [comment]
(and it doesn't touch the clock there so it wasn't caused by CopperheadOS / AOSP)

**Comment by thestinger** [comment]
This is #118.
