### ISSUE TITLE
AIMSICD crashes

### ISSUE THREAD

**Issue by vanitasvitae** [copperhead/bugtracker#127]
I tried both PaX softmode enabled and disabled, but AIMSICatcher Detector crashes. Would love to have it back :+1:

**Comment by thestinger** [comment]
It's an upstream bug: https://github.com/SecUpwN/Android-IMSI-Catcher-Detector/issues/718.

**Comment by vanitasvitae** [comment]
Ah okay. Thank you

**Comment by vanitasvitae** [comment]
The issue is fixed in the new version.

**Comment by thestinger** [comment]
New version of CopperheadOS or AIMSICD?

**Comment by vanitasvitae** [comment]
Um... I updated both :D

**Comment by vanitasvitae** [comment]
But I guess AIMSICD fixed their upstream bug.
