### ISSUE TITLE
Connection lost after call

### ISSUE THREAD

**Issue by Bmme2GFTbU** [copperhead/bugtracker#131]
After ending a call I lost 2G and 3G connection to carrier for  some (max. 5) seconds

**Comment by Bmme2GFTbU** [comment]
Gernan Carrier without 4G

**Comment by Bmme2GFTbU** [comment]
Can not be confirmed after second call

**Comment by thestinger** [comment]
You should check `adb logcat '*:F'` for crashes. The relevant log output might be gone by now, but you can try it next time it happens. You could also look for interesting errors with `adb logcat '*:E'` or simply look through the full output but there's a fair amount of noise.

**Comment by thestinger** [comment]
I'll just close this for now because it's just as likely that it's a bug on the carrier's side of things or simply bad reception for one reason or another. If it happens again or you get logs indicating that it's a CopperheadOS problem, it can be re-opened.
