### ISSUE TITLE
hammerhead no mobile inet

### ISSUE THREAD

**Issue by neo-luddite** [copperhead/bugtracker#140]
Hello,
I just installed hammerhead-factory-2016.01.13.00.36.11 with `flash-all.sh` .
Wifi is working, I can call but no mobile internet.
Logcat:  http://pastebin.com/RjTn4TKB

tnx!

**Comment by thestinger** [comment]
You might need to set up a proper APN for your carrier. It's unlikely that the problem is caused by CopperheadOS. It would probably happen with AOSP too.

**Comment by neo-luddite** [comment]
my bad, it was the APN - tnx!

**Comment by thestinger** [comment]
It would make sense to add this to the installation guide. It's likely going to be a common problem. CyanogenMod tries to add all of the APNs but it's hard to maintain and they often get it wrong.

**Comment by neo-luddite** [comment]
I think just a short sentence in the install guide would do!
