### ISSUE TITLE
MAC randomization for the Nexus 5X

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#147]
Full MAC randomization completely breaks WiFi authentication and had to be disabled.

Scanning MAC randomization mostly works, but it occasionally triggers the same symptom, apparently during sleep - but not always. It has also been disabled.

**Comment by canary5** [comment]
Is it fixed? It not changing mac for me

**Comment by darknetj** [comment]
@canary5 please provide logs and follow https://github.com/copperhead/bugtracker/blob/master/README.md

**Comment by canary5** [comment]
Can i send logcat by emeil?

**Comment by darknetj** [comment]
@canary5 sure - team@copperhead.co

**Comment by canary5** [comment]
Logcat sent by email

**Comment by thestinger** [comment]
If it was fixed, the bug would be closed. Logs aren't necessary. If someone wants to investigate and fix this, that would be great. I'm not actively working on it and I don't plan to.

**Comment by canary5** [comment]
Sorry for question, is it working on 6P

**Comment by thestinger** [comment]
The scanning MAC randomization is enabled on both. Full MAC randomization isn't ported to the 6P yet, but I expect it to work. Only the Nexus 5X uses the Qualcomm WiFi hardware rather than the usual Broadcom chips.

**Comment by thestinger** [comment]
The Nexus 6P now has full MAC randomization. It works fine. The Nexus 5X wifi chip is just garbage.

**Comment by tobia** [comment]
> The Nexus 5X wifi chip and drivers are just garbage.

And you guys didn't think of mentioning this on the project's documentation?

For the record, I just bought a €330 phone specifically to install CopperheadOS, because it's one of the *two* models mentioned on the project homepage that don't have a ridiculous price, and because a sample of internet reviews suggested that it was an improvement over the 5. And after cursing its wifi for a week I find out it's well known by the developers that it's garbage.

Great.

**Comment by thestinger** [comment]
If every upstream issue was going to be documented, the project would solely consist of writing documentation for all of the bugs in Android. The issues with the Nexus 5X WiFi chip aren't particularly bad when compared to everything else. It just isn't compatible with MAC randomization and sometimes needs to be toggled on and off.

It's possible that scanning MAC randomization makes the issues worse than they would be otherwise. However, every issue that has come up such it dropping off during heavy use or sleep and being unable to reconnect has upstream reports. The workaround for those is toggling it off and on again. These issues don't occur on other devices with Broadcom WiFi chips. It would be worth trying to disable scanning MAC randomization (which requires a userdebug build) to see if the issues are still just as frequent, but it's difficult to determine that especially since I don't regularly use the 5X. The issues haven't come up during automated testing, only when it's being used in a more normal way (sleeping, heavy network usage).

**Comment by Rudd-O** [comment]
I can't find the menu entry for randomization.  Was that altogether removed from 5X and in which commits was it killed?

**Comment by Rudd-O** [comment]
Ah, I found it.  Ignore my post.  I'm an idiot.

Note that the randomization doesn't seem to work when I'm already associated.

**Comment by Rudd-O** [comment]
How can I tell using tcpdump that my phone is in fact randomizing its MAC address when scanning?

**Comment by darknetj** [comment]
@Rudd-O please confirm you have an actual issue before reporting it on the bugtracker. 

http://bfy.tw/6oKS

**Comment by thestinger** [comment]
5X doesn't use either full MAC randomization or scanning MAC randomization anymore. It's used on the Nexus 5, 9 and 6P without problems. Can see the scanning MAC randomization via `ip link` since it's done via wpa_supplicant's support for changing the MAC address on the interface rather than requesting that the interface uses a random scanning address (that might work for 5X, but not really interested in another mechanism to work around the broken driver, and it likely doesn't randomize the vendor portion).

**Comment by recvoid** [comment]
Hello, I have a 5X and the mac randomization is not working. Was this disabled?
If so will it be enabled again in the future?

**Comment by thestinger** [comment]
If it was implemented, this issue would be closed. You're welcome to work on it. I'm not going to be working on anything related to Qualcomm's awful qcacld-2.0 WiFi driver anymore.

**Comment by thestinger** [comment]
Confirmed that the driver is still broken.

**Comment by n3xus5x** [comment]
damn... wasnt working still came here to check up the progress still no improvements.. sad story

**Comment by thestinger** [comment]
It's not going to fix itself. Until someone is interested in doing some real work on this, there isn't going to be progress. This likely impacts the Pixel and Pixel XL too so there's the slim chance that someone with a Pixel or Pixel XL will want MAC randomization working. I seriously doubt that anyone cares enough to do more than complaining about it though. It's not going to be trivial to get this working. It will be a substantial amount of work and might not pan out if it turns out to be an inherent limitation of the hardware / firmware.

**Comment by thestinger** [comment]
Replacing with #556.
