### ISSUE TITLE
support 2 factor unlock authentication when a separate encryption password is set

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#150]
Support requiring both a fingerprint and a PIN/password/pattern.

**Comment by kckrinke** [comment]
I would love to see this, mentioned it in my comment on #191 but this issue (150) is just the basic requirement of the real feature (customizable multi-factor authentications).

**Comment by thestinger** [comment]
This isn't going to be implemented. Something similar could be done, but it's going to need to be different now.

**Comment by thestinger** [comment]
See #451.
