### ISSUE TITLE
Select USB configuracion bug  Nexus 5

### ISSUE THREAD

**Issue by lagosazules** [copperhead/bugtracker#154]
I think I found a smal but importantant safety bug, in developer options - select USB Configuracion, if I select "Charging only" I have notice that after some time the setting changes always back to MTP.
Also when doing a reboot it change  to MTP, I think having USB data access when this is not necessary is a extra safety risk.

**Comment by thestinger** [comment]
The default is already charging only without touching anything in the developer settings. Those aren't user-facing settings and you aren't supposed to touch them for normal usage of the device, only debugging. I'm not sure what that option is supposed to do. It could be that it's obsolete. Regardless, it's an AOSP issue and doesn't appear to be a real security problem. I don't consider fixing AOSP bugs to be in-scope unless they have a direct security impact.

**Comment by lagosazules** [comment]
Sorry but this is not correct, I have just checkt it again on build MMB29T.2016.01.28 and after a reboot it is back on MTB again

**Comment by thestinger** [comment]
The default is charge-only without touching anything in developer settings. Not sure what you've changed, but if you go back to the default state it will be using charge-only by default again. You shouldn't change it via developer settings because there's a user-facing menu to change the setting.

**Comment by thestinger** [comment]
Just ignore the developer setting drop-down, it doesn't work.

**Comment by thestinger** [comment]
The user-facing setting exposed via the notification menu works properly. The drop-down menu in developer settings seems like it wasn't properly updated for the changes in 6.0. The developer settings are only meant for debugging / development though - those features aren't necessarily robust and they shouldn't be used on a device that's meant to be secure, beyond turning off OEM unlocking again and then ideally disabling developer settings again. A phone with CopperheadOS pre-installed would have developer settings off by default, as that's the normal state.

**Comment by thestinger** [comment]
See https://android.googlesource.com/platform/packages/apps/Settings.git/+/5eba30289a708d92f152d998c05bea3866316b3b. The way it works might be intended. The default is effectively charge-only either way and developer settings being understandable only by the Android developers working on the OS is to be expected.
