### ISSUE TITLE
Feature Request: Permission Manager

### ISSUE THREAD

**Issue by PandorasTeacup** [copperhead/bugtracker#162]
I think a Permission Manager would be a great Addition to your ROM. You can keep control over your Apps with it, especially when they are not fully trustworthy. Cyanogenmod has this feature and there are other Apps and Solutions out there, but it seems XPrivacy is one of the best Solutions and even Open Source. But it requires the XPosed Framework.

I dont know if it would be best if you integrate XPrivacy into your ROM or develope something similar by yourself, but this would be a great and Important Feature.

Here is the XPrivacy Source Code: 
https://github.com/M66B/XPrivacy

**Comment by thestinger** [comment]
The ability to toggle off permissions is built in Android 6.0. It's done via Settings -> Apps. It could be extended but the base is already there and provides the same features as CyanogenMod's PrivacyGuard did previously since they're both based on AOSP's AppOps.

**Comment by thestinger** [comment]
Apps with an API level >= 23 (i.e. Marshmallow) also aren't given 'dangerous' permissions like access to contacts and location information by default. They need to check if they have access and then request access from the user if they don't have it but want it.

**Comment by PandorasTeacup** [comment]
Sorry, didn't know that. The last Android Version I used was 2.3 and I should have checked if this was implemented since then.
