### ISSUE TITLE
Compass is pointing in opposite direction

### ISSUE THREAD

**Issue by vanitasvitae** [copperhead/bugtracker#166]
Hi
The compass on my nexus 5 points in the exact opposite direction. I noticed this in OSMAnd and rechecked with a compass app. I'm located in Europe. Is this a CopperheadOS issue?

**Comment by thestinger** [comment]
I don't think it's a CopperheadOS issue. The Nexus 5 compass is notoriously bad and the compass in the newer devices is much saner.

**Comment by vanitasvitae** [comment]
Okay. Thank you nevertheless.
