### ISSUE TITLE
"Close all" button

### ISSUE THREAD

**Issue by amilopowers** [copperhead/bugtracker#171]
Could you please add a button to close all running apps in the running apps overview?

**Comment by Bmme2GFTbU** [comment]
Support this feature. asked for this earlier. This button is already alvailable for Samsung devices.

**Comment by thestinger** [comment]
I'm not sure if I want to add features like this that aren't directly security-related.

**Comment by Bmme2GFTbU** [comment]
OK, but maybe it could be placed on the far-future-feature-list

**Comment by thestinger** [comment]
I'm not going to close the issue yet, but it's not really in scope of the CopperheadOS project. I wouldn't accept a high quality standalone patch for this right now and I'm *definitely* not going to implement it myself. CopperheadOS is aimed at hardening Android, not implementing lots of miscellaneous features. It's too out of scope to do it here. You would have more luck getting it implemented in AOSP and then it would become part of CopperheadOS, without it needing to be maintained here.

**Comment by thestinger** [comment]
I don't plan on implementing any non-security / non-privacy-related features. The development and maintenance burden will detract from security features. It's out of scope for CopperheadOS. If you want features like this, you should get AOSP to implement them and then they'll be available in CopperheadOS too.
