### ISSUE TITLE
Fast app change

### ISSUE THREAD

**Issue by amilopowers** [copperhead/bugtracker#174]
Please add the ability to go back to the previous app by holding the app switcher button.

**Comment by thestinger** [comment]
I don't plan on implementing any non-security / non-privacy-related features. The development and maintenance burden will detract from security features. It's out of scope for CopperheadOS. If you want features like this, you should get AOSP to implement them and then they'll be available in CopperheadOS too.

**Comment by vanitasvitae** [comment]
This will be implemented in Android N (double tap recent apps button), so I guess it'll be available then.
