### ISSUE TITLE
Can't install apps

### ISSUE THREAD

**Issue by amilopowers** [copperhead/bugtracker#175]
I can't install apss in F-Droid. Once the app is downloaded I cant hit the "Install" button. It isn't greyed out it just doesn't work.

**Comment by polyzen** [comment]
This could be due to some app "drawing over" it (eg. when [Twilight](http://twilight.urbandroid.org/) is working).

For a list of apps that might do this:
Settings -> Apps -> Gear icon -> Draw over other apps -> Select "Apps with permission" from dropdown

**Comment by amilopowers** [comment]
That was the problem! Thx.

**Comment by thestinger** [comment]
So I guess this isn't a bug in CopperheadOS?

**Comment by polyzen** [comment]
Afaik this is normal/expected.
