### ISSUE TITLE
Wifi hotspot doesn't work

### ISSUE THREAD

**Issue by amilopowers** [copperhead/bugtracker#176]
I configured the Wifi hotspot with a password and 2,4 GHZ. My Fedora laptop can't find the network.

**Comment by darknetj** [comment]
@amilopowers please post relevant debug information:

- dmesg output from your laptop (dmesg | grep wlan0)
- adb logcat from your device
- WiFi settings for the hotspot - WPA1/2 etc

**Comment by vanitasvitae** [comment]
Works for me (CopperheadOS Feb07, Nexus 5, Debian 8)

**Comment by thestinger** [comment]
There was another report of this issue in the past: https://github.com/copperhead/bugtracker/issues/27. It could never be replicated by everyone though.

**Comment by amilopowers** [comment]
Worked now on Mac OS and Fedora. Can be closed.
