### ISSUE TITLE
MediaServer caused huge battery drain

### ISSUE THREAD

**Issue by vanitasvitae** [copperhead/bugtracker#182]
Hi
I just had the problem that the mediaserver drained a lot of battery on my hammerhead. 
`top | grep media` showed CPU usage of 50%. I killed the process and now its fine. Right now I'm updating to the latest release. I wanna test, if the process is back after reboot. I don't know, whether this is an issue of CopperheadOS or if its just me.

**Comment by thestinger** [comment]
I would need enough information to demonstrate that it's a CopperheadOS bug before being able to look into this. There are plenty of bugs in mediaserver and it can be assumed it's one of those.
