### ISSUE TITLE
DeskClock crashes when selecting cities (globe icon)

### ISSUE THREAD

**Issue by smaeul** [copperhead/bugtracker#189]
https://gist.githubusercontent.com/smaeul/87ff4e34e88423f7d4ba/raw/5ec844294f5ff0a948b5af766158fce43c0899ae/DeskClock-logcat

This happens in both the 2016.02.18 and 2016.02.21 builds.

**Comment by thestinger** [comment]
Thanks. I think https://android.googlesource.com/platform/packages/apps/DeskClock/+/581aa2ea147f49b1fd7292ba07aa893429ac5de3 might be the fix for this. I'll try backporting it.

**Comment by thestinger** [comment]
This is now fixed.
