### ISSUE TITLE
add the option of turning off the device based on various triggers

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#191]
A certain amount of time locked without being connected to a known network is one example. It requires some more thought.

**Comment by mhyqwvcu** [comment]
How about designating a fingerprint to trigger shutdown? The middle one could be particularly satisfying. ;)

**Comment by thestinger** [comment]
That might be an option.

**Comment by lagosazules** [comment]
"fingerprint to trigge" good idea, I think also a screen password given under force (or to  write it on a sticker on the back of the phone) that activate a reboot or start whipping the phone.

**Comment by kckrinke** [comment]
Or how about using different fingerprints to trigger different actions. Middle-finger-wipe for example. I'd also like to see multi-factor features too like, two fingers plus a password are required or something silly like that.

**Comment by jiyagaimo** [comment]
I like this feature. This can be very useful in case your phone gets stolen/confiscated.

-Auto shutdown after X hours without being logged in and a timetable when this cannot be triggered.

**Comment by thestinger** [comment]
Needs to be made more specific.
