### ISSUE TITLE
Nexus 5x No incoming calls

### ISSUE THREAD

**Issue by huckinturtles** [copperhead/bugtracker#192]
I'm not receiving incoming calls on T-Mobile.

I get notifications of voicemails, also calling (outgoing) and texting works.

Not sure how to get  you anymore info on the problem

Thanks

**Comment by thestinger** [comment]
Try removing the default APN settings and setting that up again.

**Comment by huckinturtles** [comment]
Redoing the APN settings had no effect

**Comment by huckinturtles** [comment]
Update MMB29U.2016.02.27.14.18.58 fixed this bug

Thanks

**Comment by thestinger** [comment]
I'm not sure what could have changed that would fix it but I'll take it. Perhaps it just needed a reboot?

**Comment by huckinturtles** [comment]
Your right, a fresh installed did not work. Modifying the APN, rebooting and waiting awihle seemed to fix it. The default APN did not include the mmsc or APN type fields

**Comment by thestinger** [comment]
The AOSP APNs aren't maintained very well. CyanogenMod updates them but it's not something I want to deal with. Ideally, Google would ship out updates for them.
