### ISSUE TITLE
Issue on VoLTE phone calls

### ISSUE THREAD

**Issue by Mnkai** [copperhead/bugtracker#195]
## Device
Nexus 5X
## Carrier
KT (olleh) in South Korea, using LTE band

## Symptoms
I'm using this device in KT network, and this network supports VoLTE calls and messages.
Using stock rom of Nexus 5X, VoLTE works.

When I use Copperhead OS while enhanced 4g lte mode (volte) enabled, sms works out of box, but phone calls fail.
When I turn off enhanced 4g lte mode, outgoing phone calls work, but incoming call does not work - carrier still thinks I'm using volte mode. (maybe, just guessing at this part. I'm not sure this is carrier's fault.)

When I use 3g mode (lte disabled), incoming and outgoing phone calls work.

**Comment by thestinger** [comment]
It's not possible for us to address something like this since it's very unlikely that it's caused by our changes and we can't reproduce it. Unless there's an obvious error in the logs, there's nothing to work from. You could try removing the default APN entries and setting it up again. You would need to conform that this issue isn't present in AOSP for it to be considered a CopperheadOS bug.

**Comment by Mnkai** [comment]
Trying to initialize default APN entries did not work. Do I just have to look up for any sign of malfunction in adb logcat?
There are no pure AOSP roms for 5x as far as I aware of, so it will take some time for me to build AOSP from source. I'm on trip right now, so I'll try digging in logcats before compiling stock AOSP rom when I'm back home.

**Comment by Mnkai** [comment]
Saw some warnings and errors while calling on logcat. Seems to be related to VoLTE IMS. Is this the log are you looking for?

[voipcalling.txt](https://github.com/copperhead/bugtracker/files/152860/voipcalling.txt)

**Comment by Mnkai** [comment]
Update: VoLTE in CM13 works out of box, and Chroma (AOSP based) too. I have not tested stock AOSP yet, though. Will update about that later on.

**Comment by thestinger** [comment]
Try temporarily sideloading a root implementation in order to debug. Start by removing `/dev/diag`. If that doesn't work, try `setprop persist.ims.disableDebugLogs 1`. If it still doesn't work, try `setprop persist.ims.disableIMSLogs`.

**Comment by thestinger** [comment]
Logs with more context would also be helpful.

**Comment by adpaolucciknowroaming** [comment]
Rogers in Canada is supposedly launching VoLTE this month, as a possible test reference.

http://www.gsma.com/network2020/wp-content/uploads/2015/05/Summary-of-RCS-and-VoLTE-Launches-v6.pdf

**Comment by thestinger** [comment]
I need confirmation that this is still an issue along with the debugging process mentioned above.

**Comment by thestinger** [comment]
I'll have to assume that this isn't a problem then.

**Comment by perillamint** [comment]
On Nexus 6P (Carrier: SK Telecom, Korea), It still does not work. I tried running setprop command mentioned at top but it does not help.

**Comment by thestinger** [comment]
In all likelihood it's an AOSP issue, not a CopperheadOS issue, as with all the rest of these carrier/radio issues. AOSP issues aren't going to be tracked here and they aren't going to have time devoted to them. A sane workaround will be accepted, although there's a good chance that it's android-prepare-vendor where a change needs to happen.

**Comment by thestinger** [comment]
This tracker is for issues with CopperheadOS features. For AOSP, there's https://code.google.com/p/android/issues/list. There are many issues in AOSP builds that are not present in stock and in fact there's no official support from Google for building AOSP for the 5X and 6P with the radio working at all. These issues might have to be worked around in https://github.com/anestisb/android-prepare-vendor which the project CopperheadOS relies upon for Nexus 9, 5X and 6P support.

**Comment by adpaolucciknowroaming** [comment]
@thestinger I don't believe this is a AOSP issue as stock Nexus 6p devices have no problems with VoLTE, even on SK Telecom bands/systems. @perillamint can you copy+paste your APN configuration? If the APN configuration was not automatically populated you may need to add the MMSC Can you also validate that your account with SK Telecom has VoLTE enabled? I know with Verizon in the US it needs to be enabled along with Rogers here in Canada they need to add a special flag to your account, this might not be done if you didn't purchase the device with your carrier.

*For VoLTE * SKT is available only when registering a device name that people LTE handset manufacturers OMD _VOLTE. (Currently, Samsung, LG, only APPLE.)

This should be the APN entry in ASOP, will check it later in the CopperheadOS codebase.

"<apn preferapp="" type="" mmsport="9093" mmsproxy="smart.nate.com" mmsc="http://omms.nate.com:9082/oma_mms" port="80" proxy="" server="*" authtype="0" password="" user="" apn="lte.sktelecom.com" mnc="05" mcc="450" carrier="SKT"/>"

SK Telecom APN Settings: 
- APN: lte.sktelecom.com 
- MMSC: http://omms.nate.com:9082/oma_mms 
- MMS Proxy: lteoma.nate.com 
- MMS Port: 9093 
- MCC: 450 
- MNC: 05 
- TYPE: default, supl, mms, dun, cbs, fota 
- PROTOCOL: ipv4v6

I'm not quite sure if these APN settings are correct as the documentation I have for SK Telecom is outdated, but I believe they may have split the LTE versus IMS into two separate APNs, I would verify with the carrier to confirm these settings.

**Comment by thestinger** [comment]
AOSP != stock

**Comment by adpaolucciknowroaming** [comment]
@Mnkai can you also verify your APN settings for your issue? Did you ever contact the carrier to confirm these settings?

**Comment by perillamint** [comment]
@adpaolucciknowroaming I'm using automatically populated APN settings.. and it seems have correct MMSC.

Also, my phone is registered as "Nexus 6P" (or corresponding codename?) in SKT internal DB and it marks N6P has a VoLTE feature.

I think that's why I cannot receive phone call while I connected to LTE network. It seems SKT tries to reach me using VoLTE but CopperheadOS's security rule seems to blocking it from working.

When I asked my friend to call me while I'm in LTE network, I can see some AVC denials in kernel log and logcat.. but I'm not quite sure about reason because when I set SELinux as permissive mode, it still does not work..

**Comment by perillamint** [comment]
@thestinger  Additionally, I found someone mentions VoLTE is working in AOSP but not in Cyanogenmod. 

https://jira.cyanogenmod.org/browse/NIGHTLIES-2969

If you need more clarification, I can build vanilla AOSP and test it on it.

**Comment by thestinger** [comment]
> It seems SKT tries to reach me using VoLTE but CopperheadOS's security rule seems to blocking it from working.

It isn't a CopperheadOS feature blocking it.

> When I asked my friend to call me while I'm in LTE network, I can see some AVC denials in kernel log and logcat.. but I'm not quite sure about reason because when I set SELinux as permissive mode, it still does not work..

It's normal for there to be denials. A denial doesn't indicate a bug. Setting it to permissive still prints out denials that would have happened. This isn't caused by SELinux, and I *doubt* it's caused by a CopperheadOS feature.

**Comment by thestinger** [comment]
AOSP alone doesn't support the radio on the Nexus 5X and 6P. You won't get any cell service at all. You need to use something to generate the files and build system for the vendor files from the factory images, which in the case of CopperheadOS is https://github.com/anestisb/android-prepare-vendor. There are a few possible things that could be going on. The most likely are either an AOSP bug or something that's being missed or done incorrectly by android-prepare-vendor.

**Comment by razaborg** [comment]
Sorry to bring up this "old" issue. But I have a Nexus 6P with CopperheadOS and I still have this VoLTE issue (both the UE and the SIM card are definitely compatibles with VoLTE, the only blocking point here seems to be the OS).
On the network side, the Phone seems to ask for a CS fallback, despite valids APN for ims are set.

My question is quite simple : is it supposed to work with CopperHead, or maybe VoLTE is not "officially" supported by the project ?

FYI, my phone is totally up to date with the latest stable version of Copperhead.

**Comment by thestinger** [comment]
VoLTE is officially supported on the Pixel and Pixel XL. No one ever did the work to make it work on Nexus devices and we no longer actively develop anything device-specific for them. It's their last year of maintenance-only support before they're dropped.
