### ISSUE TITLE
NFC

### ISSUE THREAD

**Issue by marix11** [copperhead/bugtracker#196]
Me on latest 07/03 on 5x.  I cant get nfc to work.  Any1 tested nfc? 
On more question. How to remove space for search on home screen? Seems like not full screen used

**Comment by thestinger** [comment]
> Me on latest 07/03 on 5x. I cant get nfc to work. Any1 tested nfc? 

It's disabled by default, but it should work. Going to need a lot more information for this to be actionable such as exactly what you're trying to do and logs from `adb logcat`.

> On more question. How to remove space for search on home screen? Seems like not full screen used

It's not possible. It's also where it displays the various possible actions when dragging.

**Comment by marix11** [comment]
I was using openkeychain and yubikey. Heres logcat
http://pastebin.com/vh4R4bbH

**Comment by thestinger** [comment]
Did it work on a previous CopperheadOS version or on stock Android?

**Comment by marix11** [comment]
Its first time i have installed your OS. And i wiped stock same minute i bought new phone ;)

**Comment by thestinger** [comment]
Few of these issues end up being CopperheadOS-specific which is why I asked.

**Comment by marix11** [comment]
I see. Openkeychain+smartcard worked on my previuos samsung phone. So this either my new phone buggy or smth with CoOS

**Comment by thestinger** [comment]
It needs to be confirmed as a CopperheadOS-specific issue. Even then, I'm unable to test this so you'll need to provide logs and perhaps more. Otherwise, I'll just have to close this because I can't confirm it or debug it myself.

**Comment by marix11** [comment]
I will try to test on another nexus5 during weekend

**Comment by marix11** [comment]
I been testing on nexus5 and nfc working fine. I will try to find another 5x to test

**Comment by adpaolucciknowroaming** [comment]
YubiKey(NEO)+OpenKeyChain on Nexus 5x (MMB29V.2016.03.07.22.19.43) works fine, it's a bit iffy to get the NFC reader to pickup the key, but it does eventually(minute or so of removing it and placing it to the back of the phone) and it works. Has also worked in previous versions, can't try on the latest as I've swapped ROMs.

**Comment by darknetj** [comment]
@adpaolucciknowroaming can you supply a logcat for both scenarios to help us debug?

**Comment by adpaolucciknowroaming** [comment]
@darknetj sorry, cannot at this time. Running back on stock to compare performance.

**Comment by marix11** [comment]
Ok its working on another 5x. So theres problem with my phone. I will close the issue
