### ISSUE TITLE
Updating on Nexus 5 via Sideloading

### ISSUE THREAD

**Issue by nexus4fun** [copperhead/bugtracker#200]
Hello, i wanted to update my phone via sideloading, but i can't boot in to Recovery. Tried both options: adb reboot recovery and Volume down + Power button. Result in both cases was same: "Broken Android" logo.

**Comment by thestinger** [comment]
The broken Android logo is recovery. It's the same as stock Android.  The menu is only shown by default in a debug build. Regular users won't end up there unless something goes wrong so they hide the menu and show an error, with a reboot happening after an idle time. You can access the menu by holding the power button and pressing the volume up button.
