### ISSUE TITLE
Add support for the OnePlus One

### ISSUE THREAD

**Issue by Bolts** [copperhead/bugtracker#204]

**Comment by thestinger** [comment]
There isn't going to be support for devices not supported by the Android Open Source Project.

**Comment by akuckartz** [comment]
@thestinger What about support by CyanogenMod ?

**Comment by thestinger** [comment]
CopperheadOS isn't going to be based on CyanogenMod. See https://copperhead.co/blog/2016/02/08/beta.

**Comment by akuckartz** [comment]
@thestinger Thanks a lot for the answer and the link to the details.

**Comment by weedy** [comment]
I'm disappointed by this since at least with the COS base kernel repos they did a decent job having a stable updated source for things.
