### ISSUE TITLE
Provide a short changelog

### ISSUE THREAD

**Issue by vanitasvitae** [copperhead/bugtracker#206]
Hi!
I'd find it useful to have a quick overview about what changed in the latest version of copperheadOS.
Is it possible to have some kind of changelog besides the commit messages in your repository?

**Comment by thestinger** [comment]
I could start keeping track of the changes and publishing a changelog along with adding changelogs to the OTAs. I was just too lazy to do it in the past. Going to want this by the time it's stable so I'll start doing it.

**Comment by thestinger** [comment]
https://builds.copperhead.co/changelog/2016.03.27.04.15.10.txt
