### ISSUE TITLE
Immediately shutdown device after too many failed unlock attempts

### ISSUE THREAD

**Issue by xmikos** [copperhead/bugtracker#207]
If you are using short PIN/pattern to unlock screen but want to have strong encryption password, it would be great if Copperhead OS monitored failed screen unlock attempts and immediately shutdown device if maximum number is exceeded (default can be 3).

I have implemented this with my [SnooperStopper](https://github.com/xmikos/SnooperStopper) app, but it needs root access (to shutdown/reboot device), which is not appropriate for Copperhead OS. This functionality should be idealy implemented on system level (same as your UI for changing encryption password).

**Comment by polyzen** [comment]
Already implemented: #86

**Comment by xmikos** [comment]
@polyzen Great! I didn't know about it... Is there some UI to configure max. number of failed unlock attempts before shutdown? If not, what is the default?

**Comment by thestinger** [comment]
It's hard-wired to be 5 for now. I could expose a setting for it in the future but I was lazy.

**Comment by xmikos** [comment]
@thestinger I would prefer 3, but even 5 is good :-)

Btw. I have tried it and it does reboot, not shutdown. It has been similar in my SnooperStopper app, but I have recently changed it to shutdown because of this report:

[ #7: Shutdown instead of reboot](https://github.com/xmikos/SnooperStopper/issues/7)
(TL;DR someone got his phone factory reset because of this when having it in his pocket)

**Comment by thestinger** [comment]
Replaced with #212. I'll consider using shutdown instead of reboot too.
