### ISSUE TITLE
recovery

### ISSUE THREAD

**Issue by canary5** [copperhead/bugtracker#208]
I cant enter recovery to update otas. It stop on entering screen and cant reach menu. Is it locked?

**Comment by darknetj** [comment]
@canary5 please provide screenshots or logs to help us debug.

Follow the Guidelines here before posting any further bug reports:
https://github.com/copperhead/bugtracker/blob/master/README.md

**Comment by canary5** [comment]
![recov](https://cloud.githubusercontent.com/assets/18005146/14002128/bd695276-f141-11e5-86f4-9a3582cbbf1d.jpeg)

**Comment by thestinger** [comment]
That's what the recovery looks like on a user build, including on stock Android. It's documented in https://copperhead.co/android/docs/install. You can update from within the OS though, no need to sideload the updates since there's an OTA update client.

**Comment by canary5** [comment]
Yes i was doing it, but i have quite bad connection. Sometimes need to update 2-3 times. And i have few phones, one download would help.
I have read it and tried sideload but stuck on that screen before menu

**Comment by thestinger** [comment]
So this doesn't work for you?

> Next, access the recovery menu by holding down the power button and pressing the volume up button a single time.

**Comment by canary5** [comment]
Yes i cant pass that screen

**Comment by darknetj** [comment]
@canary5 if you're updating for multiple phones, why not download the updates on your computer and sideload from there? That way you only need to download once.

**Comment by canary5** [comment]
Darknetj, thats what im trying to tell you. I cant get to recovery menu. Is it locked? I cant sideload. That what i was trying to tell;)) you asked screen, me added it, where recovery freezing for me

**Comment by darknetj** [comment]
@canary5 check your email as I provided you some suggestions.

**Comment by thestinger** [comment]
@canary5 You need to hold the power button for a few seconds and press volume up without releasing the power button. Is that what you're doing?
