### ISSUE TITLE
feature requests

### ISSUE THREAD

**Issue by canary5** [copperhead/bugtracker#209]
Some features i really missing for daily isage. Change device name. Battery percentage.
Also possible yo remove access to quick launch icons when screen is locked

**Comment by darknetj** [comment]
@canary5 both of those features currently exist in AOSP.

http://www.pocket-lint.com/news/135718-how-to-show-battery-percentage-on-your-android-6-0-marshmallow-device

http://www.wikihow.com/Change-the-Name-of-Your-Android-Phone

**Comment by canary5** [comment]
Thanks for percentage, but for device name  its not available in dev options
