### ISSUE TITLE
allow configuring the number of unlock attempts before reboot

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#212]

**Comment by Kiwi** [comment]
Trying to implement this. Would an option to shutdown instead of reboot be a welcome addition?

**Comment by thestinger** [comment]
Yes, that would make sense too.

**Comment by subproc** [comment]
and an option to erase?

**Comment by thestinger** [comment]
That's provided for the boot password already, and forcing a reboot leaves you there. Working on anything related to encryption would be unwise before Android N is out and CopperheadOS is migrated to it though, because it changes how all of this works.

**Comment by thestinger** [comment]
Not sure what will happen to the existing work in CopperheadOS on this yet.

**Comment by thestinger** [comment]
This feature is no longer present. It makes sense to revisit providing an alternate authentication method (#451) but it has to be done differently in order to support FBE. Anyway, it doesn't appear that this feature is wanted since no one has shown interest in working on it.

**Comment by HacKanCuBa** [comment]
I want it!! Working on it its a whole diff story :(
