### ISSUE TITLE
Viewing changelogs in OTA manager crashes (probably WebView)

### ISSUE THREAD

**Issue by vanitasvitae** [copperhead/bugtracker#218]
Hi!
When I click an update in the OTA manager to view the changelog, CyanogenModUpdater crashes (probably due to the webview bug). Enabling PaX-Softmode prevents crashes.
[Logcat](https://gist.github.com/vanitasvitae/453072f91b302863f043)
Im currently on 2016.03.21. Will update now.

Btw: congratulations to your collaborations with FDroid and the guardianproject :+1:

**Comment by thestinger** [comment]
This is the same issue as https://github.com/copperhead/bugtracker/issues/216. I don't have time to address it right now.

**Comment by thestinger** [comment]
I'm not going to manually add exceptions for each application using the WebView. The options available are:

a) Drop MPROTECT as a feature
b) Automatically mark all apps using the WebView as requiring an MPROTECT exception
c) Fix the WebView to not require an exception when JavaScript isn't used. AFAIK, it worked fine in the past. This is what should happen, but it might require a *lot* of work.

I'm unwilling to take the first path right now, and I don't like the second option. I don't have time to implement either the second or third option. PaX is only on the Nexus 5, and even if it was applied to the newer other kernels the userspace features wouldn't be available yet.

**Comment by vanitasvitae** [comment]
Okay. I just wanted to notice you about this. 
I wish I could help in another way than only submitting bug reports.

Should I stop submitting bug reports having to do with #216 then?

**Comment by thestinger** [comment]
If the traceback just has the WebView 0x8 segmentation fault and is solved by enabling soft mode, then you don't need to report it. If it's something else, I do want to know.
