### ISSUE TITLE
Add support for Galaxy Nexus

### ISSUE THREAD

**Issue by pixelrust** [copperhead/bugtracker#219]
[Galaxy Nexus](https://en.wikipedia.org/wiki/Galaxy_Nexus) devices still perform decently - is there any chance to support them?

**Comment by darknetj** [comment]
@pixelrust this is out of scope currently.

**Comment by thestinger** [comment]
We can only support devices that are still supported by AOSP. We're unable to provide updates for proprietary components ourselves, so it would be infeasible to support it even with many employees.
