### ISSUE TITLE
bundle a build of Orbot so Tor can be used from the start without needing adb install

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#220]

**Comment by vanitasvitae** [comment]
Can you use the superuser features of Orbot when installed as a system app?

**Comment by thestinger** [comment]
No, since it depends on `su` rather than system/signature-only permissions. Worth noting that Orbot now has support for transparent proxying without root via the VPN feature.

**Comment by eighthave** [comment]
How would you see this happening?  Can you just stick an official release binary in _/system/app_?

**Comment by vanitasvitae** [comment]
Is this now implemented or discarded?

**Comment by thestinger** [comment]
It's not going to be implemented right now.
