### ISSUE TITLE
Port Copperhead to Replicant

### ISSUE THREAD

**Issue by herbsmn** [copperhead/bugtracker#221]
https://replicant.us

On your website you say that Copperhead is "Open-source and free of proprietary services. Google integration is entirely optional."

If your project cares about free software, I would like to suggest that you port Copperhead to a Replicant device and base it off of Replicant so that you can have a fully free as in freedom Cooperhead option for your users.

Replicant meets the Free Software Foundation's Free System Distro Guidelines: https://www.gnu.org/distros/free-system-distribution-guidelines.html

I personally believe that you can't have security without freedom. If you agree, please at least explore this port as an option as you move forward.

It isn't an official release yet, but there's an experimental Replicant 6.0 ROM here: https://redmine.replicant.us/boards/21/topics/12057

"Nightly" builds of Replicant 6.0 for the Samsung Galaxy S3 can be found here: https://fossencdi.org/replicant/

**Comment by darknetj** [comment]
Porting our OS is currently out of scope.

If you want to port it over (or find someone to do it), feel free.
