### ISSUE TITLE
"Replace encryption password" blank screen/doesn't work without PIN/password/pattern

### ISSUE THREAD

**Issue by Kiwi** [copperhead/bugtracker#227]
So this is mostly user error and there is possibly (but not always) a warning to the user they're being stupid and might break things.

If you don't have a PIN, password, or pattern it won't let you "Replace encryption password" if you've changed it.

If the device is using Swipe or None you can still Change encryption password and have to enter that to boot, the setting Replace encryption password will be made visible; however, attempting to use the option goes to a blank page and does not remove the separate password.

If you switch to a PIN, password, or pattern it will make the option work as expected.

The only warning user might encounter occurs if they switch to Swipe or None from a PIN, password, or pattern. The warning actually implies it would be removed by saying device protection will be disabled but doesn't remove the separate password which is kind of ironic.

**Comment by thestinger** [comment]
It should work without a lockscreen PIN/password but it doesn't currently handle that case.

**Comment by thestinger** [comment]
This feature no longer exists due to the switch to Nougat. This might not be a problem when either it's reimplement or another feature is done instead.

**Comment by Vodochnik** [comment]
Hi Daniel,

any chance to get this feature in Nougat soon?
Or any chance to get latest Marshmallow build for 5x bullhead WITH this feature?
I _really_ need it.
Thanks in advance
