### ISSUE TITLE
Chromium SSL/TLS interstitials broken

### ISSUE THREAD

**Issue by graxlop** [copperhead/bugtracker#229]
My device is the Nexus 5, running the latest CopperheadOS.

Ever since one of the recent Chromium updates, I've noticed oddities with Chromium's SSL certificate interstitials and the detailed connection info. They seem to show either inaccurate info or just broken HTML code in the case of the interstitials.

Screenshots attached showing both problems. Some example interstitials can be found on the site below (ex. bad host, expired cert, etc.)

https://badssl.com/

![screenshot_20160405-051809](https://cloud.githubusercontent.com/assets/17195442/14276718/e38a8456-faed-11e5-92da-61fce2b10066.png)
![screenshot_20160405-051833](https://cloud.githubusercontent.com/assets/17195442/14276743/fe5cc2b2-faed-11e5-9340-a031fc70d668.png)

**Comment by thestinger** [comment]
There are no modifications to the Chromium build used in CopperheadOS, so there's nothing for us to do beyond continuing to update it.

**Comment by thestinger** [comment]
Do you use a different locale than US English? Might be worth trying that. I might not be asking it to build the other locales... don't know what I'd need to change though.

**Comment by graxlop** [comment]
I'm using US English. It also seems to show up in chrome://history

![screenshot_20160405-201908](https://cloud.githubusercontent.com/assets/17195442/14303642/040935c4-fb7a-11e5-81a7-29207f4e7188.png)
![screenshot_20160405-201636](https://cloud.githubusercontent.com/assets/17195442/14303667/287d6b28-fb7a-11e5-8e31-b98759ec7f26.png)

**Comment by thestinger** [comment]
This is caused by not using the Chromium linker due to #202. I don't want to track upstream Chromium issues here. The only approach that will be taken here is fixing compatibility with the usual custom linker.

**Comment by thestinger** [comment]
Here's an upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=630863/.

**Comment by thestinger** [comment]
Since #202 has been fixed, this problem will be avoided by using the Chromium linker again. The upstream bug is still present and I'd like to disable the Chromium linker again once it's resolved though.
