### ISSUE TITLE
Dropped support for exchange server?

### ISSUE THREAD

**Issue by christoph-buente** [copperhead/bugtracker#230]
Thx for a new update (MHC19Q.2016.04.06.11.37.02) with the latest f-droid client.

After the latest update for my LG nexus X5 my emails were gone from my device. Also all my calendar entries. When checking my email client, no mail account seems to be present. I was a bit irritated. And when i tried to add the exchange account again, i could not find it anymore. Has exchange support been dropped? Is there a changelog for the releases, so i could know what has been changed with each release upfront and without surprises?

Cheers, Chris

**Comment by thestinger** [comment]
Google dropped support for it in master and then backported that change to the new marshmallow branch (https://android.googlesource.com/platform/build/+/6019adf259eb304f206907fb695c33706b8c2714). The changelog does mention that we moved to the new upstream branch: https://builds.copperhead.co/changelog/2016.04.06.11.37.02.txt. It isn't ever going to summarize the changes made upstream, only our own changes including when the base OS is upgraded.

If you want exchange support, you'll need to use another calendar and email client. The standard email client and calendar are close to unmaintained upstream.

**Comment by thestinger** [comment]
In stock Android, they moved the functionality to the proprietary Gmail app. It's part of the ongoing process of user-facing AOSP apps being replaced by proprietary Play apps. The only solution is bundling new open-source applications as replacements but users can install them from F-Droid either way.

**Comment by thestinger** [comment]
Also, you can look at the changelogs in the OTA update client by touching the update listing. I think it works...

**Comment by christoph-buente** [comment]
Thx for the hint with the changelog. It actually works :)

I understand that you are not responsible for upstream change. I just was not aware of those things going on. I tried to rollback the update and install the previous version, but the update fails. Is this possible at all without flashing the whole device?

Thx

**Comment by thestinger** [comment]
It's not possible to install older updates in production builds of Android for security reasons. It uses the build date rather than a version comparison. I don't think the MMB29X build has all of the security updates since I couldn't update the proprietary components (no factory image from them) so it isn't a great option (and it won't be there next month either).
