### ISSUE TITLE
Nexus 5X: no data

### ISSUE THREAD

**Issue by Rudd-O** [copperhead/bugtracker#232]
Icon does not show 3G or 4G, there is no data on my phone after latest update.  Only Wi-Fi works.

2016.04.06.11.37.02

Thanks.

**Comment by thestinger** [comment]
Try deleting the APN information and adding it back again, The only changes are the upstream ones by Google.

**Comment by Rudd-O** [comment]
On 04/09/2016 03:08 PM, Daniel Micay wrote:
>
> Try deleting the APN information and adding it back again, The only
> changes are the upstream ones by Google.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/copperhead/bugtracker/issues/232#issuecomment-207804729>
>

Copying the APN settings from another phone, then rebooting, worked to
give me my Internet back.

-- 
    Rudd-O
    http://rudd-o.com/

**Comment by thestinger** [comment]
It's just the usual lackluster APN database in AOSP then. I don't want to maintain a forked version like CyanogenMod, so manually configuring APNs will often be required.

**Comment by Rudd-O** [comment]
On 04/09/2016 04:28 PM, Daniel Micay wrote:
>
> It's just the usual lackluster APN database in AOSP then. I don't want
> to maintain a forked version like CyanogenMod, so manually configuring
> APNs will often be required.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/copperhead/bugtracker/issues/232#issuecomment-207815725>
>

There has to be an actual solution that can be incorporated at build
time, such as merging their database, or pushing changes upstream.

-- 
    Rudd-O
    http://rudd-o.com/

**Comment by thestinger** [comment]
Non-security-related work on AOSP is out of the scope of the CopperheadOS project. There doesn't have to be any solution to those problems here. Someone else can work on it in AOSP.

**Comment by thestinger** [comment]
Manually configuring APN settings is to be expected with an unlocked phone in the general case. The built-in database is a convenience. It will never be fully complete or up-to-date. Merging CyanogenMod's database might makes things better overall, but it would introduce new problems and would be *far* from a complete solution. It's better to leave the vanilla APN database alone as I can just defer to them rather than wasting time on this.
