### ISSUE TITLE
Date and time reset after poweroff on N5

### ISSUE THREAD

**Issue by reenz0h** [copperhead/bugtracker#234]
Nexus 5 poweroff resets the date and time (reverts it to December 1971), when:
1. SIM card not present in the device
2. "Automatic date & time" is off
3. "Automatic time zone" is off

Phone model: **Nexus 5**
Build number: **MMB29X.2016.04.05.04.42.49**
Security level set: **middle** (no additional sec features turned on)
Language: **English**

**Comment by thestinger** [comment]
This is an upstream issue in AOSP. The time service might not have the necessary permissions to set up the RTC correctly (perhaps missing SELinux policy and/or incomplete user build support in AOSP). I'm no longer going to be working on *upstream* issues on the Nexus 5, so someone else will need to take this on if it's going to be fixed.

**Comment by thestinger** [comment]
Nexus 5 support is winding down as 7.0 approaches so further work on it isn't going to happen.
