### ISSUE TITLE
"Mobile standby" and battery drain on Nexus 5x

### ISSUE THREAD

**Issue by n1m1** [copperhead/bugtracker#235]
Hello,
on my new Nexus 5x I am detecting high percentages of mobile standby which are the reason of a huge battery drain. However, I don't have any evidence that this problem is related to Copperhead.

This usually happens when my device switch from WiFi to 4G . At that point, even if I switch again to WiFi, mobile standby (and battery drain) persists. The only way to fix this is rebooting the device. Moreover, in this particular situation (WiFi -> 4G -> WiFi) I can't switch again to 4G: mobile data is not working any more.

APN settings are correct. Furthermore, before writing this post, I've also tested a new SIM card: nothing change.

Thanks in advance for your attention.

P.s: Copperhead is really great.

**Comment by thestinger** [comment]
That's almost certainly an upstream Android issue or a hardware issue. Worth noting that more power will be drained if the signal is poor.

**Comment by n1m1** [comment]
Correct. 
Browsing around I've seen that actually lot of devices running 6.0.1 are affected by this issue. A popular suggestion for fixing the bug is that of performing a factory reset. I could give a try to this (even if I am not very convinced) but... 

How can I backup my device since I am not root (therefore I can't use oandbackup which seems to be the only app on F-Droid useful for this purpose). Any suggestion about the methods I could employ to backup contents and apps on CopperheadOS?

Thanks.

**Comment by thestinger** [comment]
You can use `adb backup` (with the appropriate flags, something like `adb -f backup.ab -all -shared` and then `adb restore backup.adb` IIRC).

**Comment by n1m1** [comment]
Great.
Thanks for the prompt answer.
