### ISSUE TITLE
Nexus 5 won't boot into recovery mode

### ISSUE THREAD

**Issue by suradasa** [copperhead/bugtracker#238]
Just installed Copperhead from hammerhead-factory-2016.04.15.02.07.53.tar.gz, and it won't boot into recovery mode. Just gives me the android lying down with !. (I also tried the 4.10 version)

**Comment by thestinger** [comment]
That is the recovery mode. The menu is hidden by default on production (user) builds since there are other ways for a user to end up there. You need to hold the power button and press the volume up button while still holding down power to get to the menu.
