### ISSUE TITLE
add support for nexus 7 flo (wifi only, 2013)

### ISSUE THREAD

**Issue by latestNexusFlo** [copperhead/bugtracker#240]

**Comment by latestNexusFlo** [comment]
From Twitter:
@HackDefendr The CM13 port isn't really ready yet. You should probably be building from CM12.1. Or you'll just run into known issues.

I built Copperhead CM12 too. I just wanted to let you know :)

@HackDefendr Note that for the CM12.1-based version, there are mandatory changes required in the device repository for text relocations.

@HackDefendr You need to switch from execmem -> execmod to allow text relocations. Can take a look at the hammerhead of jf device repos.

@HackDefendr And once that's done, everything should work fine. But you'll need to port the MAC randomization kernel patch and all of PaX.

@HackDefendr Anyway, interested in hearing how it goes. Just don't want you to get stuck on stuff that we know is an issue already.

@HackDefendr was offering to support a build for flo.
Interested in knowing more about this.

**Comment by thestinger** [comment]
It wouldn't be that hard to add support without PaX at a source level, but it would take a lot of resources to start testing and publishing builds for it. Google might drop support soon, and that would take it off the table for CopperheadOS.

**Comment by latestNexusFlo** [comment]
Nexus 7 flo is the only Wifi-only tablet small enough to be used as a smartphone.
For those of us who don't trust closed baseband chips it is one of the only options.

I'm wanting to update Mike Perry's https://github.com/mission-impossible-android/mission-impossible-android for the flo, using Copperhead OS. Happy to write the documentation but would need some help getting Copperhead installed on the flo. Would be better if you provided signed binaries. Otherwise I'll do my best building from source but the community has no reason to trust my packages.

**Comment by thestinger** [comment]
We can't afford the necessary resources (2 of each device and a powerful build server) for expanded device support. We're planning on running a crowdfunding campaign soon, but that's going to take a while, and that's only to support the Nexus 6 and 6P.

Once that happens, this becomes a matter of development time. The initial port is not that much work. It's the added maintenance burden for every release that's a big issue. It needs to be built, flashed onto a device and manually tested. The second device would be used to run the Compatibility Test Suite. Then, the problems that are discovered (and there will be problems) need to be narrowed down and debugged. If there's funding for the work, I will do it, but I'm not willing to spend my free time working on support for a device that could easily be dropped by the end of the year.

**Comment by latestNexusFlo** [comment]
Understood, thanks for your prompt and comprehensive response.

It would be useful if, between your project, Tor, and ReplicantOS we could have a reasonably secure Wifi-only tablet which is small enough to be used as a phone paired with a portable LTE Wifi router.

Realistically, what could be done towards this with a donation of $5k?

**Comment by thestinger** [comment]
5k is probably enough to add another Nexus device, port PaX to it and then maintain it until Google drops support once we have a build server. It's not enough to build a proper build server though. I really can't do it right now because it will take too long to build for it.

However, if they stop releasing security updates for a device, I'll need to drop it. I expect that the Nexus 5 and 7 won't get 7.0 when it comes out around October, but I plan on keeping a 6.0 source tree alive for them with security updates if Google continues to release them. I wouldn't be porting every new security feature over to them though. It would be maintenance-only mode to extend the lifetime of devices we already supported in the past.

**Comment by thestinger** [comment]
And who knows, maybe Google will release a new small Nexus tablet soon.

**Comment by thestinger** [comment]
I don't want to add any devices that are likely not going to get N.

**Comment by hackdefendr** [comment]
That's fine...its just that the Nexus 7 was one of the first to have Kali Nethunter, and with the Copperhead hardened OS, there would have been a lot more devices being used. 

By the way...

Nexus 7 Wifi-only 2013 has the 1.5ghz dual-core cpu with 2gb ram and will definitely get 7.0 when it's released...there really isn't a reason not to support it through next year. 

The 2016 will probably be 4-times that and should be considered heavily for future copperhead development.

**Comment by thestinger** [comment]
It's not a sure thing that Google will upgrade the Nexus 5 and Nexus 7 to Android N. They aren't supported by the N preview. The Nexus 4 didn't get Marshmallow. They have a lot of incentive to drop all 3.4 kernel devices so they only have to deal with >= 3.10.

**Comment by hackdefendr** [comment]
Um...Nexus 7 (flo) has an N-Preview2. I built an image myself and am running it.

**Comment by thestinger** [comment]
The fact that it hasn't been removed from the source tree doesn't mean it has an N preview release. There is no release of the updated drivers for a proper build. Every CopperheadOS release has to correspond to an upstream factory image, since we can't provide full updates from source code alone.

**Comment by hackdefendr** [comment]
Again...

I have Preview 2 for the Nexus 7 (flo) built and fully running on my device.
Source tree timestamp - Apr 14 20:56:49 2016 -0700

But whatever, you don't even have an N7 so what do you know?

**Comment by thestinger** [comment]
The factory images or driver releases are a requirement for official CopperheadOS support. It doesn't matter if it can be built from source and boot without it. The standard for device support is different than it is in CyanogenMod. It's not possible for us to provide a correct set of proprietary components without them releasing their own builds, and that's a hard requirement.

**Comment by hackdefendr** [comment]
Like I said 36 minutes ago...That's fine.

I was just stating that the N7 would have given you a much wider customer base, at least thru 6.0.1. With all the security pros I know that use that device with Kali Nethunter, having a hardened OS would have been really nice.

I really stopped pushing a long long time ago...someone else re-opened the discussion only to find out what I was already told months ago.

**Comment by thestinger** [comment]
People downloading the OS aren't our customers. It's free. Very little is accomplished by expanding device support unless someone is going to fund the work.

The priority for device support is the Nexus 6P, and then the upcoming Nexus devices. Supporting an older 32-bit device with a 3.4 kernel, no verified boot and likely no official 7.0 images doesn't make much sense at this point. It would have made sense a year ago. It could have been supported rather than the S4, and then it would still be supported today.
