### ISSUE TITLE
Fingerprint + PIN/password screen unlock

### ISSUE THREAD

**Issue by mhyqwvcu** [copperhead/bugtracker#241]
[FR] Option to require a PIN/password when using a fingerprint. In addition to a strong main password.

I'm not sure if this is possible with how things work in Android but it would protect against entry when the user is dead/asleep. Brute force protection as well when the phone is stolen for example?

**Comment by thestinger** [comment]
See #150.

**Comment by vanitasvitae** [comment]
Nice usecase by the way :+1:

**Comment by mhyqwvcu** [comment]
Thanks @thestinger glad to see it's in the pipeline.
