### ISSUE TITLE
IDS

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#243]
It would be cool to have optional built-in IDS support. It's not possible to do this well without it being built into the OS due to lack of privileges, especially as the app sandbox is hardened. It's an area where CopperheadOS could provide a real edge. Android has SafetyNet, but that's meant to protect the ecosystem as a whole, not individuals.

**Comment by xmikos** [comment]
It would be great if it could also detect QUANTUM INSERT attacks, see here: [Deep dive into QUANTUM INSERT](https://blog.fox-it.com/2015/04/20/deep-dive-into-quantum-insert/) (configuration for Bro, Snort and Suricata IDS here: https://github.com/fox-it/quantuminsert/tree/master/detection).

Not only NSA, but now even Chinese, Malaysian and Indian malware and ad networks seems to be doing QUANTUMINSERT-style man-on-the-side attacks: [Website-Targeted False Content Injection by Network Operators](http://arxiv.org/abs/1602.07128)

**Comment by thestinger** [comment]
Not planned.

**Comment by thestinger** [comment]
This is going to be revived as part of our Auditor app: https://github.com/copperhead/Auditor/issues/27.
