### ISSUE TITLE
sanitizers detect an issue in sdcard service, making FUSE fs unavailable

### ISSUE THREAD

**Issue by Bmme2GFTbU** [copperhead/bugtracker#246]
The Update from today killed my /storage/emulated folder. Its only available as a link, so far I could see.

**Comment by Bmme2GFTbU** [comment]
Update for Nexus 5, sorry missed

**Comment by thestinger** [comment]
It's an sdcard service bug detected by one of the sanitizers. The upstream bug needs to be found and fixed. Can't easily do that in a normal user build since there are no debugging symbols and trapping UBSan doesn't provide any guidance without that.

**Comment by denharad** [comment]
This also happened to me. Is the data gone or just unmounted and is there any quick fix?

**Comment by vanitasvitae** [comment]
Are all the files still there? I can't see them from my computer. I'm a little bit worried about my data.

**Comment by vanitasvitae** [comment]
@denharad: I just checked my file structure via TWRP. In my case the files are still there when android isnt booted *pfew*

**Comment by thestinger** [comment]
No data is lost. As I said, it's a bug caught in the sdcard service by one of the sanitizers. It occurs a lot more frequently on 64-bit (or there are multiple issues) which is why it wasn't caught in testing. CopperheadOS didn't introduce the bug, it just detected it. I could make new builds with the sanitizers disabled again, but that will waste a day that could be spent fixing the issue which is what I plan on doing.

**Comment by vanitasvitae** [comment]
@thestinger That's okay for me. I think I can spend some days without my files. I'll try to push the important files to my desktop for now.

**Comment by thestinger** [comment]
Don't have the resources to do thorough testing so issues like this will happen, and it's going to take a while to resolve due to the long build times.

**Comment by thestinger** [comment]
Alright, I think it's fixed. I was just a benign overflow. Testing it again, and then I'll push out new builds.

**Comment by thestinger** [comment]
Just need clean builds to publish now. Going to take a while.

**Comment by thestinger** [comment]
New builds are published for the Nexus 5 and 5X. Nexus 9 coming later.

**Comment by vanitasvitae** [comment]
I can confirm that this is fixed on hammerhead :+1:
