### ISSUE TITLE
Orbot wont connect to  tor

### ISSUE THREAD

**Issue by rowdyray** [copperhead/bugtracker#249]
![torerror](https://cloud.githubusercontent.com/assets/18713340/14876157/7a41f0b2-0d01-11e6-9039-d768ae608dbb.png)
Copperhead Kernel Version Tue April 26, Nexus 9

**Comment by thestinger** [comment]
Which version of Orbot are you using?

**Comment by vanitasvitae** [comment]
Looks like an older version.
Try to kill Orbot from within Androids settings section "apps" and restart it.

**Comment by thestinger** [comment]
Older versions might not work on Marshmallow.

**Comment by vanitasvitae** [comment]
See https://trac.torproject.org/projects/tor/ticket/17968
This issue can be closed.
