### ISSUE TITLE
Unable to restore factory (shamu) ROM to Nexus 5

### ISSUE THREAD

**Issue by gethob1** [copperhead/bugtracker#252]
Thanks for bearing with my long explanation.
Perhaps you can direct me in a different, unexpected way than where I'm going now.

Please note I am not asking you to support use of unverified/untrusted apps or otherwise apps from outside the Copperhead-approved repository.  I realize you don't support them.  I'm only using them because I have no choice (certain apps like 'google maps' are required for my job) and I could use advice on how to best approach this given my dependency on these risky apps.  I still believe that Copperhead with these risky apps is better than using the stock Android ROM, therefore I'm intentionally breaking the rule of not installing unverified/untrusted apps as to retain job-critical functionalities and some security better than Android.

Unfortunately Google Play Store doesn't work when I try to install it (I gather you don't support it) and worse, Google doesn't make APKs available and hence why I installed third-party APKs knowing at this point it was defeating, at least in part, the whole purpose of having a secure smart phone.  I installed about 6 unverified apps from outside the F-Droid repository which worked like a charm mostly.  But within just a few weeks it seemed to be doing things it shouldn't (I know, surprise!) like downloading .json files, injecting fake updates, or at least as far as I could tell.  Maybe this behavior was normal...

I think the last update was fake because I couldn't find the same update on Copperhead website and it caused my phone to lose 3G/data immediately and uninstalling it did not restore 3G/data.  Also I noticed I was unable to export or import .vcf, resulting in great frustration and loss of time.  Unfortunately I didn't think to record the filename of that supposed fake update, but to be sure, I had automatic updates set to daily, always updating every one that's available as released, and there were none on Copperhead website for that day.  There was a total of 3 on the website and 4 on my phone.  I uninstalled it but the damage was done, and have since re-flashed Copperhead.  Anyway if somehow it was a legitimate update it didn't seem to be listed on Copperhead website.

Still in need of certain apps only available in Google Play Store I decided to try re-flashing my device with the factory Android ROM, 'shamu-mmb29x' which I downloaded from [](https://dl.google.com/dl/android/aosp/shamu-mmb29x-factory-ef4cbb75.tgz) (is that the right source, by the way?) with the hopes of using an app called APK extractor [](https://play.google.com/store/apps/details?id=com.ext.ui) to create package files that would hopefully not be malicious and would be safer than those from 3rd party web sites.  Of course, who knows what this app is actually doing but being a highly rated app on Google Play Store it seemed a somewhat better option than https://apkpure.com/ !

But when I tried to flash the factory Android ROM with `sh flash-all.sh` it fails with a few warnings of significance:

> writing 'bootloader'...
> FAILED (remote: invalid bootloader image)

> writing 'radio'...
> FAILED (remote: size too large)

> checking product...
> FAILED
> 
> Device product is 'hammerhead'.
> Update requires 'shamu'.

I tried using fastboot to erase the partitions and all data but I'm unable to find the correct command to do so if any exist.  Factory reset does nothing, and I'm unable to find the names of the partition tables to delete them.  Fastboot just says:

> FAILED (remote: Partition table doesn't exist)

So it appears re-flashing my device with the factory 'shamu' ROM is not allowed / practical for me.  I need to get my phone back up and running ASAP so at this point my plan is to just re-install Copperhead, thus restoring my 3G/data.  However, I'm now without several critical apps and am considering just installing back the same untrusted ones-- this time disabling automatic updates, and manually downloading them from my computer and sideloading them.   So while the security of the system may still be at risk due to these 3rd party apps it seems like they had to get me to download a fake update in order to break my 3G/data.  Again I realize none of this is supported/ideal but I'm in a difficult situation requiring both Play Store apps and enhanced security.

Please advise improvements to my approach or suggestions on how to install the factory Android ROM without the above errors so I may derive APKs from Play Store and not 3rd party websites.  For now my plan is to just keep using the 'apkpure' ROMs until something breaks but hopefully only sideloading updates directly from Copperhead website will prevent what happened this time.

Thanks for your time.

**Comment by polyzen** [comment]
This was incredibly long.

> I think the last update was fake because I couldn't find the same update on Copperhead website

Problematic updates are regularly (afaics) removed from the Downloads page. If used as intended (read: using the built-in updater and CopperheadOS recovery), ChOS verifies the update, so it being a fake update is highly unlikely, if even possible.

> Device product is 'hammerhead'.
> Update requires 'shamu'.

Nexus 5 is "hammerhead." 6 is "shamu."

**Comment by gethob1** [comment]
Thanks, I think I now have a much clearer understanding of what's going on and how to proceed.

If later I decide to try installing the stock hammerhead and encounter the same problem I'll post back here.  For now proceeding with Copperhead re-installation.

Again, I don't know if the update broke my 3G/data access, the break did occur immediately after the update, and removing the update didn't fix it.  If the update wasn't responsible for the break, then perhaps my carrier was to blame.  Obviously 3G/data outages aren't unheard of, but I hope to rule out "problematic updates" as the cause.

**Comment by gethob1** [comment]
Wait, I think I've found the name of the update that breaks my 3G/data connection upon installation from the built-in updater.
hammerhead-ota_update-2016.04.26.16.55.03
I noticed its "version" is different than all other updates.
MOB30D.2016.04.26.16.55.03   vs.  the previous MMB29X........
It doesn't seem right but I'd appreciate it if you can tell me if I'm not supposed to install MOB30D when my installation is MMB29X or if the version discrepancy is a problem or meant to be an upgrade?

Thanks kindly.

**Comment by polyzen** [comment]
MOB30D is the latest android build.
https://developers.google.com/android/nexus/images#hammerhead

**Comment by gethob1** [comment]
Nevermind, it's the carrier.

**Comment by polyzen** [comment]
Please close this if it's resolved. \o/

**Comment by gethob1** [comment]
Ok, I'll open a new ticket if I need to install the factory Hammerhead.  Closed.
