### ISSUE TITLE
Default mail app broken in latest 5x build

### ISSUE THREAD

**Issue by adpaolucci** [copperhead/bugtracker#264]
Default mail app crashes when you attempt to open emails, ADB output of the crash is attached in full.

https://paolucci.ca/mailfailure-20160515-bullhead_cOS.log
Latest cOS build on Nexus 5x
bullhead-factory-2016.05.08.05.30.34

**Comment by adpaolucci** [comment]
Marking as closed as the latest build solved this issue.

**Comment by thestinger** [comment]
There weren't any changes related to this.

**Comment by thestinger** [comment]
Let me know if it happens again. I'm really curious about it.
