### ISSUE TITLE
"Your device has loaded a different operating system."

### ISSUE THREAD

**Issue by tobia** [copperhead/bugtracker#265]
I haven't found this mentioned in the install documentation or here in the issues.

Is there a way to remove the [Yellow Warning](https://support.google.com/nexus/answer/6185381#yellow_warning) without loading a different bootloader and decreasing security? (Nexus 5X)

I understand the purpose of this warning, but really, I have had my "different OS" installed for more than a week. Is Google going to bug me forever for ditching their default image?

**Comment by thestinger** [comment]
No, there isn't a way to remove it. It's verified boot informing you that the OS is signed with a different key than the hard-wired one. There is no way to install a different bootloader it there's signature verification for it. This is how verified boot works.
