### ISSUE TITLE
Screenshot combination broken

### ISSUE THREAD

**Issue by tobia** [copperhead/bugtracker#266]
The screenshot combination (Power + Volume down) does not seem to do anything on my 5X with latest OS version.

If this is a security measure of some sort, what is the recommended way to take screenshots for debugging or other purposes? Is there a way to enable it?

**Comment by thestinger** [comment]
There's no change to this in CopperheadOS. It works fine here. You need to press them at the same time, not one after the other. The time delay for this is very small.

**Comment by tobia** [comment]
It definitely does not work on my 5X.

**Comment by thestinger** [comment]
It's not very easy to make it work here but it does work. I think they must have tightened up the timing a lot in 6.0, perhaps because of the double-tap power to open camera feature. They added another way to do it but it requires Play Services...

**Comment by polyzen** [comment]
With Play Services, I get the error "Couldn't capture screenshot".

**Comment by thestinger** [comment]
The service involved probably doesn't have sdcard access. Check the logs for a security exception. The normal way works for you though, right?

**Comment by polyzen** [comment]
Thank you, I will look at that. The normal way being without GApps? Haven't tried. :p

**Comment by polyzen** [comment]
```
32688 32688 W SoundPool:   sample 1 not READY
 3030  3111 I art     : Background concurrent mark sweep GC freed 10025(602KB) AllocSpace objects, 2(48KB) LOS objects, 40% free, 11MB/19MB, paused 819us total 241.510ms
 1979  1988 I art     : Background partial concurrent mark sweep GC freed 7666(443KB) AllocSpace objects, 0(0B) LOS objects, 33% free, 27MB/41MB, paused 17.320ms total 381.517ms
```
