### ISSUE TITLE
Verbose boot

### ISSUE THREAD

**Issue by tobia** [copperhead/bugtracker#267]
Seeing as CopperheadOS seems to take quite a bit of time to boot up (I'm sure it's due to the security features), is there a way to enable some sort of "verbose boot" instead of (or below) the animated logo?

A Linux-like text log would be great.

**Comment by thestinger** [comment]
CopperheadOS isn't going to make changes unrelated to hardening, especially substantial ones like this. It's out-of-scope for the project.
