### ISSUE TITLE
Alarm halts when screen locked

### ISSUE THREAD

**Issue by MelReynolds** [copperhead/bugtracker#276]
Steps To Reproduce The Bug:

Set an alarm via Clock app, then lock screen (manually or let system time out). When alarm activates it sounds very briefly, then stops. The alarm displays as missed in notifications.

CopperheadOS version: 

MTC19T.2016.05.17.11.18.09

Device Model:

Nexus 6P Angler

Logcat:
[Nexus6p.AlarmHaltsWhenScreenLocked.txt](https://github.com/copperhead/bugtracker/files/287187/Nexus6p.AlarmHaltsWhenScreenLocked.txt)

**Comment by thestinger** [comment]
This is an upstream AOSP bug, see #231. Most of the issues seem to have been fixed by rolling back the translation changes, but this issue is still around. I'll try porting over a fix for this now the scope is much smaller.

**Comment by MelReynolds** [comment]
Apologies for the duplicate! Thank you for your work. Enjoy using the OS.

**Comment by thestinger** [comment]
It's sort of a duplicate: there were a dozen issues from translation brokenness in that thread, and this was mixed in with all of the rest.

**Comment by thestinger** [comment]
I applied a fix that should take care of this for the next release. There are too many of these upstream issues in the dr1.6 branch for me to fix them all though. I'm really only doing this because it keeps coming up.
