### ISSUE TITLE
ota updater doesn't work in nexus 6p

### ISSUE THREAD

**Issue by subproc** [copperhead/bugtracker#278]
hi, i can download the update, but if i try to install it when the phone reboot i can only see a dead android robot whit a red exclamation mark saying error...
the log in recovery say:
Supported API: 3
Finding update package...
I:Update location: @/cache/recovery/block.map
Opening update package...
sysutil: failed to read block device from header
sysutil: Map of "@/cache/recovery/block.map" failed
E:failed to map file
Installation aborted
I:Saving locale "en_US"
E:unknown volume for path [/sdcard]

-- Couldn't mount /sdcard.
Installation aborted.
I:Saving locale "en_US"
I:Saving locale "en_US"
E:unknown volume for path [/sdcard]

-- Couldn't mount /sdcard.
Installation aborted.
I:Saving locale "en_US"
I:Saving locale "en_US"

what you think about?
i'm on the first release for 6p

**Comment by subproc** [comment]
but i can do "adb sideload" with no problem

**Comment by thestinger** [comment]
Can you try deleting it and downloading it again? It won't work if it fails the first time, since the download is "corrupted" in the process of converting it to the format for the update.

**Comment by subproc** [comment]
now i can't, but later i give it a try...now i'm on the new release (with adb sideload), how can i backup all to reflash the first release and try another time the ota updater? it's "adb backup -s -all"? or i have to use another syntax? 
p.s.: amazing work whit this rom!!!! keep up the good job..

**Comment by n1m1** [comment]
Just for the record. It has recently happened also to me on the 5x. 
Deleting the download and re-applying the update via OTA usually fixes the problem.

**Comment by thestinger** [comment]
I need clarification on what happens. It's known that trying to apply an update again will fail, and that's the error being reported here. The information I need is what causes the update to fail in the first place, not on subsequent attempts.

**Comment by thestinger** [comment]
I expect that it's probably just the known reboot to recovery failure, where it reboots back into the OS. So the failure isn't actually related to the update system, but rather whatever causes booting into the recovery to occasionally fail.

**Comment by subproc** [comment]
i'm updating from MTC19T.2016.05.24.21.38.49 to MTC19T.2016.05.28.01.02.27 through the OTA updater and IT WORK flawlessly...

**Comment by subproc** [comment]
i'm going to close this bug, 'cause seems that your solution (deleting and downloading another time the update) works...
