### ISSUE TITLE
Amazon App Doesn't Work With The Latest Release

### ISSUE THREAD

**Issue by asdf-asdf** [copperhead/bugtracker#279]
The Amazon App store is the only application manager that seems to work on secondary accounts in Android. 
Ever since the latest update, it seems to crash constantly, and is not able to install applications. It worked well with previous updates. I just switched back to the 5/17 update, and it is stable. I forgot to grab logs for it, but if you need them I will update my phone and provide the logs. 
I currently have all security settings on, respect legacy permissions turned off, and the allocation quarantine size set to 1mb. 

Here is the link to the Amazon app store - http://www.amazon.com/gp/mas/get-appstore/android

Edit: forgot to mention, I'm using a Nexus 5x

**Comment by thestinger** [comment]
I think I know why this happens. Signature permissions were limited to system apps. It needs to be a bit more precise and limit only platform signature permissions to system apps. I'll try changing that and will do a new release since there was another fix too.

**Comment by thestinger** [comment]
This has been fixed and will be included in the upcoming release.

**Comment by asdf-asdf** [comment]
thank you very much!
