### ISSUE TITLE
dnscrypt 

### ISSUE THREAD

**Issue by subproc** [copperhead/bugtracker#281]
i know that someone have asked to remove google dns or every google-query, but would be interesting for a security/privacy oriented rom, like copperhead os, use dnscrypt  to encrypt all dns queries...
sorry for my bad english ;-)

**Comment by pablomh** [comment]
Yes, please.

**Comment by thestinger** [comment]
Not going to be implementing a non-standard protocol like this when DNS-over-TLS exists. Regardless, it should be implemented upstream. It's not going to be done in CopperheadOS.

**Comment by spacekitteh** [comment]
Do you use DNS-over-TLS?

**Comment by thestinger** [comment]
No, it's not implemented.
