### ISSUE TITLE
Nexus 5X occasionally stalls at the Google logo during boot

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#285]
This might be an issue on other devices too.

**Comment by darknetj** [comment]
N5 doesn't have this issue on latest release

**Comment by rveeblefetzer** [comment]
I just installed Copperhead on a brand-new 5x, and I'm bootlooping

**Comment by thestinger** [comment]
That's not the same as this issue (stall != reboot). Did you follow the installation instructions, including using an up-to-date fastboot?

**Comment by rveeblefetzer** [comment]
sorry, maybe I misspoke; I can't tell if it's a bootloop. It's hanging on the Copperhead logo, but I do not ever again see the Google logo. You're right, though; I'm in need of updating my SDK. 

Aside: I'm sorry for clogging up the bugtracker. Is there an online community somewhere where I can ask questions?

**Comment by thestinger** [comment]
https://www.reddit.com/r/copperheados

**Comment by thestinger** [comment]
If you lock the bootloader, it should pass the boot verification steps (and state that an alternate OS is loaded - yellow icon means it passed). If it doesn't, you need to unlock and flash it properly.

**Comment by rveeblefetzer** [comment]
Thanks @thestinger. Joined -- thanks for the answers, and for the work into this

**Comment by Rudd-O** [comment]
N5X def does this to me.  At least once a week.  The bootloader is locked.

**Comment by thestinger** [comment]
This is resolved.
