### ISSUE TITLE
since update wifi don't work on nexus 5x

### ISSUE THREAD

**Issue by bichem93** [copperhead/bugtracker#288]
Since update bullhead-factory-2016.05.28.01.02.27, on my nexus 5x, wifi can't connect to the router.

**Comment by thestinger** [comment]
There haven't been any changes that could cause this and it still works fine here. Reset your network settings in Backup & reset -> Network settings reset and see if that fixes the problem. If you installed a while ago, scanning MAC randomization would have been enabled in the wpa_supplicant template and it doesn't work properly for the 5X.

**Comment by bichem93** [comment]
Thank you so much for your fast answer, since I deactivate Mac randomization It work fine.
