### ISSUE TITLE
Is it possible to install Google Play on Nexus 5X?

### ISSUE THREAD

**Issue by bichem93** [copperhead/bugtracker#289]
I need to install Google Play because of Google's GCM.
So is there a solution to install it or all gapps on Nexus 5X?
Thanks

**Comment by thestinger** [comment]
It's possible, but there's no existing way to do it without as substantial loss of security due to needing an insecure third party recovery image and verified boot disabled. It's not something that's going to be officially supported either way.

**Comment by bichem93** [comment]
Thank you for your answer.
If you just can send me a link which explain how to do this?

2016-05-31 1:19 GMT+02:00 Daniel Micay <notifications@github.com>:

**Comment by polyzen** [comment]
> If you just can send me a link which explain how to do this?

These should be sufficient:
https://github.com/copperhead/bugtracker/issues/105#issuecomment-167040110
#104
