### ISSUE TITLE
Copperhead Limitations Root?

### ISSUE THREAD

**Issue by BobsUncle** [copperhead/bugtracker#292]
Sorry I am new to Android just purchased a 5X just because of the copperhead project 

So, because copperhead hardens android I can't run apps like XPosed & XPrivacy or take full advantage of orbot, etc? 

Anyway around it?

**Comment by thestinger** [comment]
Orbot transparent proxying works fine via the VPN feature. Use the current version from the Guardian Project repository.

There won't be any official guidance on doing things that would compromise security like integrating XPosed or a root implementation, *especially* if it's done via hacks like sideloading which break verified boot and require an insecure recovery.

If there are useful (i.e. not hacks at a Java layer that can be bypassed) components of XPrivacy that are missing, then those could be proposed as feature requests and then implemented by a contributor. There's already dynamic permission control in Android M, but the UX exposed for controlling it is very simple/limited.

**Comment by BobsUncle** [comment]
So can I use the Orbot Tor Tethering feature ?

**Comment by thestinger** [comment]
No. A similar feature could be implemented for the Android VPN feature if anyone is interested in helping with that.

**Comment by thestinger** [comment]
https://github.com/copperhead/bugtracker/issues/303
