### ISSUE TITLE
List of what's not working

### ISSUE THREAD

**Issue by anantshri** [copperhead/bugtracker#293]
While browsing through the whole website there is no place where i can find a list of stuff tha'ts not working or how build differ between various devices.

Example 5X might have a feature implemented but not 6P, simmilarly 6P might have fingerprint working but 5X might not, It might make sense to take the pain of creating such a sheet.

**Comment by thestinger** [comment]
The issue tracker is the most I'm willing to do. I don't have time for duplicated work or maintaining documentation for things that are in flux. There are device labels on the issue tracker.
