### ISSUE TITLE
heartattack moments during first flash

### ISSUE THREAD

**Issue by anantshri** [copperhead/bugtracker#294]
when a script gives out errors like 

```
archive does not contain 'boot.sig'
archive does not contain 'recovery.sig'
archive does not contain 'system.sig'
archive does not contain 'vendor.sig' 
```

Might be a good idea to either hide those errors or ensure there is a message which confirms they are ignorable.

**Comment by thestinger** [comment]
I don't consider improving non-security-related upstream code to be in-scope. The stock factory images produce the same messages, and that's the experience I want to emulate. People can submit patches to AOSP if they want to improve Android in general, and those will be inherited by CopperheadOS.

**Comment by anantshri** [comment]
I would beg to differ on this. If my understanding of flashing scripts is right the messages are correct we are missing files. however that  doesn't makes any difference for us. and hence it might be a good idea at our end to hide the error messages as its an unnecessary annoyance.

**Comment by thestinger** [comment]
There's nothing missing. It isn't our code, and the output doesn't differ from the stock factory images. You're also probably using a copy of `fastboot` from Google, so there's nothing I can do about the output it produces even if I considered it in-scope.
