### ISSUE TITLE
Nexus 5X: Bug report: camera inverted for Focal and open document scanner

### ISSUE THREAD

**Issue by anantshri** [copperhead/bugtracker#295]
Not sure if you would be interested in solving this but default camera doesn't have HDR mode o looked at alternatives open camera seems to work fine but Focal is inverting the camera simmilarly open note scanner is also inverting the camera

Focal : https://f-droid.org/repository/browse/?fdfilter=foca&fdid=fr.xplod.focal

Open Note Scanner: https://f-droid.org/repository/browse/?fdfilter=open+note&fdid=com.todobom.opennotescanner

not exactly a security issue but might affect camera apps including barcode scanner etc.

**Comment by thestinger** [comment]
This isn't a CopperheadOS issue. Lack of HDR support in the AOSP camera app is a known limitation, and bugs in other apps or AOSP aren't something we'll address.

http://www.theverge.com/2015/11/9/9696774/google-nexus-5x-upside-down-camera

**Comment by anantshri** [comment]
Thanks for the comment. I will most probably be opening some more issues as i explore copperhead os on nexus 5x.
