### ISSUE TITLE
mail app

### ISSUE THREAD

**Issue by subproc** [copperhead/bugtracker#297]
and about changing the default mail app whit k9 with openkeychain? to archive a more secure and more featured mail app...

**Comment by Rudd-O** [comment]
K9 would be great.  APG or openkeychain also would be great.  People are already installing K9 anyway.

**Comment by kckrinke** [comment]
I'm sorry but I don't like K9 and in fact prefer the stock one to K9's interface.

I would much rather have openkeychain integrated into the stock mail app along with a few UX changes. But that's just me.

**Comment by thestinger** [comment]
Not going to be making any substantial changes to obsolete AOSP apps, but I don't consider k9 sane enough to bundle it. At most, the Email app is going to end up removed along with Calendar and other obsolete, unmaintained apps.

**Comment by thestinger** [comment]
I don't want to make any change here right now. I don't think k9 is robust enough.

**Comment by Rudd-O** [comment]
What, there will be no calendar at all?

What about K-9 is insane?
