### ISSUE TITLE
Hotspot broken on MOB30J.2016.05.28.01.02.27

### ISSUE THREAD

**Issue by jtgans** [copperhead/bugtracker#301]
This is on a Nexus 5. Seems the routing tables are screwed up. Doing a ping on device to 8.8.8.8 works fine. Connecting devices get IP addresses, but DNS does not function and pinging 8.8.8.8 from them fails at the assigned gateway (the phone). Pinging the gateway works.

**Comment by thestinger** [comment]
Did it work on a previous release?

**Comment by jtgans** [comment]
No. I havent had this work since I installed it about 6 months ago.

**Comment by thestinger** [comment]
In all likelihood, this is an upstream problem. There are many similar reports:

https://code.google.com/p/android/issues/detail?id=82545

**Comment by jtgans** [comment]
No, i dont think so. That bug report is about DNS not functioning. I cant ping publicly routable internet addresses at all from the tethered device. IOW, the routing of packets is broken.

**Comment by thestinger** [comment]
I can't think of something that would break it for only some people on the Nexus 5, while it has never been a problem for anyone on the 5X/6P or many people on the 5. I doubt it's a CopperheadOS change since the changes that are there would not do this.
