### ISSUE TITLE
feature : auto erase after failed login attempts

### ISSUE THREAD

**Issue by q6r** [copperhead/bugtracker#302]
Would be nice to have a feature that defines a number of failed attempts before erasing the data on the phone. Some users defines a good encryption passphrase at boot and an easy bruteforceable pin number for normal usage. Having this feature will not make bruteforcing possible and is very useful. There are existing apps but something built in would be much better that'll work for before normal usage and at boot decrypting.

**Comment by thestinger** [comment]
It currently forces a reboot after 5 failed attempts when a separate encryption password is set. I don't think wiping is a good way to do it, since it can *easily* be done by accident.
