### ISSUE TITLE
Time resets on reboot

### ISSUE THREAD

**Issue by agardener** [copperhead/bugtracker#304]
I do not have GSM networks available to myself.   This means every time I reboot the device my time resets to an unusable date/time.  This causes most applications that require ssl/tls to fail.  Can you create some sort of stable time source?  I see you take some ideas from openbsd... If possible Id like to suggest using opennptd.  https://github.com/openntpd-portable/openntpd-portable

It allows for setting https based time constraints which may provide extra security against udp time drift attacks.

If this is out of the scope of the project please let me know, I need to find an OS with stable time.  

Cheers!

**Comment by thestinger** [comment]
Android already supports NTP as a fallback.

**Comment by thestinger** [comment]
Which device are you using?

**Comment by agardener** [comment]
Nexus 5.   My device does not appear to be making ntp calls, on reboot, or even after leaving the device online all day.  Is there a ntp config exposed in anyway?

**Comment by thestinger** [comment]
There's no NTP configuration, as it's supposed to work out-of-the-box.

However, the time is also supposed to be preserved between reboots... which happens to be broken on the Nexus 5 for some reason. The Nexus 5 is considered deprecated so it won't be getting attention for device-specific bugs.

Identifying why NTP isn't correcting the time makes sense but it might simply be on a long delay.

**Comment by thestinger** [comment]
The default polling interval appears to be once every 24 hours.

**Comment by agardener** [comment]
Ive left the device on for an entire day and it does not correct the time.   Unfortunate that I can not use the OS with out being subscribed to some service.  I guess I should just throw this thing in the garbage.  Thanks for your help.

**Comment by agardener** [comment]
24hrs seems kinda weak no?

**Comment by thestinger** [comment]
It's only supposed to be correcting clock drift. The Nexus 5 RTC not working is a separate issue from NTP, and might have to do with something like the driver package provided by Google being incomplete. It doesn't occur on the Nexus 9, 5X or 6P. Someone is welcome to work on it and we'll take patches for it but we no longer consider issues specific to the Nexus 5 to be in-scope beyond that.

**Comment by agardener** [comment]
okay

**Comment by agardener** [comment]
thanks!  in the bin it goes.  android, my failed experiment.
