### ISSUE TITLE
eliminate usage __TIME__ and __DATE__ to work towards reproducible builds

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#309]
The -Wdate-time warning is now enabled by default.

**Comment by eighthave** [comment]
Isn't this mostly covered upstream now?  Are there any Copperhead-specifc usages of `__TIME__` and `__DATE__`.

**Comment by thestinger** [comment]
There aren't CopperheadOS uses of it but there are plenty of upstream ones.

**Comment by thestinger** [comment]
Reproducible builds are not going to be considered in-scope for CopperheadOS in the near future.
