### ISSUE TITLE
OS Crash after fingerprint unlock following call hangout

### ISSUE THREAD

**Issue by acabrol** [copperhead/bugtracker#310]
Just after a call hangout i used fingerprint to unlock my Nexus 6P.
The phone display immediately the copperhead loading logo.
I had to restart the phone with hard switch off.

**Comment by thestinger** [comment]
Needs logs from `adb logcat` to approach this, along with knowing whether you changed the advanced security settings in Settings -> Security.

**Comment by acabrol** [comment]
I was not able to reproduce this bug. So i'm not sure this was due to the sequence i provided above.

**Comment by thestinger** [comment]
Just try to get logs if you do run into it again. In all likelihood, it's another upstream memory corruption bug but it's not one that we know about yet.

**Comment by acabrol** [comment]
I'll try to get logs next time i will get unexpected reboot or crash.
By the way i'll try to update to june angler ota it could help.
