### ISSUE TITLE
use the Copperhead wallpaper

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#315]

**Comment by bnvk** [comment]
Really good suggestion. It's silly, but tiny things like this will have a nice UX impact on first use!

**Comment by darknetj** [comment]
@bnvk copperhead wallpaper has been made by @n8fr8 already available here:
https://github.com/n8fr8/copperwall

We need proper dimension sizing for devices.

**Comment by thestinger** [comment]
I meant the wallpaper made by f3ndot.

**Comment by dark159123** [comment]
Can someone link to the wallpaper by @f3ndot?

**Comment by thestinger** [comment]
Need a script to generate a white logo on black background wallpaper from the logo SVG in https://github.com/copperhead/branding for different resolutions.
