### ISSUE TITLE
riseup.pem

### ISSUE THREAD

**Issue by subproc** [copperhead/bugtracker#321]
could you add tha riseup certificate into the rom? 'cause in marshmallow we can't import .pem but only psck because of       a bug/limitation and would be usefull for the riseup vpn

**Comment by thestinger** [comment]
I don't understand why this would need to be added, or what exactly you mean by added. If what you're running into is an upstream limitation, then it's probably out-of-scope for CopperheadOS. There's no OpenVPN support in the base system.
