### ISSUE TITLE
Project Fi Support?

### ISSUE THREAD

**Issue by indolering** [copperhead/bugtracker#328]
I'm on project Fi but I would like to switch over my OS.  However, Project Fi does some interesting things with skipping between carrier networks and WiFi.  Any idea if it would work with Copperhead?

Sorry if this is the wrong place for support requests, I couldn't find a user mailing list.

**Comment by thestinger** [comment]
At the very least, using one of the carriers should work. There might be issues with activation right now, but if it's already enrolled then there's a good chance it will work.

On the other hand I would not expect all of the features to work, at least right now.

**Comment by thestinger** [comment]
And this isn't something that we can test, since we're in Canada and we don't have the resources to devote to it. It is something that other people could work on, and we would be interested in supporting this to the extent possible without Play Services.

**Comment by thestinger** [comment]
#329 is probably relevant. I'll try fixing that today.

**Comment by indolering** [comment]
Did some Googling and it sounds like the SIM card handles the network switching and there are reports of it working on CM.  There might be a dependency on the Project Fi app, but it might be limited to WiFi calling.  I guess it couldn't hurt to try.

**Comment by thestinger** [comment]
It's likely that little of it works right now, especially Sprint support, but for there to be progress people will need to step up and contribute.
