### ISSUE TITLE
Carrier name replaced with "Roaming Indicator Off"

### ISSUE THREAD

**Issue by justin-sleep** [copperhead/bugtracker#332]
The carrier name on both the lockscreen and quick settings menu has been replaced with what seems to be a verbal indicator of the roaming status. My carrier is U.S. Cellular and I have an angler, if it's relevant.

![screenshot_20160706-133130](https://cloud.githubusercontent.com/assets/14955039/16630509/57ca07d0-4380-11e6-930f-39c3b53b25be.png)

**Comment by thestinger** [comment]
It's very unlikely that something like this would be caused by CopperheadOS.

By replaced, do you mean it has been this way since you installed CopperheadOS, or did it start happening after an upgrade, reboot, etc.?

**Comment by justin-sleep** [comment]
It has been this way since I installed CopperheadOS. When I took the phone out of the box and got it activated, and it read "U.S. Cellular". After flashing CopperheadOS, it read "Roaming Indicator Off".

I agree that it doesn't seem like it would be caused by CopperheadOS, but I'm not sure what else would have caused it.

**Comment by thestinger** [comment]
I mean it's probably something wrong with AOSP compared to stock.

**Comment by justin-sleep** [comment]
For what it's worth, I'm now noticing this out of the box. So yes, I agree, it's an upstream issue.

**Comment by thestinger** [comment]
It's possible that it's even the carrier at fault. I'm not sure how this works.
