### ISSUE TITLE
Recovery mode shows "No command" dead android

### ISSUE THREAD

**Issue by Rudd-O** [copperhead/bugtracker#335]
I can't enter recovery and then get ADB to apply the sideload update.

It always says "No command".

**Comment by Rudd-O** [comment]
Wait.  I got the secret code to get the menu.  Thanks.

**Comment by Rudd-O** [comment]
This should be documented.  In the "no command screen", Nexus 5X requires power + Vol Up to show the menu that allows for sideload.

**Comment by Rudd-O** [comment]
Also note that sudo adb kill-server and adb sideload are needed otherwise "insufficient permissions for device" (a host OS problem) appears.

**Comment by thestinger** [comment]
> This should be documented. In the "no command screen", Nexus 5X requires power + Vol Up to show the menu that allows for sideload.

It's mentioned in https://copperhead.co/android/docs/install. It's how it works on user builds, as opposed to userdebug builds with the menu shown by default. I think userdebug builds might also show the log output during upgrades, the same combination is used to show that on user builds.

> Also note that sudo adb kill-server and adb sideload are needed otherwise "insufficient permissions for device" (a host OS problem) appears.

Only if the necessary udev rules aren't set up to use it without privileges. For example, Arch has the android-udev package for those. I can't maintain instructions for every OS though.

**Comment by Rudd-O** [comment]
Well, a note about the "insufficient permissions" message in the docs, explaining to kill ADB and do it as root instead, would probably suffice.  It's a one-liner and it will help the process be more streamlined for people doing this work, and popularize Copperhead more.
