### ISSUE TITLE
questions about the ROM

### ISSUE THREAD

**Issue by lijefmma** [copperhead/bugtracker#337]
First of all, I apologize if this is the wrong place, but I don't know where else to ask these questions that I have about CopperheadOS.

I'm currently using CyanogenMod on my Nexus 6P but thinking of switching to Copperhead OS because of more security / privacy. Before I do that, I'd like to clarify some things.

- Are there any known compatibility issues with Copperhead? More specifically, will the following work:
 - MicroG
 - Xposed
 - Orbot
 - Firewall like AFWall+ / OrWall
 - OpenVPN for Android

- Will I be able to sideload apks from the Play Store or install apps from F-Droid?

- Will the fingerprint sensor work (Nexus 6P)?

- Since I dislike Google and their privacy-invasive business approach, I would appreciate a ROM that sends as little information as possible to Google. What's Copperhead's stance on this / privacy in general?

Any other important things to consider when switching from CyanogenMod?

**Comment by darknetj** [comment]
As per our[ guidelines ](https://github.com/copperhead/bugtracker#reporting-issues)please keep each issue to one report.
