### ISSUE TITLE
prevent IP leaks in WebView

### ISSUE THREAD

**Issue by lmawkefj** [copperhead/bugtracker#338]
Android WebView contains the WebRTC standard which will leak the real IP through STUN requests, when using a VPN or Tor. Are there any plans to disable this?

**Comment by thestinger** [comment]
This is something that applications need to deal with. I'm not sure what the OS could do about it.

**Comment by thestinger** [comment]
It's also a clear example of why proper transparent proxying is important, rather than applications trying to do it internally.
