### ISSUE TITLE
Nexus 6P no data connection T-Mobile

### ISSUE THREAD

**Issue by CopperAnglerIssueReport** [copperhead/bugtracker#340]
Upon a fresh installation of CopperheadOS, I cannot seem to get a stable network connection. Phone calls and texts work fine. It appears that the data connection may occasionally work, as I received an MMS message approximately 6 hours after it was sent. I have never successfully visited a webpage.

I installed using the adb/fastboot SDK download as suggested.
ADB version 1.0.36 (Revision fd9e4d07b0f5-android)
Same revision for fastboot

CopperheadOS version MTC19Z.2016.07.07.02.16.02
gpg --verify returned "Good signature from "Daniel Micay <danielmicay@gmail.com>""

I tried flashing back to stock MTC19X (The latest on Google's website) and had an internet connection again, then flashed back to CopperheadOS.

I've tried then APN settings on https://support.t-mobile.com/docs/DOC-2090, as well as just copying them from a friend's phone.

Attached are the logcat logs from both the fresh install boot, and the boot after changing APN settings.
I'm unsure, but I question if the following is the relevant error:

07-13 20:48:42.235   526   526 I libmdmdetect: ESOC framework not supported
07-13 20:48:42.236   526   526 I libmdmdetect: Found internal modem: modem

[logcat-fresh.txt](https://github.com/copperhead/bugtracker/files/362886/logcat-fresh.txt)
[logcat-apn-switch.txt](https://github.com/copperhead/bugtracker/files/362885/logcat-apn-switch.txt)

**Comment by thestinger** [comment]
In all likelihood it's a configuration issue. CopperheadOS doesn't make changes to this stuff, so it's the same as AOSP. AOSP differs from stock in that the built-in APN settings are often wrong, so it needs to be freshly added.

**Comment by CopperAnglerIssueReport** [comment]
I'll try going back to stock and getting any settings I might need from there.

Is there anything I should grab other than the APN settings?

**Comment by thestinger** [comment]
I don't know. Nothing comes to mind beyond the common AOSP APN issues, which isn't in scope for CopperheadOS right now.

**Comment by CopperAnglerIssueReport** [comment]
Yeah, I saw that in other bug reports. That was where I got the idea to try changing the APN settings originally.

Looking between stock and CopperheadOS, they appear to be the same though. However, in Copperhead the cellular network state is stuck on "Connecting".

The reason I questioned the libmdm output is because that doesn't show up in stock, and seemed tangentially related.

If you think of anything else I can try, please let me know.

[Screenshots.tar.gz](https://github.com/copperhead/bugtracker/files/362919/Screenshots.tar.gz)

**Comment by biotinker** [comment]
I have this same issue.

However, I cannot seem to find the options to edit the APNs- it's not under Networks/More/Cellular Networks, where I would expect it, and doesn't seem to be elsewhere.

I'm not on T-Mobile- I'm on Sprint, and according to my logcat, SprintDM keeps crashing, which is the app that updates the PRL and device config. I've not gotten Copperhead to successfully update the PRL or device config yet either, but that may be the same issue with the APNs.

**Comment by cwmke** [comment]
This might help.  It's T-Mobile's instructions for reseting the APN.  Towards the bottom there's a section titled 'Manually enter APN/MMSC settings' which is probably what you need to dig into.

https://support.t-mobile.com/docs/DOC-1979

**Comment by biotinker** [comment]
It looks like DMservice, the apk that registers my device on the Sprint network, is crashing. Here's the logcat:
[DMserviceCrash.txt](https://github.com/copperhead/bugtracker/files/366234/DMserviceCrash.txt)

**Comment by biotinker** [comment]
Ah, I just saw that Issue 329 is exactly this. I'll go move there.

**Comment by cwmke** [comment]
I currently have the same issue with Ting's network which is a company that uses T-Mobile's network.  It has different APNs but the same issue.

**Comment by CopperAnglerIssueReport** [comment]
@cwmke Yeah, that's where I went to find the APN settings mentioned in the first post. On that page, it links to the DOC-2090 I referenced.

Since my APN settings appear to be identical to stock, my next intention was to try to build pure AOSP over the weekend and see if I get a data connection there.

**Comment by rberg2** [comment]
Hello I ran into this on a Nexus 5x back on June 26/27 also with T-mobile with the correct apn setting. I have a logcat and radio log from that date and a few things stood out to me.

06-26 17:56:56.105   509   598 E QC-QMI  : qmi_client [509]: unable to bind to client socket, rc = -1 errno[13:Permission denied]

06-27 09:13:39.553  3192  3192 D DefaultPhoneNotifier: nofityServiceState: mRegistry=com.android.internal.telephony.ITelephonyRegistry$Stub$Proxy@5a1fe6e ss=0 1 voice home data home T-Mobile T-Mobile 310260 T-Mobile T-Mobile 310260  LTE Unknown CSS not supported -1 -1 RoamInd=-1 DefRoamInd=-1 EmergOnly=false IsDataRoamingFromRegistration=false sender=Handler (com.android.internal.telephony.gsm.GSMPhone) {1721204} phondId=0 subId=-2

I am not sure if those are related or not though. Here are the full logs.
[logcat.txt](https://github.com/copperhead/bugtracker/files/367452/logcat.txt)
[radio-log.txt](https://github.com/copperhead/bugtracker/files/367453/radio-log.txt)

**Comment by thestinger** [comment]
I don't see anything out of the ordinary in those logs. Someone with access to T-Mobile with this problem will need to debug it. I don't have access to it.

**Comment by zmcNTP4fM9Kg** [comment]
I didn't have data available at first on my 6P with fast.t-mobile.com, so I switched from the default fast.t-mobile.com to epc.t-mobile.com, went to IPv4, and made a few other changes.

Try these settings:

https://apn.gishan.net/settings/1259_12_t-mobile_apn_settings_for_huawei_nexus_6p.php

My T-Mobile LTE seems to work just fine with these changes.

**Comment by thestinger** [comment]
Unlike the Sprint issues, it's not clear to me that there's a problem here beyond APN configuration.

**Comment by thestinger** [comment]
And yeah, it should be configured correctly by default but that's up to AOSP.

**Comment by CopperAnglerIssueReport** [comment]
I'm still super unclear why the neither the APN settings from stock, nor the APN settings from T-Mobile's website work, but I am able to access mobile data with the APN settings you linked, @zmcNTP4fM9Kg, thanks!

**Comment by micahflee** [comment]
I ran into the exact same problem when testing out https://github.com/mikeperry-tor/mission-improbable. It took some time to realize that this was actually a Copperhead issue and not an mission-improbable, iptables, or orWall issue.

I used the APN settings that @zmcNTP4fM9Kg linked and that worked for me. However, I think this issue should probably be opened again. As it stands, mobile data just doesn't work on this device with Copperhead on T-Mobile with the default APN settings, but it does work with the stock rom with those same settings. There must be something about Copperhead that is causing it to fail, but a quick fix would probably be to ship with the slightly tweaked settings that do work.

While I was troubleshooting this issue I found this other person with the same problem looking for help:
http://forum.xda-developers.com/nexus-6p/help/nexus-6p-copperhead-os-data-issues-t3454128

**Comment by thestinger** [comment]
Stock is more than simply AOSP with Google Play bundled, so it's not clear that this is an issue with CopperheadOS without further research into it. I don't want to make changes without someone identifying why it's necessary. The T-Mobile issue seems to be caused by IPv6 support, so either Google doesn't enable IPv6 support or there's something wrong with it on CopperheadOS. If there is something wrong with it, it needs to be identified and fixed.

**Comment by thestinger** [comment]
@micahflee Can you try to figure out what exactly needs to be changed from the defaults? I suspect IPv6 needs to be disabled but I am not sure about that.

**Comment by BenBaltz** [comment]
@thestinger The apns-conf.xml from the stock image needs to be used, the AOSP one does not work for some carriers. Almost all ROMs based off of AOSP do this, its not IPv6.

**Comment by thestinger** [comment]
That's likely in the scope for https://github.com/anestisb/android-prepare-vendor. If stock ships a different version of the APN configuration database, it should be replaced with the stock version there. Someone will need to try incorporating it and confirm that it solves this issue. I can't test T-Mobile. I also don't have much faith in the information being reported to us about this stuff because no one is willing to follow up on it. There have been several confirmed reports that disabling IPv6 fixes issues with T-Mobile, but other people don't run into those issues at all.
