### ISSUE TITLE
OTA update error

### ISSUE THREAD

**Issue by q6r** [copperhead/bugtracker#342]
On Nexus 6P OTA update 2016.07.07.02.16.02 says error after reboot to install the update.

**Comment by thestinger** [comment]
It's not possible to attempt to install an update a second time. The process of attempting to reboot to install it the first time mangles it, so if anything goes wrong you need to delete it and download it again. They can be automatically deleted in the future.

In all likelihood, you ran into another issue like the occasional memory corruption that's detected on reboot and causes it to stall. It's too late to know why now though.

**Comment by thestinger** [comment]
https://github.com/copperhead/bugtracker/issues/285
