### ISSUE TITLE
[Enhancement] Introduce 2FA using password/pin and fingerprint for access.

### ISSUE THREAD

**Issue by GarrettGotu** [copperhead/bugtracker#345]
Hey guys,

Looking at how the fingerprint sensor stores and verifies data I'm not even sure this should be possible.

However, if it is, could the developers please look at implementing this feature? Hopefully an additional option under settings>security.

Thanks for all the hardwork you're doing, the only reason I got a Nexus was for CopperHeadOS.

**Comment by thestinger** [comment]
This is already filed as #150. It's not planned in the near future. At the very least any authentication or encryption changes are going to be delayed until after the migration to Android N around October.

**Comment by thestinger** [comment]
See #451.
