### ISSUE TITLE
Please allow disabling of "Enhanced 4G LTE services" as it can cause massive battery drain.

### ISSUE THREAD

**Issue by GarrettGotu** [copperhead/bugtracker#346]
Hi guys,

Can we please look at implementing the toggle for enhanced 4G LTE services, its most likely causing cell standby to consume more battery power as its constantly active.

- 98% battery at 12:29PM, Cell Standby active for 18M 11S, Consumed 56MAH.
- 94% battery at 12:47PM, Cell Standby active for 35M 6S, Consumed 108MAH.
- 93% battery at 12:58PM, Cell Standby active for 42M 39S, Consumed 131MAH.
- 91% battery at 1:05 PM, Cell Standby active for 46M 53S, Consumed 144MAH.

I'd be happy to provide logs and preform testing if required.

Thank you.

**Comment by GarrettGotu** [comment]
Please note, I've figured out what is causing the drain on my device, although I think this enhancement is still valid.

The issue was me using LibreSignal, which uses Websockets rather than GMS, this requires a constant connection and will cause the cell to remain on stand by until the app is killed.

**Comment by thestinger** [comment]
I guess you mean VoLTE, but that might not even be working right now. I don't want to implement a toggle for it, especially since I can't test that. Changes like this are outside the scope of CopperheadOS.

**Comment by thestinger** [comment]
I think it makes more sense to add toggles for the legacy way of doing things, rather than the more modern implementation. None of this would fall under the current scope of the OS though. Not able to test assorted carriers so not going to be making any changes to that stuff.
