### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by positix** [copperhead/bugtracker#348]
Hi. Couple of questions about encryption in CopperheadOS

1) Do you use 256-bit encryption for the master key? The documentation says its optional for OEMs to go higher than 128. https://source.android.com/security/encryption/'

2) Do you disable TRIM? Google enables it since Android 5.0 though its disabled on desktop Linux for security. When its on, TRIM leaks data that was encrypted before when the user deletes it.
http://asalor.blogspot.com/2011/08/trim-dm-crypt-problems.html

3) I saw somewhere that CopperheadOS defends against the TEE keystore extraction. is this true?

**Comment by darknetj** [comment]
@positix please follow our guidelines
https://github.com/copperhead/bugtracker/blob/master/README.md#reporting-issues

send questions to https://copperhead.co/contact

**Comment by positix** [comment]
I'll follow guidelines, but I would really like some feedback for my questions.

I am not fond of contact forms because they are not transparent like forums. No one else with the same concerns gets to know if its been asked before or what your response was.

**Comment by thestinger** [comment]
> No one else with the same concerns gets to know if its been asked before or what your response was.

That's assuming they look for answer, but the answer to those questions is already available. The issue tracker isn't going to be used to provide support though. It's for tracking bugs and enhancements.

**Comment by positix** [comment]
Alright. Saw some answers on your tech overview.

Please address question 2 and 3. You mention TEE, but its not clear if what the latest TrustZone key extraction applies to CopperheadOS, or how much damage it does.

**Comment by positix** [comment]
I checked and you, in fact, do disable TRIM. There is no discard option in fstab.

Thanks CopperheadOS guys for making us safe.

**Comment by thestinger** [comment]
Android does TRIM via fstrim rather than discard.
