### ISSUE TITLE
use a separate kernel configuration for user and userdebug/eng

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#349]

**Comment by thestinger** [comment]
This is now implemented.

**Comment by AdFad666** [comment]
Perhaps a better way is to use CM's [kernel.mk](https://github.com/CyanogenMod/android_build/blob/cm-13.0/core/tasks/kernel.mk) in `/build` and make use of the `TARGET_KERNEL_ADDITIONAL_CONFIG` option which appends to the main defconfig.

create `$(KERNEL_SRC)/arch/arm64/configs/copperheados_debug_config` with the extras you want, and add this to device repo:

```
# Enable debug on debug builds
ifneq ($(TARGET_BUILD_VARIANT),user)
TARGET_KERNEL_ADDITIONAL_CONFIG := copperheados_debug_config
endif
```

This also gives you inline kernel build without the need to modify the kernel as it is automatically picked up during build.

(or just copy the relevant parts to each kernel's `AndroidKernel.mk`.)
