### ISSUE TITLE
No link to bugtracker from https://github.com/copperheados

### ISSUE THREAD

**Issue by condor0765** [copperhead/bugtracker#351]
There is no link directly from github source code repo to the bugtracker. Only a web search gave me this: Perhaps you could add a link to [bugtracker](https://github.com/copperhead/bugtracker)  in 
https://copperhead.co/android/docs/ It seems counter-intitutve to search for bug tracker in the copperhead instead of copperheados.

**Comment by thestinger** [comment]
The CopperheadOS organization is a namespace for repositories that are actually part of the OS, which doesn't include the update server or a meta-repository like this one. This bug tracker includes issues on the site (like this) and with the update server - it's not just for CopperheadOS.

The issue tracker is linked in https://copperhead.co/android/docs/install and https://copperhead.co/android/docs/technical_overview. It could be linked elsewhere but it's only a search away regardless.

**Comment by condor0765** [comment]
Thanks. My suggestion would be to make it more prominent. May be in TOC.

**Comment by thestinger** [comment]
I don't plan to make changes to this, we're primarily interested in supporting customers and the bug tracker is already proving to be a major hassle with little gain as is.
