### ISSUE TITLE
Encryption locks users out of OTAs

### ISSUE THREAD

**Issue by tusing** [copperhead/bugtracker#353]
The latest OTA can't be installed on an encrypted device (encryption password must be removed first), as the recovery installed by the OTA does not have any decryption features.

**Comment by thestinger** [comment]
The recovery doesn't require decryption support to install over-the-air updates. The update is decrypted before the OS reboots to recovery. It uses the same implementation (`installPackage`) as stock Android. There's nothing CopperheadOS-specific about the update installation process, only the downloader. You might have run into a problem, but this isn't it and your workaround probably wasn't what fixed the issue for you.

**Comment by thestinger** [comment]
There's a known issue (https://github.com/copperhead/bugtracker/issues/285) causing Nexus 5X reboots to stall. This tends to cause problems for users installing updates, since it's not possible to attempt to reboot and install the update if there's a failure. It needs to be downloaded again. The updater could track state to work around this, but it currently doesn't do that (related: #341).

**Comment by thestinger** [comment]
Removing the encryption password also doesn't decrypt the device. The data partition in stock Android and CopperheadOS is *always* encrypted with a random key due to `forceencrypt` being used as a mount option. Setting a password only adds a layer of protection to the actual encryption key.

**Comment by tusing** [comment]
Thanks, that cleared up a few things.

Is there anywhere I can manually download the latest update .zip, then? On the Nexus 5 (not 5X), I get the "Error" screen (not the stall in #285).

**Comment by thestinger** [comment]
Have you tried deleting and downloading the update again? It won't install if it's corrupted, and if any other kind of problem occurs once then the update has to be downloaded again since it will be mangled (could be improved, but it isn't on the roadmap).

**Comment by thestinger** [comment]
The updates can also be downloaded from https://copperhead.co/android/downloads and sideloaded, but that shouldn't be necessary.

**Comment by tusing** [comment]
I'll try downloading it again, thanks.

On another note - the "long press to delete" is unintuitive; perhaps that should be moved to a separate icon?

**Comment by thestinger** [comment]
Deletion of updates will just be automated. It doesn't make sense to improve the UI because there's no use in keeping around updates as downgrading to them isn't possible.

**Comment by tusing** [comment]
Looks like re-downloading fixed the issue. Thanks, especially for the super-fast response.
