### ISSUE TITLE
selfrando

### ISSUE THREAD

**Issue by subproc** [copperhead/bugtracker#355]
what about using the selfrando project in copperhead os?

**Comment by thestinger** [comment]
It doesn't support Android right now, and I'm not interested in porting it. If someone else ported it, then it could be considered, but right now it's not available as an option.

**Comment by thestinger** [comment]
ARM64 supports execute-only memory which could make this significantly more useful.

**Comment by thestinger** [comment]
The license isn't compatible.

**Comment by thestinger** [comment]
Ah I think the library part is actually BSD, NVM.

**Comment by thestinger** [comment]
Not going to consider this without a working upstream port.

**Comment by thestinger** [comment]
This conflicts with preventing dynamic code generation. I don't see a way to work around it without designing new memory protection mitigations for the kernel designed to allow self-modifying code for the early loading phase.
