### ISSUE TITLE
Call volume is significantly lower in 07/24 build (set to max volume).

### ISSUE THREAD

**Issue by sun1235** [copperhead/bugtracker#357]

**Comment by polyzen** [comment]
The name of the device and a look at logcat (as per the [issue reporting guidelines](https://github.com/copperhead/bugtracker#reporting-issues)) could be useful.

**Comment by thestinger** [comment]
This isn't determined by CopperheadOS, but rather the Android Open Source Project. There have also been no changes relevant to this in CopperheadOS.
