### ISSUE TITLE
msm_irqbalance needs /proc/stat

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#358]

**Comment by thestinger** [comment]
This has been fixed and will be in the next release (i.e. the first one after the August security update release).

**Comment by AdFad666** [comment]
msm_irq is a proprietary blob but do you have any info on what the fix is? Does it need a code change or is it simply better sepolicy?

**Comment by thestinger** [comment]
It's already fixed:

https://github.com/CopperheadOS/device_lge_bullhead/commit/2d00ea2ac6a45dfc49da4f68a85d790c7ddf90a6

It's not an upstream issue.
