### ISSUE TITLE
Replace the awful Music app with something more modern

### ISSUE THREAD

**Issue by AdFad666** [copperhead/bugtracker#365]
AOSP has long neglected its `Music` app, but instead of simply removing it we can replace it with a modernized app from our friends at CodeAurora. The `SnapdragonMusic` app is a drop in replacement for the AOSP music app and is actually pretty nice.

I've already made the necessary minor changes to make this work on CopperheadOS (and AOSP in general) and it can be found [here](https://github.com/Contortrix/packages-apps-SnapdragonMusic).

It would be nice to have an actually useful Music app, and also get rid of that last ugly Gingerbread era icon from the app drawer.

<img src="https://cloud.githubusercontent.com/assets/1012095/17589754/bddead2e-5fd6-11e6-9661-4b6bcd1b531f.png" width="250"> <img src="https://cloud.githubusercontent.com/assets/1012095/17589755/bde8cde0-5fd6-11e6-9b0d-784447c01acf.png" width="250">

[Original Source](https://source.codeaurora.org/quic/la/platform/packages/apps/SnapdragonMusic/)

**Comment by rosswell98** [comment]
I don't think that's useful, the best way I think, is to desactivate the default Music app and install the player of our choice...
It may be problematic to add the support of a modern app and maybe negociate with probable security problems if they exist ?

**Comment by AdFad666** [comment]
Pros and Cons. Installing an external app is inherently insecure, you have to blind trust it. This is at least open source, can be owned by Copperhead and can be fixed.

But that's also extra work and we're talking about 'only' an MP3 player. Personally I don't listen to music that much on a phone, I just wanted to get rid of the damn awful Gingerbread train wreck.

There is also such a thing as taking the 'possible security problems' idea too far. perhaps Copperhead OSshould only have 2 icons in the app drawer, Dialer and Settings?

**Comment by thestinger** [comment]
It's too much work to bundle another app and then deal with bug reports for it. The only thing that might happen is the removal of the current Music app without a replacement, if it's not a requirement to pass the CTS.
