### ISSUE TITLE
i can't activate unknow sources on guest account, Nexus 5

### ISSUE THREAD

**Issue by lagosazules** [copperhead/bugtracker#366]
On guest account  I can't activate unknow sources and install applications downloaded from Fdroid, off course I got unknown sources activated on the owner account , a bug or I'm missing something?

**Comment by thestinger** [comment]
You don't need to enable unknown sources to install packages from F-Droid in CopperheadOS. It counts as a known source since it's integrated into the OS.

**Comment by thestinger** [comment]
F-Droid doesn't currently work in non-owner user accounts. It's a known issue with F-Droid itself, not CopperheadOS.

**Comment by thestinger** [comment]
F-Droid works on alternate users now, FWIW. It was an upstream bug in AOSP.
