### ISSUE TITLE
Build without 3rd Party Apps for Nexus 5

### ISSUE THREAD

**Issue by vanitasvitae** [copperhead/bugtracker#380]
Hi!
I saw that recently updates were released for all devices except the Nexus 5. If you dropped support for it, it would be nice, if you release one last image for it without build in 3rd party apps like FDroid, so that we still can use that image and are able to easily keep FDroid updated on our own.

**Comment by thestinger** [comment]
There will still be security updates for the Nexus 5 as long as Google releases them, but once that's over I won't be releasing any more updates. There isn't going to be another feature release for the Nexus 5 of any kind.
