### ISSUE TITLE
Unable to receive incoming calls. Verizon Wireless - N5X

### ISSUE THREAD

**Issue by 0xFF600** [copperhead/bugtracker#381]
Running the 2016-08-23 build for Nexus 5X, (MTC20F.2016.08.23.15.51.31) (bullhead-factory-2016.08.23.15.51.31.tar.xz), unable to receive incoming calls. Placing outgoing calls works without issue. SMS send and receive also both work as expected. VZW APN settings were successfully auto-configured after first boot.

**Comment by thestinger** [comment]
APN settings being set up automatically doesn't mean that they're set up properly.

**Comment by 0xFF600** [comment]
Just reflashed and verified they are set as needed:

Latest Verizon settings (Galaxy S7 Edge):

Name: Verizon Internet
APN: VZWINTERNET
MCC: 311
MNC: 480
APN type: default,dun,supl
APN protocol: IPv4/IPv6
APN roaming protocol: IPv4/IPv6
Mobile virtual network operator type: None

All other values “Not set”.


These settings are verified working on other AOSP based ROMS:
https://github.com/omnirom/
https://github.com/omnirom/?utf8=%E2%9C%93&query=bullhead

**Comment by thestinger** [comment]
Try removing it and adding it back again with the proper settings regardless.

**Comment by 0xFF600** [comment]
How do I add it back again? There is no option to "Create a new APN" after removing the existing, other than "Reset to default".

**Comment by 0xFF600** [comment]
This issue is also present in the 2016-08-16 build.

**Comment by thestinger** [comment]
It would be helpful if you could provide the `adb logcat` output.

**Comment by 0xFF600** [comment]
I won't have a second phone to place test calls with until this weekend. Will test, try to pull some logcats and will report back then.

**Comment by thestinger** [comment]
This would need to be revisited with Nougat. There are major changes in the issues that are present in AOSP.
