### ISSUE TITLE
implement automatic OS update downloads

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#403]
This should be a straightforward feature addition in packages/apps/Updater. It should have 3 modes: off, WiFi-only, always. The user should be notified when an update download is complete and ready for installation (whether or not automatic downloads are enabled).

**Comment by thestinger** [comment]
Not planning on enhancing the old update app further. CopperheadOS lacks the resources to maintain it, so there's only going to be the legacy update in the current state and a new simplified updater for A/B devices only without a user interface beyond a notification when updates are complete to reboot.

**Comment by daradib** [comment]
If possible, can you add a section about updating to the [usage guide](https://copperhead.co/android/docs/usage_guide)? I can also try writing a paragraph if you're short on time, let me know.

**Comment by thestinger** [comment]
Not planning to document the old update client. Going to be focusing on the future rather than the legacy mess that's being left behind.

**Comment by thestinger** [comment]
The new update client will not have any user interface, so there won't be much to document beyond stating that it just works (unlike the current update client).

**Comment by daradib** [comment]
OK, thanks!
