### ISSUE TITLE
disable location tagging by default

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#412]

**Comment by anestisb** [comment]
I'm guessing you're referring to default camera2 app location tagging right?

Do you want to skip the entire first run dialog and default in the background to false (user has to open camera app, swipe to go to setting and enable manually if desired), or choose disable value by default on the first run dialog?

Default first run dialog value is [here](https://github.com/CopperheadOS/platform_packages_apps_Camera2/blob/nougat-release/src/com/android/camera/app/FirstRunDialog.java#L52)
```
    /** The default preference of whether enabling location recording. */
    private static final boolean DEFAULT_LOCATION_RECORDING_ENABLED = true;
```

Should run first dialog global setting check is [here](https://github.com/CopperheadOS/platform_packages_apps_Camera2/blob/nougat-release/src/com/android/camera/app/FirstRunDialog.java#L139):
```
    private boolean shouldShowLocationDialog() {
        return !mSettingsManager.isSet(SettingsManager.SCOPE_GLOBAL, Keys.KEY_RECORD_LOCATION);
    }
```

**Comment by thestinger** [comment]
We used to change the default value for the preference in Marshmallow, but I'm likely going to switch to just toggling it off by default in the first run dialog. These nougat-port tagged issues are mostly cases where the old commits didn't apply cleanly and some work is required but in this case I just want to review the past decision.

**Comment by thestinger** [comment]
This is implemented again. The permission request should probably be moved, but it's good enough for the time being.
