### ISSUE TITLE
switch to using a monochrome apk instead of separate chrome/webview apks

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#415]
It's not clear if the necessary sources are public yet, but this should happen once it becomes possible.

**Comment by rsesek** [comment]
In order to support users disabling (Mono)Chrome, Android system still ships a SystemWebViewGoogle. That way there's a fallback package to keep WebView working if the Monochrome package is explicitly disabled. If you're not concerned about users disabling Chrome, then you can just use Monochrome.

**Comment by thestinger** [comment]
@rsesek The part that I'm unsure about is what the target is to build monochrome. There are chrome_public_apk and system_webview_apk but I don't see one to actually make a Chrome build include the monochrome libraries, or an option to make it do that.

**Comment by rsesek** [comment]
The monochrome APK target isn't yet upstreamed. WebView team is working on unforking it, though (should be part of the crbug mentioned in #420).

**Comment by rsesek** [comment]
There's now a bug dedicated to tracking the public monochrome target: https://bugs.chromium.org/p/chromium/issues/detail?id=650927.

**Comment by thestinger** [comment]
AFAICT, some of the changes required for this landed but now it isn't progressing. It's not super important but it does make each of our updates significantly bigger which is a bit annoying.

**Comment by rsesek** [comment]
I don't know much about the Chromium Android build configuration, but if you can post on the bug what issues are still outstanding, that'd probably be helpful to the people who do know.

**Comment by thestinger** [comment]
It turns out that the remaining issues were resolved recently, I just had to deal with porting it to using 64-bit processes:

https://github.com/CopperheadOS/chromium_patches/blob/master/0017-use-64-bit-Monochrome-processes.patch
