### ISSUE TITLE
Enable (even) longer encryption passwords

### ISSUE THREAD

**Issue by securitymanager** [copperhead/bugtracker#416]
Hello everyone!

Could someone explain to me why the website says there is a limit of 32 characters for the encryption password? Please correct me if I'm wrong, but many other custom ROMs in combination with an app like "Cryptfs Password" would enable the user to choose encryption passwords that are much longer than 32 characters. Why is there such limit of characters for a password in a ROM that aims to provide the best security for its users?

Thank you very much!

**Comment by thestinger** [comment]
The issue tracker isn't going to be used for providing support / answering questions. There are no changes to this area in the current Nougat-based CopperheadOS anyway, and there's support for a new encryption format where things work differently.

**Comment by securitymanager** [comment]
I guess I accidentally misused the tracker. I also found a subreddit and now I think I should have opened a topic there instead of opening one in here. Still: It would have been nice to read one or two short sentences or receive a link which directly address the 
> new encryption format where things work differently.
I'm sure some users are searching the internet for the same question and thus the creation of new topics with the same question or in the wrong place could be avoided in the future. Thank you very much!
