### ISSUE TITLE
adb backup -all -obb -apk -shared hangs

### ISSUE THREAD

**Issue by Rudd-O** [copperhead/bugtracker#418]
The hang happens right at the moment that the backup progress screen text box changes to say "Shared data".

Without -shared, backup works.

**Comment by thestinger** [comment]
IIRC, this is a known upstream issue. CopperheadOS never applied an unofficial fix for it.

**Comment by thestinger** [comment]
It might be resolved in Nougat which should be released for all 3 supported devices today. We're not going to be doing any more work on Marshmallow.

**Comment by Rudd-O** [comment]
Oh, I should try again, now that I have upgraded my system.

**Comment by anestisb** [comment]
It's still an issue in upstream Android with no fix yet (and least not in the public-sphere). https://code.google.com/p/android/issues/detail?id=219980

Also for what is worth it I've checked it against "NRD90M.2016.09.05.03.48.51" Nexus 5x Copperhead build and it's still there.

**Comment by thestinger** [comment]
Is it present with an adb build from the CopperheadOS source tree though?

**Comment by Rudd-O** [comment]
I don't at present have a way to test this from source as I lack the resources to build it myself, or test it myself.

**Comment by thestinger** [comment]
Since this isn't caused by a CopperheadOS feature, I don't want to track it here. It doesn't make sense to track every AOSP bug.
