### ISSUE TITLE
WebView for Android Nougat relies on code that is not yet part of upstream Chromium releases

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#420]
CopperheadOS will need to reuse Google WebView builds rather than our own builds for the time being. This is _quite_ annoying since it means we're stuck with their baseline compiler hardening rather than being able to enable some trapping UBSan sanitizers and using our `-fsanitize=local-init` sanitizer to zero all uninitialized local variables. Among other things that were previously possible thanks to building from source...

Can keep checking each stable release to figure out when the new code becomes public. Hopefully, they've already upstreamed enough for us to switch with the next stable release...

**Comment by thestinger** [comment]
Note: standalone Chromium still works fine.

**Comment by thestinger** [comment]
Related: #415.

**Comment by rsesek** [comment]
Chromium's issue for upstreaming this code is here: https://bugs.chromium.org/p/chromium/issues/detail?id=643660

**Comment by thestinger** [comment]
@rsesek Any idea about #415? That seems like it might just be a bit of build integration that's missing now. Most of it seems to be there.

**Comment by thestinger** [comment]
(I'd be really happy if I had to do 2 builds instead of 4 :P)

**Comment by thestinger** [comment]
Have now switched to the Beta channel to build this from source again. The new issue is #489.
