### ISSUE TITLE
Downloading an update fails when 2 are available

### ISSUE THREAD

**Issue by jhfdvjkfdjhbjhviufi** [copperhead/bugtracker#428]
After starting any of the available updates' download, the download is showed by an indeterminate progress bar and after a while a notification appears saying that the download failed without more explanations. Trying again always produces the same result.
Happened on Nexus 5x twice.

**Comment by thestinger** [comment]
Are you sure it's not https://twitter.com/CopperheadOS/status/773547201083629568? The issue was fixed in NRD90S.2016.09.07.12.31.09. If you installed an earlier Nougat update, you need to either install the new Updater.apk and reboot first or alternatively you can sideload the update.

**Comment by thestinger** [comment]
There's no progress bar due to an OpenShift issue. That's expected. If the download is actually failing and you're receiving a notification about it, that sounds like a network issue not a CopperheadOS issue. There are currently no delta updates, so it's a very large download.

**Comment by thestinger** [comment]
Any progress in getting past this?
