### ISSUE TITLE
Problem installing the latest ota update (angler-ota_update-2016.09.14.05.23.28.zip)

### ISSUE THREAD

**Issue by BytesTuner** [copperhead/bugtracker#431]
I have tried to install  'angler-ota_update-2016.09.14.05.23.28.zip' a few times from a wifi connection this morning without success (the download stopped every times with a error notification). Then I have downloaded it manually from the website and tried to sideload it with adb. Unfortunately, it always stuck at "verifying update package" during long period of time (more than a hour) without showing any progress or some kind of result.

Is it be possible that the latest update file is corrupted or has a bad signature? 

Thank you!

*My phone is a 6p

**Comment by BytesTuner** [comment]
oups..just saw this thread: https://github.com/copperhead/bugtracker/issues/428

I'm currently installing updater.apk to see if that will fix my issue...

I will report back...

**Comment by BytesTuner** [comment]
Nope...I still have the issue after applying Updater.apk and reboot my phone.

The download continue to stop after several minutes with a error notification.

**Comment by thestinger** [comment]
> Is it be possible that the latest update file is corrupted or has a bad signature?

No, it's fine, and this is only happening to you. I expect it's a network problem on your end. These are quite large downloads.

**Comment by thestinger** [comment]
The verifying update package step being stuck is a strange symptom that I've never heard of before. It definitely takes a long time, as in a minute or two. It sounds a bit like your `adb` is not transferring the data, perhaps it's too old to work properly.

**Comment by thestinger** [comment]
I don't think either of these is a CopperheadOS bug.

**Comment by BytesTuner** [comment]
You were right about my adb sideload issue. The problem was cause by a older version of adb. I've fixed it by installing the latest version included with the Android SDK. 

However, the only way I'm able to update my phone now is by sideloading the new ones. The regular way of updating over wifi it's not working for me since the last 3 updates. It was working without problem before that. FWIW I don't think it is related to a bad wifi connection on my side because I can browse the Internet and even stream video content over my wifi during a long period of time. I've also a tablet on the same wifi that is working flawlessly. My guess is that this is related with the Copperhead Updater. 

Apart from this issue, I really like my Copperhead OS experience so far and find it much more solid overall than when I was on CyanogenMod. Keep up the good work guys!
You were right about my adb sideload issue. The problem was cause by a older version of adb. I've fixed it by installing the latest version included with the Android SDK. 

However, the only way I'm able to update my phone now is by sideloading the new ones. The regular way of updating over wifi it's not working for me since the last 3 updates. It was working without problem before that. FWIW I don't think it is related to a bad wifi connection on my side because I can browse the Internet and even stream video content over the wifi during a long period of time. I've also a tablet on the same wifi that is working flawlessly. My guess is that this is related with the Copperhead Updater. 

Apart from this issue, I really like my Copperhead OS experience so far and find it much more solid than when I was on Cyanogen Mod. Keep up the good work guys!

**Comment by thestinger** [comment]
Can you obtain logs with `adb logcat` from when it fails? Note that the download itself is done by Android's standard DownloadManager, not the updater app itself. The Updater is a fork of the CyanogenMod updater with only some minor changes to fix some security issues and to make it compatible with CopperheadOS.

**Comment by BytesTuner** [comment]
> Can you obtain logs with adb logcat from when it fails?

Sure, no problem. I will do that if it fails again next update and report back here.

**Comment by BytesTuner** [comment]
Here is the logs when it fails downloading over wifi:

http://dpaste.com/24XFNEX

**Comment by BytesTuner** [comment]
I finally isolate the problem and I can now say for sure that the problem has nothing to do with Copperhead OS. Sorry about that! Thank you
