### ISSUE TITLE
CPU usage overlay isn't displayed when toggled on

### ISSUE THREAD

**Issue by jmndn** [copperhead/bugtracker#435]
Build: NRD90U.2016.9.14.05.23.28
Device: Nexus 6P
Description: When attempting to activate the CPU usage overlay from developer settings, SELinux prevents reading /proc/stat and the overlay fails to display.

[Relevant logs](https://github.com/copperhead/bugtracker/files/475601/logcat.txt)

**Comment by thestinger** [comment]
I don't really consider this a bug, and it's already broken to a lesser extent without those restrictions. Note that the `/proc/stat` restrictions were landed upstream as-is too.

**Comment by thestinger** [comment]
Google removed this feature.
