### ISSUE TITLE
orbot crashing when you shutdown and restart it

### ISSUE THREAD

**Issue by canary5** [copperhead/bugtracker#440]
--------- beginning of main
09-19 07:13:54.345  3869  3869 I ServiceManager: Waiting for service AtCmdFwd...
09-19 07:13:55.346  3869  3869 I ServiceManager: Waiting for service AtCmdFwd...
09-19 07:13:56.348  3869  3869 I ServiceManager: Waiting for service AtCmdFwd...
09-19 07:13:57.349  3869  3869 I ServiceManager: Waiting for service AtCmdFwd...
09-19 07:13:58.351  3869  3869 I ServiceManager: Waiting for service AtCmdFwd...
--------- beginning of system
09-19 07:13:59.072  4322  4986 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.torproject.android/.OrbotMainActivity bnds=[315,2103][597,2411] (has extras)} from uid 10013 on display 0
09-19 07:13:59.351  3869  3869 W Atfwd_Sendcmd: AtCmdFwd service not published, waiting... retryCnt : 4
09-19 07:13:59.503  4322  5288 I WindowManager: Destroying surface Surface(name=com.android.launcher3/com.android.launcher3.Launcher) called by com.android.server.wm.WindowStateAnimator.destroySurface:2014 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:881 com.android.server.wm.WindowState.destroyOrSaveSurface:2073 com.android.server.wm.AppWindowToken.destroySurfaces:363 com.android.server.wm.AppWindowToken.notifyAppStopped:389 com.android.server.wm.WindowManagerService.notifyAppStopped:4456 com.android.server.am.ActivityStack.activityStoppedLocked:1252 com.android.server.am.ActivityManagerService.activityStopped:6873 
09-19 07:14:02.283  7753  7753 I TorService: stopTor
09-19 07:14:07.658  4322  5276 I WifiHAL : Got channel list with 11 channels
09-19 07:14:07.661  4322  5276 I WifiHAL : Got channel list with 9 channels
09-19 07:14:07.664  4322  5276 I WifiHAL : Got channel list with 15 channels
09-19 07:14:07.914  7753  7753 I TorService: onCreate end
09-19 07:14:07.919  7753  8234 D torResources: deleting existing torrc.custom
09-19 07:14:07.974  8243  8243 W sh      : type=1400 audit(0.0:101): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
09-19 07:14:07.987  8243  8243 W sh      : type=1400 audit(0.0:102): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
09-19 07:14:07.987  8243  8243 W sh      : type=1400 audit(0.0:103): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
09-19 07:14:07.987  8243  8243 W sh      : type=1400 audit(0.0:104): avc: denied { read } for name="/" dev="rootfs" ino=1 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:rootfs:s0 tclass=dir permissive=0
09-19 07:14:09.036  7753  8235 D torResources: deleting existing torrc.custom
09-19 07:14:09.048  7753  7775 I art     : Background sticky concurrent mark sweep GC freed 5768(530KB) AllocSpace objects, 7(140KB) LOS objects, 0% free, 50MB/50MB, paused 6.214ms total 19.525ms
09-19 07:14:11.618  5637  5637 I wpa_supplicant: p2p-dev-wlan0: CTRL-EVENT-REGDOM-CHANGE init=BEACON_HINT type=UNKNOWN
09-19 07:14:16.008  5354  5354 D PhoneStatusBar: disable: < expand ICONS* alerts SYSTEM_INFO* back home recent clock search quick_settings >
09-19 07:14:17.875  4322  5570 I ActivityManager: START u0 {cmp=org.torproject.android/.OrbotMainActivity} from uid 10069 on display 0
09-19 07:14:17.875  4322  5570 W ActivityManager: startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { flg=0x800000 cmp=org.torproject.android/.OrbotMainActivity }
09-19 07:14:17.886  4322  5898 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@7cdcea8 attribute=null, token = android.os.BinderProxy@add7d1d
09-19 07:14:18.297  5354  5354 D PhoneStatusBar: disable: < expand icons* alerts system_info* back home recent clock search quick_settings >
09-19 07:14:19.352  3869  3869 I ServiceManager: Waiting for service AtCmdFwd...
09-19 07:14:19.855  7753  7753 I TorService: stopTor
09-19 07:14:20.353  3869  3869 I ServiceManager: Waiting for service AtCmdFwd...
09-19 07:14:21.354  3869  3869 I ServiceManager: Waiting for service AtCmdFwd...
09-19 07:14:22.355  3869  3869 I ServiceManager: Waiting for service AtCmdFwd...
09-19 07:14:22.390  7753  7753 I TorService: onCreate end
09-19 07:14:22.398  7753  8283 D torResources: deleting existing torrc.custom
09-19 07:14:22.462  7753  8284 D torResources: deleting existing torrc.custom
09-19 07:14:23.356  3869  3869 I ServiceManager: Waiting for service AtCmdFwd...
09-19 07:14:24.357  3869  3869 W Atfwd_Sendcmd: AtCmdFwd service not published, waiting... retryCnt : 5
09-19 07:14:27.664  4322  5276 I WifiHAL : Got channel list with 11 channels
09-19 07:14:27.670  4322  5276 I WifiHAL : Got channel list with 9 channels
09-19 07:14:27.677  4322  5276 I WifiHAL : Got channel list with 15 channels
09-19 07:14:30.287  7753  8304 D torResources: deleting existing torrc.custom
09-19 07:14:32.734  5354  5354 D PhoneStatusBar: disable: < expand ICONS* alerts SYSTEM_INFO* back home recent clock search quick_settings >
09-19 07:14:34.084  4322  5570 I ActivityManager: START u0 {cmp=org.torproject.android/.OrbotMainActivity} from uid 10069 on display 0
09-19 07:14:34.084  4322  5570 W ActivityManager: startActivity called from non-Activity context; forcing Intent.FLAG_ACTIVITY_NEW_TASK for: Intent { flg=0x800000 cmp=org.torproject.android/.OrbotMainActivity }
09-19 07:14:34.107  4322  5575 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@bfa03f9 attribute=null, token = android.os.BinderProxy@add7d1d
09-19 07:14:34.491  5354  5354 D PhoneStatusBar: disable: < expand icons* alerts system_info* back home recent clock search quick_settings >
09-19 07:14:37.937  7753  8335 D torResources: deleting existing torrc.custom
09-19 07:14:49.359  3869  3869 I Atfwd_Sendcmd: AtCmdFwd service not ready - Exhausted retry attempts - :6
09-19 07:14:49.359  3869  3869 I Atfwd_Daemon: result : -1 	 ,Init step :2 	 ,qmiErrorCode: 0

**Comment by thestinger** [comment]
I don't see a crash there.

**Comment by thestinger** [comment]
I expect that whatever is going on is an Orbot bug with Nougat, not a CopperheadOS issue. I won't be looking into this without confirmation that it only occurs on CopperheadOS.

**Comment by canary5** [comment]
Its blinking, starting and shuting down. It maybe orbot bug, i dont have any other N system to test

**Comment by vanitasvitae** [comment]
I also appears sometimes on my Nexus 5 with 6.0.1. So I assume its an upstream bug.
When this happens to me, I have to force kill Orbot and restart it.

See eg. https://github.com/n8fr8/orbot/issues/48

**Comment by thestinger** [comment]
Seems to an upstream issue (for something that's not bundled).

**Comment by canary5** [comment]
Latest orbot beta fixed it
