### ISSUE TITLE
Can't add a new certificate

### ISSUE THREAD

**Issue by rosswell98** [copperhead/bugtracker#445]
I can't add a new user certificate, when I select the certificate in the internal memory, he ask my password, the name of the certificate, but ask again my password, but when I validate the password he ask me again and again...
So it's impossible to add a new certificate...

**Comment by rosswell98** [comment]
I installed the update **_NRD90U.2016.09.27.15.19.19_** and now I can use my fingerprint to add a new certificate and he's not asking me for my password, like before!
It's OK, thanks you!

**Comment by thestinger** [comment]
I guess this was a symptom of the keystore issue.
