### ISSUE TITLE
Will not flash on Angler/6P

### ISSUE THREAD

**Issue by PunkUnity** [copperhead/bugtracker#452]
punkunity@GhostShell:~/Downloads/angler-nrd90u$ ./flash-all.sh
target reported max download size of 494927872 bytes
sending 'bootloader' (3530 KB)...
OKAY [  0.115s]
writing 'bootloader'...
OKAY [  0.209s]
finished. total time: 0.324s
rebooting into bootloader...
OKAY [  0.008s]
finished. total time: 0.258s
target reported max download size of 494927872 bytes
sending 'radio' (48664 KB)...
OKAY [  1.160s]
writing 'radio'...
OKAY [  2.168s]
finished. total time: 3.328s
rebooting into bootloader...
OKAY [  0.012s]
finished. total time: 0.263s
target reported max download size of 494927872 bytes
archive does not contain 'boot.sig'
archive does not contain 'recovery.sig'
archive does not contain 'system.sig'
archive does not contain 'vendor.sig'
Creating filesystem with parameters:
    Size: 58688266240
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 8192
    Inode size: 256
    Journal blocks: 32768
    Label: 
    Blocks: 14328190
    Block groups: 438
    Reserved block group size: 1024
Created filesystem with 11/3588096 inodes and 271280/14328190 blocks
Creating filesystem with parameters:
    Size: 104857600
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 6400
    Inode size: 256
    Journal blocks: 1024
    Label: 
    Blocks: 25600
    Block groups: 1
    Reserved block group size: 7
Created filesystem with 11/6400 inodes and 1438/25600 blocks
--------------------------------------------
Bootloader Version...: angler-03.58
Baseband Version.....: angler-03.72
Serial Number........: 8XV7N15A20000987
--------------------------------------------
checking product...
OKAY [  0.020s]
sending 'boot' (12189 KB)...
OKAY [  0.320s]
writing 'boot'...
OKAY [  0.187s]
sending 'recovery' (17693 KB)...
OKAY [  0.443s]
writing 'recovery'...
OKAY [  0.259s]
erasing 'system'...
OKAY [  0.062s]
sending sparse 'system' (483334 KB)...
FAILED (remote: data too large)
finished. total time: 1.374s
punkunity@GhostShell:~/Downloads/angler-nrd90u$

**Comment by thestinger** [comment]
You need to use an up-to-date fastboot/adb on a machine with enough memory. You're probably using an incompatible old distribution build.

**Comment by PunkUnity** [comment]
I am on Xubuntu 15.04, fully updated. Just deleted all my adb/fastboot/android studio stuff and re-downloaded it all. I regularly build/compile roms and kernels for many different ROMs and a few different devices. I am going to try and build form source for now. Oh ya, cannot repo init the "stable" branch as per the copper instructions. I could however repo init the "development" branch instead and will go forward with that for now.

**Comment by thestinger** [comment]
What error do you get from using a stable tag?

**Comment by PunkUnity** [comment]
Also, machine is an intel i7 Devil's Canyon, 32GB RAM 1TB Samsung EVO 850, intercooler, etc etc

**Comment by PunkUnity** [comment]
remote refs tags not found (for repo error i think)

**Comment by PunkUnity** [comment]
just try it real quick

**Comment by thestinger** [comment]
This works fine here:

```
repo init -u https://github.com/CopperheadOS/platform_manifest.git -b refs/tags/NRD90U.2016.09.23.17.14.14
```

Do you get an error while syncing? Need to know the full error.

**Comment by thestinger** [comment]
> I am on Xubuntu 15.04, fully updated.

It won't have an up-to-date fastboot in the official repositories though. You need to make sure to use fastboot from an up-to-date SDK. The old versions aren't compatible.

**Comment by PunkUnity** [comment]
i just updated all my sdk etc. Rebooted. Same problem. Cannot flash the file using flash-all.sh

**Comment by thestinger** [comment]
So run `which fastboot` and verify that it's really the one from the SDK.

**Comment by PunkUnity** [comment]
OK, thanks for all the help guys! I got it installed! Seems in the end fastboot was still hiding in /usr/bin/. I don't know what the cause of the init error was, but it seems it is working on your end, so I will leave it at that and say this is resolved. Thanks!
