### ISSUE TITLE
Option to hide QuickSettings from Lockscreen

### ISSUE THREAD

**Issue by rosswell98** [copperhead/bugtracker#460]
It is possible to add a toogle in settings to remove the quick settings on the Lockscreen?
I saw that it's a security issue...
A bad guy can take the phone and connect it to a rogue AP or things like this.
The other solution is to remove all icons in the panel but that's not "usable"...
If you can't because it's more a Android issue, I can understand!

**Comment by thestinger** [comment]
It's in scope for CopperheadOS, but it's likely not going to be implemented any time in the near future unless someone contributes the code.

**Comment by thestinger** [comment]
Going to be approaching this differently by just extending how the location quick setting works to the others.
