### ISSUE TITLE
fix issues caught by -fsanitize=bounds in pico tts

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#461]

**Comment by jgeerds** [comment]
What is the exact issue?

On a ~ 10 days old build of CopperheadOS Pico TTS were broken on my Nexus 5X. Today I updated to the latest version and now it works (i.e. it doesn't crash anymore) but the sound is pretty bad. To be honest, it's so bad that it is unusable. Pico TTS worked pretty well for me on the previous Android (Lollipop?) version. Are these the issues you mean?

**Comment by thestinger** [comment]
It's unlikely that these upstream out-of-bounds access bugs are the cause of the poor sound quality. The bounds sanitizer is disabled for this library and other code where it catches issues during regular use. It's not within the scope of CopperheadOS to fix every upstream bug.

**Comment by thestinger** [comment]
For the sound quality issue, see https://github.com/copperhead/bugtracker/issues/426. It's probably an AOSP issue so it's not something that we are going to act on. If a set of clean fixes are put together for the pico tts issues, we'll apply them. Ideally, they should be submitted upstream too.

**Comment by thestinger** [comment]
Not going to track these upstream bugs here anymore. The canonical list of exceptions is in our sources.
