### ISSUE TITLE
No separated passwords :sad:

### ISSUE THREAD

**Issue by Vodochnik** [copperhead/bugtracker#466]
Last 5 days i was hunting for version with support of separated passwords. No luck.
I have read this https://twitter.com/CopperheadOS/status/779802381894680576

Since entering fingerprint can be forced, it's not an option for me.

Any chance to get latest marshmallow build for Nexus 5x bullhead, containing this feature?

I _really_ need a possibility to set strong passphrase for encryption and password for unlock.

P.S. This feature is still advertised https://copperhead.co/android/docs/technical_overview ;)

**Comment by thestinger** [comment]
See https://github.com/copperhead/bugtracker/issues/451. Patches implementing this are welcome. I won't have time to deal with it for a while, *especially* if we end up supporting new devices.

> P.S. This feature is still advertised https://copperhead.co/android/docs/technical_overview ;)

The Technical Overview isn't going to have everything deleted from it when porting to a new version and then added back as it's ported. You can follow the issue tracker if you want to know what is and isn't ported.

**Comment by thestinger** [comment]
You don't seem to understand the fingerprint proposal if you don't see that the 2-factor proposal is strictly better than the old feature.

**Comment by thestinger** [comment]
> Any chance to get latest marshmallow build for Nexus 5x bullhead, containing this feature?

No chance. There is no Marshmallow support in CopperheadOS anymore. The last Marshmallow builds are not secure anymore since they're missing security updates. I don't keep old builds regardless.

**Comment by Vodochnik** [comment]
is current release rootable? I had no luck sideloading SuperSU for vdc cryptfs changepw password.
I need root just to set another (stronger) password for cryptFS.

**Comment by thestinger** [comment]
Rooting or making other modifications like that to the OS after building is not supported. If you want this feature, help to implement a replacement for it.

**Comment by Vodochnik** [comment]
I'm sooo behind you in this particular field "android dev"... i can help only with some donation:)
So you get time for this work.
