### ISSUE TITLE
Support of OnePlus 3

### ISSUE THREAD

**Issue by ch40s** [copperhead/bugtracker#468]
I think that support of OnePlus 3 is a must. It has amazing hardware specs and a fair price so that would make Copperhead much more popular.

**Comment by thestinger** [comment]
Only devices with Android Open Source Project support will be supported by CopperheadOS. There are already *four* supported AOSP devices that we don't have the resources to support:

* Nexus 6
* Pixel C
* Pixel
* Pixel XL

There's no way that supporting a device without proper monthly security updates and immediate migration to new Android versions upon release is going to happen. CopperheadOS is solely based on Nougat now, and in fact just moved from nougat-release -> nougat-bugfix-release on the day it was released this month.
