### ISSUE TITLE
ASOP Gesture Typing not working

### ISSUE THREAD

**Issue by jpfingstmann** [copperhead/bugtracker#470]
Under Settings -> Languages and Input -> Virtual Keyboard -> Android Keyboard (ASOP) -> Gesture Typing, the "Enable gesture typing" option is enabled, but I am unable to use gesture typing.  I've previously always used "Swype" or equivalent on my phone as I find it much more efficient, personally.  I've tried disabling it and re-enabling it, I've tried installing an alternate keyboard (AnySoftKeyboard) to switch back and forth between options in hopes it might reset it to working, but it still does not function.  I found this page that mentions a similar issue and the fix is installing a library that is missing (libjni_latinime.so), but without root, I cannot verify if this is the issue (I've always run with optional root enabled, I'm guessing that's not enabled on CopperheadOS by design).
Site mentioned with similar issue/fix: http://rubenalamina.mx/2015/06/02/how-to-fix-aosp-keyboard-gesture-typing-in-cyanogenmod-12-and-12-1/

This is a clean install of CopperheadOS from the 2016-10-05 03:23:30 package for Nexus 5X.

**Comment by thestinger** [comment]
Gesture typing isn't an AOSP feature. It's provided by the proprietary Google Play fork of the keyboard via a library that's not included in AOSP.
