### ISSUE TITLE
Disable EXIF info in photos

### ISSUE THREAD

**Issue by condor0765** [copperhead/bugtracker#471]
Since you have disabled location info in the photos, can you also please disable EXIF in the photos? Just look
line 209: `private void writeExifData() throws IOException {`
in the file
`platform_packages_apps_Camera2/src/com/android/camera/exif/ExifOutputStream.java`

**Comment by thestinger** [comment]
There's not much point in dumping time into the essentially unmaintained Camera app. Not going to be working on any issues related to it. The community should work on alternatives.

**Comment by thestinger** [comment]
We're going to be making our own camera app.
