### ISSUE TITLE
Flashing new 5x system image hangs

### ISSUE THREAD

**Issue by weajr** [copperhead/bugtracker#484]
Using the latest image files from CH running SDK on Linux.  System starts to flash, the device responds, then when it gets to the System Image (500k) file 1 of 3 it hangs, the device just shows downloading.

The device and the flash-all.sh run fine, I am able to reflash the device back to the factory image with no problem.

I have redownloaded and tried 2 of the latest 5x image sets, reflashed back to factory image and started over, all results are the same.

Any ideas?

**Comment by thestinger** [comment]
Maybe you don't have enough memory or space in `/tmp` if it's using `/tmp`. The CopperheadOS images don't use compression for the inner image zip file in order to properly take advantage of the outer xz compression, so it's quite large.

**Comment by weajr** [comment]
Plenty of system RAM, only terminal running. /tmp is empty

 

Still hanging at 

 

sending sparse ‘system’  1/3

**Comment by thestinger** [comment]
How big is `/tmp` though? And how much memory is there specifically?

**Comment by weajr** [comment]
783M, most likely not big enough, correct?

**Comment by thestinger** [comment]
If it's actually using /tmp then it would be too small.

**Comment by weajr** [comment]
The default Nexus 5X factory image is over 2G, it flashes with no problem?

**Comment by thestinger** [comment]
Just try with a larger /tmp and more memory (by adding a swap file perhaps).

**Comment by weajr** [comment]
Got it, had to use another system with more RAM.

 

Installed OK, thanks a bunch

 

R/

Bill
