### ISSUE TITLE
Documentation to verify builds with gpg does not work

### ISSUE THREAD

**Issue by j1mc** [copperhead/bugtracker#493]
The documentation to verify the builds says:

```
Verify the factory images using the GPG signature:

gpg --recv-keys 65EEFE022108E2B708CBFCF7F9E712E59AF5F22A
gpg --verify bullhead-factory-2016.05.03.18.54.15.tar.xz.sig bullhead-factory-2016.05.03.18.54.15.tar.xz
```
But when I attempt the first command, I get:

```
$ gpg --recv-keys 65EEFE022108E2B708CBFCF7F9E712E59AF5F22A
gpg: no keyserver known (use option --keyserver)
gpg: keyserver receive failed: bad URI
```

Please include the desired keyserver as part of the documentation. Thank you.

**Comment by thestinger** [comment]
Modern versions of GPG already have default keyservers.

Note that the documentation (`man gpg`) states this:

```
       --keyserver name
              This option is deprecated - please use the --keyserver in `dirmngr.conf' instead.
```

I don't want to include a guide on configuring GPG, especially when the default skeleton configuration file includes keyservers already.
