### ISSUE TITLE
flash-all.sh fails on Nexus 5X: "remote: data too large"

### ISSUE THREAD

**Issue by PureW** [copperhead/bugtracker#496]
Hi,

I just tried to flash bullhead-factory-2016.11.16.11.42.49.tar.xz onto a new Nexus 5X delivered last week.

I followed the instructions on https://copperhead.co/android/docs/install but the `./flash-all.sh` program experienced an error in the middle of the procedure: 

> sending sparse 'system' (524299 KB)...
> FAILED (remote: data too large)
> finished. total time: 18.897s

 See full log below:

https://gist.github.com/PureW/782017a3ac59fe2ff46f0279beff3b65

Unfortunately, I didn't see the line with FAILED, but only the last line saying finished so I assumed it all went fine. I then proceeded with
```
sudo fastboot oem lock
...
OKAY [ 65.455s]
finished. total time: 65.455s
```

I seem to have a corrupt system now. At boot, the display shows this link https://support.google.com/nexus/answer/6185381?visit_id=1-636154181357081261-3590643701&p=verified_boot&rd=1

and then proceeds to wait forever on the "Google" logo without proceeding.

**Comment by thestinger** [comment]
You don't have enough memory or enough space in `/tmp`.

**Comment by PureW** [comment]
Any advice on how to proceed?

**Comment by thestinger** [comment]
You need more memory or a bigger /tmp. If you really don't have enough physical memory, you can make a swap file.

**Comment by thestinger** [comment]
Also make sure you're using an up-to-date fastboot/adb, not an out-of-date distribution build. People still run into that even though a warning was added. Sometimes because they think they're using a different adb/fastboot installation than what is actually in PATH.

**Comment by PureW** [comment]
Hmm still experiencing that problem with new adb/fastboot and plenty of space. See:

> (python3) 9:24:31 anders@falcon bullhead-nbd91p master ? free -h                                                  1 ↵
>               total        used        free      shared  buff/cache   available
> Mem:            15G        2.1G        9.0G        416M        4.5G         12G
> Swap:          3.7G          0B        3.7G
> (python3) 9:24:38 anders@falcon bullhead-nbd91p master ? df -h
> Filesystem             Size  Used Avail Use% Mounted on
> udev                   7.8G     0  7.8G   0% /dev
> tmpfs                  1.6G  9.9M  1.6G   1% /run
> /dev/sda5               21G   14G  6.3G  68% /
> tmpfs                  7.9G  394M  7.5G   5% /dev/shm
> tmpfs                  5.0M  4.0K  5.0M   1% /run/lock
> tmpfs                  7.9G     0  7.9G   0% /sys/fs/cgroup
> /dev/sda2               96M   29M   68M  30% /boot/efi
> /dev/sdb3              828G  614G  172G  79% /home
> cgmfs                  100K     0  100K   0% /run/cgmanager/fs
> tmpfs                  1.6G   12K  1.6G   1% /run/user/1000
> /home/anders/.Private  828G  614G  172G  79% /home/anders
> (python3) 9:24:41 anders@falcon bullhead-nbd91p master ? which adb
> /home/anders/Downloads/android-sdk-linux/platform-tools/adb
> (python3) 9:24:49 anders@falcon bullhead-nbd91p master ? which fastboot
> /home/anders/Downloads/android-sdk-linux/platform-tools/fastboot
> (python3) 9:24:53 anders@falcon bullhead-nbd91p master ? adb version
> Android Debug Bridge version 1.0.36
> Revision 84e3321d5db3-android
> (python3) 9:24:56 anders@falcon bullhead-nbd91p master ?

Full log at https://gist.github.com/PureW/a4616231e559b9f408586db1f93b0d49

I wonder if the first line hints at the problem?

> target reported max download size of 536870912 bytes

That is smaller than image-bullhead-nbd91p.zip at 1583824581 bytes...

**Comment by PureW** [comment]
UPDATE: I downloaded the latest copperhead: bullhead-factory-2016.11.21.18.36.19.tar.xz and using that one it works as it should.

bullhead-factory-2016.11.16.11.42.49.tar.xz  seems to have caused the problems.

Both files where validated using gpg and the signature as instructed in the install doc.

**Comment by thestinger** [comment]
It's not a problem with the images. It's an issue with your setup. That adb / fastboot version is out-of-date. Make sure that the OS you flashed actually passes boot verification once the bootloader is locked. I wouldn't be surprised if it was corrupted.

**Comment by PureW** [comment]
I'm confused, the platform tools were just downloaded using 
```tools/android update sdk --no-ui ```

Are you saying that the following is an old adb/fastboot? Or that the flash-all-script somehow found another adb on the system?
```? adb version        
Android Debug Bridge version 1.0.36
Revision 84e3321d5db3-android
fastboot --version                                    
fastboot version 84e3321d5db3-android```

I can't seem to find the version

**Comment by PureW** [comment]
You are right of course. fastboot has to be executed with sudo, and sudo has a different PATH leading to old fastboot.

Sorry for wasting your time.

I've been using copperhead for almost a year now, starting on the Nexus 5. I'd just like to thank you for the amazing work you put in!

**Comment by thestinger** [comment]
I updated the documentation to include a note about PATH because multiple people have run into that. Although, I still expect that people will run into it, but the documentation might as well try harder to cover the common issues.

**Comment by darknetj** [comment]
@PureW sudo isn't required for fastboot - ensure you're using the proper udev rules
read:
https://wiki.cyanogenmod.org/w/UDEV

**Comment by Harut42** [comment]
Link is broken : https://wiki.cyanogenmod.org/w/UDEV
