### ISSUE TITLE
Miracast

### ISSUE THREAD

**Issue by Cj-Malone** [copperhead/bugtracker#497]
This isn't a security issue, and it's not really relevant in the context in of Copperhead OS, but I thought I'd ask.

It seems Google has disabled Miracast on devices released after the Nexus 5, and it appears to only have been done as a way to promote the propriety ChromeCast/GoogleCast. Not a technical reason.

I would appreciate it being enabled, see [this commit](https://github.com/CyanogenMod/android_device_lge_bullhead/commit/4ee7122b06c7cd03256021ac661c71d04a9cc927). It is just a value in the overlay, or if enabling for all devices by default this [value](https://github.com/CopperheadOS/platform_frameworks_base/blob/nougat-mr0.5-release/core/res/res/values/config.xml#L1806).

I am running the signed builds on my flounder and bullhead devices, so even if I downloaded and built myself I still couldn't test, but as it is in CyanogenMod I can't see their being an issue.

I know it's not the scope of Copperhead OS, but it is a small patch and I'd really appreciate it.

**Comment by thestinger** [comment]
I need someone to try enabling this and test it to confirm that it works without other changes.

**Comment by BenBaltz** [comment]
@Cj-Malone You could try adding persist.debug.wfd.enable=1 to your build.prop since it does the same as switching that bool.

**Comment by Cj-Malone** [comment]
If someone could post a signed bullhead build with either the commit or the build prop change I could test it.

**Comment by ksala** [comment]
I've tested it with my Nexus 5x and a Sony KD-49X8308C, and it's not working.
The phone and the TV can connect, but then mediaserver seems to crash on the phone, and the TV errors out (just a generic "couldn't connect, retry).

This is the `adb logcat` taken during the connection: https://hastebin.com/raw/zanokunuhu

**Comment by thestinger** [comment]
I'm unwilling to enable a major feature that Google is not testing upstream unless there are people willing to step up to properly maintain it. It's not going to be enough to work around the issues that are uncovered until it works. It needs proper maintenance. Until there are people willing to step up to devote multiple hours a week to maintaining components like this, it won't be happening. CopperheadOS has a single full time developer, myself, and there isn't enough time to take on the responsibility of maintaining new components not used / tested by Google for stock Android.

**Comment by thestinger** [comment]
This will only be reconsidered when there are people contributing substantially to either CopperheadOS or a separate project aiming to maintain production quality AOSP releases for Nexus/Pixel. A lot of help is needed with the existing scope of the project before it can be expanded.

**Comment by Cj-Malone** [comment]
@b52 Chromecast uses a proprietary protocol, and the API is in Google Play Services which aren't a part of Copperhead OS.

**Comment by b52** [comment]
So there is effectively no way to make this work without the Google Services? I used to use Plex to stream stuff from my server to my TV using the chromecast, I kinda miss this setup

**Comment by darknetj** [comment]
@b52 there may be a way to do it, however, media player services is not in the scope of CopperheadOS and thus won't have resources pulled to it

please note: this issue is considered closed

**Comment by b52** [comment]
@darknetj I do understand that this is not in scope of CopperheadOS, yet I wondered if someone has some pointers how one can achieve it on his own.

**Comment by ksala** [comment]
As far as I know, the ChromeCast API is part of the Google Play Services. This mean that you can't really do much about it without installing them, for which you need to build your own custom build of CopperheadOS or unlock the bootloader and flash something like opengapps (both not officially supported by Copperhead, obviously).

The only applications that supports Chromecast without the Play Services are old build of YouTube and BubbleUPnP (which allow you to cast local files, might be enough for your needs).

**Comment by ksala** [comment]
For future reference, this patch fixes Miracast on my nexus 5x: https://github.com/VanillaNexusSource/android_frameworks_av/commit/7fcba07bb7d41d723bc435546089480b20faf917

I understand that it likely won't get merged with COS as the Miracast code is not maintained anymore, but it might be helpful for anyone compiling it himself.
