### ISSUE TITLE
device corrupt warning, then hangs on Nexus 5X

### ISSUE THREAD

**Issue by neuhaus** [copperhead/bugtracker#498]
I flashed a Nexus 5x after verifying the GPG signature.

I tried these firmware versions:

- NBD91P.2016.11.21.18.36.19
- NBD91P.2016.11.16.11.42.49
- NBD91P.2016.11.10.09.53.38

I get the yellow warning that the OS has changed with the fingerprint 0AA1-7043-4D5F.

I then get the "erasing" screen followed by the yellow warning again.

I then get the red warning that the device is corrupt. I think this is an error! :warning: 
After that it hangs at the Google logo (i waited several minutes). How long should it realistically take at this point?

I have the 16GB version of the Nexus 5x.

**Comment by thestinger** [comment]
> I then get the red warning that the device is corrupt. I think this is an error!

It's not an error. It's legitimately corrupt. You didn't flash the system and/or vendor images successfully.

**Comment by neuhaus** [comment]
I think you are right. It appears my adb is too old.

**Comment by thestinger** [comment]
https://copperhead.co/android/docs/install#prerequisites warns about this. Only use it from the SDK unless you use Arch, in which case android-tools is up-to-date enough (Android 7.0.0_r1).

**Comment by thestinger** [comment]
(the problem is really fastboot but adb/fastboot almost always get shipped together as a unit)

**Comment by neuhaus** [comment]
OK, for reference, here's what I did on Ubuntu 14.04:

    # sudo apt-get purge  android-tools-adb     android-tools-fastboot

Download Android SDK command line tools from https://developer.android.com/studio/index.html#downloads (current filename: `android-sdk_r24.4.1-linux.tgz`)

Unpack the tarball

Download and update the tools using `cd android-sdk-linux; tools/android update sdk --no-ui -t "platform-tool,tool"`

Copy them somewhere in the path
    # sudo cp platform-tools/{adb,fastboot} /usr/local/bin

After that I had up-to-date tools and flashing Copperhead worked. :+1: 

    $ fastboot --version
    fastboot version 302830efc153-android
    $ adb version
    Android Debug Bridge version 1.0.36
    Revision 302830efc153-android

**Comment by vishalparkar** [comment]
At me,
no success even for

$ fastboot --version
fastboot version 3db08f2c6889-android
Installed as /usr/local/sbin/platform-tools/fastboot

$ adb version
Android Debug Bridge version 1.0.39
Revision 3db08f2c6889-android
Installed as /usr/local/sbin/platform-tools/adb

Pl help.

**Comment by neuhaus** [comment]
Did you install them in parallel with the OS versions?

**Comment by vishalparkar** [comment]
Got them from the stock image in zipped format.
Thanks!

--
With Regards.
Vishal Parkar.
