### ISSUE TITLE
Change the gps XTRA download location to use https

### ISSUE THREAD

**Issue by JasperWallace** [copperhead/bugtracker#499]
At the moment they are plain text, and if there is a vulnerability in the modem an attacker who can mitm can inject a malicious xtra2.bin file.

The file is available from the same servers with https.

This may be as simple as changing http: to https: in gps.conf here:

https://github.com/CopperheadOS/device_lge_bullhead/blob/nougat-mr0.5-release/gps.conf

or might need changing this code too:

https://github.com/CopperheadOS/platform_frameworks_base/blob/nougat-mr0.5-release/services/core/java/com/android/server/location/GpsXtraDownloader.java#L116

I can look into this and test a change, but it will take me a while to setup a build server.

**Comment by thestinger** [comment]
It needs to be tested before it can be changed.

**Comment by thestinger** [comment]
This is implemented upstream in 7.1.1.
