### ISSUE TITLE
Add DuckDuckGo as search engine in Chromium

### ISSUE THREAD

**Issue by craftyguy** [copperhead/bugtracker#505]
I would like to have DDG as an option in the list of search engines used by Chromium!

**Comment by thestinger** [comment]
I'll add it for the next release. DuckDuckGo doesn't appear to have the search suggestions API or the other extended features, so it will be barebones support.

**Comment by craftyguy** [comment]
> DuckDuckGo doesn't appear to have the search suggestions API or the other extended features, so it will be barebones support.

They support suggestions, provided in json, through duckduckgo.com/ac:

https://duckduckgo.com/ac/?q=copperhead

**Comment by thestinger** [comment]
Ah, it outputs the right format with https://duckduckgo.com/ac/?q=copperhead&type=list

**Comment by thestinger** [comment]
It's now added, and has been made the default search engine since search suggestions can work with it after all (and the other extended features aren't very important):

https://github.com/CopperheadOS/chromium_patches

**Comment by craftyguy** [comment]
Awesome, thanks a lot!
