### ISSUE TITLE
Scramble PIN layout

### ISSUE THREAD

**Issue by raccoonia** [copperhead/bugtracker#508]
It would be a great added feature to have the ability to scramble the PIN layout for the lock screen. 

For all of us that use PIN to unlock the phone it is possible to intercept the number by seeing the location the finger is typing or by seeing the finger marks on the screen.

From what I see, this feature is already implemented in other ROMs, would be great to have it also here.

Thank you for your time and effort, keep up the good work!

**Comment by thestinger** [comment]
See #106.
