### ISSUE TITLE
Opening Carrier Settings page fails on Nexus 5x

### ISSUE THREAD

**Issue by Susurrus** [copperhead/bugtracker#513]
I'm running COS 2016.11.27.21.33.03 on a Nexus 5x. I'm not able to get mobile data working, so I'd like to edit my APN settings to get that fixed. I believe these settings are under Wireless & networks -> Cellular networks -> Carrier settings. But when I select "Carrier Settings" the screen goes black very briefly then kicks me back to the "Wireless & networks" page.

**Comment by thestinger** [comment]
On which carrier? Sprint?

**Comment by Susurrus** [comment]
Yes, Sprint. They seem to have the most APN problems.

**Comment by thestinger** [comment]
CopperheadOS intentionally leaves out SprintDM so this isn't going to work right now.

**Comment by Susurrus** [comment]
So there's no way for me to set APN with COS on Sprint?

**Comment by Susurrus** [comment]
I don't know what SprintDM is.

**Comment by thestinger** [comment]
Sprint isn't going to work properly right now, intentionally, because we don't include the app giving them system-level privileges on the device.

**Comment by thestinger** [comment]
The only way it's going to be supported is if someone wants to dedicate time to figuring out how to make it work without SprintDM or if our concerns about SprintDM are addressed. It's working as designed right now. It could be documented that Sprint isn't supported due to the craziness they require.

**Comment by thestinger** [comment]
#514

**Comment by Susurrus** [comment]
Thanks, this would be definitely helpful to have this documented somewhere. It's been painful not having LTE (I don't seem to get 3G anywhere either) with Sprint on COS, so unfortunately I'm going to need to go back to CyanogenMod until that work happens.

**Comment by thestinger** [comment]
It's likely not going to happen. There are no contributors to the project and we can't test Sprint, not that we would have time to work on it.
