### ISSUE TITLE
document incompatibility with Sprint due to leaving out SprintDM

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#514]

**Comment by thestinger** [comment]
The state of this on the Pixels is no longer clear and the Nexus 5X and 6P aren't sold anymore. The carrier app situation on the Pixels is different.

**Comment by Susurrus** [comment]
Is CHOS still available for the Nexus 5x and 6p? If so, then this should still be documented. If builds are no longer being done, then yes I don't think this needs documenting.

**Comment by thestinger** [comment]
They aren't being sold which is all that matters. This has already had to be worked through on a case-by-case basis for customers on the 5X and 6P.

**Comment by thestinger** [comment]
(Sprint can work on them, but not typically out-of-the-box)
