### ISSUE TITLE
Add support in Chromium for custom input of search engine

### ISSUE THREAD

**Issue by craftyguy** [copperhead/bugtracker#523]
This may be a rather significant addition to Chromium, but given alternative host-your-own metasearch engines (like [searx](https://github.com/asciimoo/searx)) and other local or regional search engines that people might want to use, this request is to add a 'custom' option in chromium  on the Search Engine setting page where the url of any search engine supporting http GET could be input in the form of: 

```https://example.com?q=%s```

Where the ```%s``` is input by the user into the custom field and matched/replaced by chromium with the term(s) the user wants to search for (use whatever letter or character(s) you want, this is just an example), and the  ```https://example.com/?q=```  portion is also input by the user but dependent upon search engine (supporting HTTP GET).

The intention is to provide basic search functionality using a custom-specified search engine url. Any advanced search features  (search suggestions, etc) wouldn't need to be supported.

I've seen browsers over the years support this feature (Opera did ~15 years ago when I last used it, if I recall), I can dig around for specific examples if there's some confusion about what this looks like.

**Comment by thestinger** [comment]
Chromium supports this in the desktop UI but they haven't implemented it in the Android UI along with many of the other features.

**Comment by thestinger** [comment]
I don't really think I want to maintain something like this out-of-tree. It would have to be done upstream.

**Comment by craftyguy** [comment]
Understood, thank you for the quick response.

OMG, also just realized you're the same thestinger who developed termite! THANK YOU!!!

**Comment by thestinger** [comment]
I think they would probably happily implement this upstream, the Android UI just needs a lot of work to reach feature parity. Similar to how site settings UI is missing outside of settings, unlike in the desktop UI.

**Comment by thestinger** [comment]
Supposedly this is implemented for Chrome 57 but I couldn't get it to work on the sites that I tried.

**Comment by thestinger** [comment]
Visit qwant.com -> do a search -> go to settings -> search engine -> select it in recently visited (note it seems you need to do a search to trigger this).
