### ISSUE TITLE
bluetooth broken

### ISSUE THREAD

**Issue by zongo** [copperhead/bugtracker#525]
**Steps To Reproduce The Bug**
Download NMF26O.2016.12.07.07.47.51 factory image. Install as per recommended steps. 
Install with twrp and latest OS same issue. 
Pairing device: Jabra Wireless headsets
Bluetooth eventhoug enabled says disconnected in settings.
Any pairing with device will crash bluetooth share app.
Trying to pair after that display the error: "Could not pair with Jabra REVO because of an incorrect PIN or Passkey". No pop up screen to insert pin or passkey.
Reproducible everytime
**CopperheadOS version**
NMF26O.2016.12.07.07.47.51
Nougat 7.1.1
**Device Model**
Nexus 6P
adb logcats attached 
[logcat.txt](https://github.com/copperhead/bugtracker/files/643905/logcat.txt)

**Comment by thestinger** [comment]
Thanks, the log is helpful. This is likely an out-of-bounds access in that bluetooth library detected by -fsanitize=bounds.

**Comment by thestinger** [comment]
Try the latest release (NMF26O.2016.12.12.04.03.44). It shouldn't crash anymore.

**Comment by thestinger** [comment]
This bug will be kept open to track fixing the detected undefined access even though it should be successfully worked around now.

**Comment by zongo** [comment]
OTA update with latest, pairing is still failing. 
Same issue with bluetooth share app is crashing. 
Crashing happens with Jabra headset. Even though crash with bluetooth app, devices says headset is paired.  When trying to play music through headset, it does not work. 
Issue not happening with Marshmallow. 
Logs attached.
[log6.txt](https://github.com/copperhead/bugtracker/files/648262/log6.txt)

**Comment by thestinger** [comment]
Well, it's almost certainly the bounds sanitizer catching an out-of-bounds access, but it could be in any of the libraries statically linked into that one. I don't have any bluetooth devices to test with, so all I can do is take shots in the dark. I don't have room to keep around symbols for each build but I'll do it for the next set.

**Comment by zongo** [comment]
Thank you for your help.  This is not a show stopper anyways. Love the ROM. This is exactly what I was looking for. Donated 100 $ today. Thank you again for your time.

**Comment by thestinger** [comment]
Thanks to reproducible builds this can probably actually be solved now:

```
[strcat@thinktank hw]$ addr2line -e bluetooth.default.so 000d5416
/proc/self/cwd/system/bt/stack/./sdp/sdp_api.c:361 (discriminator 1)
```

**Comment by thestinger** [comment]
So it's really libbt-stack that needs the bounds exception, it just gets statically linked into the other library.

**Comment by thestinger** [comment]
Please try the new NMF26Q.2016.12.17.07.29.30 release.

**Comment by dark159123** [comment]
I can confirm bluetooth is now working, testing with Pebble+Gadgetbridge.
Thanks mate!

**Comment by thestinger** [comment]
#617
