### ISSUE TITLE
802.1x EAP does not connect and is broken

### ISSUE THREAD

**Issue by zongo** [copperhead/bugtracker#527]
Actual Result: EAP appears to be in a constant state of connection. The connection is never happening
EAP method is PEAP. 
If option CA certificate is left with 'Please Select', the tab connect is always grayed out. Workaround is select 'Do not validate' and the tab connect will not be grayed out anymore.  I don't know if this is expected but never had to do this step under Marshmallow. 
Issue is reproducible everytime. 
Android Nougat 7.1.1 
Build: NMF260.2016.12.07.07.47.51
Device: Nexus 6P 
Expected Result: Expected the device to connect to EAP network using PEAP authentication method as it used to be the case under Marshmallow. 

Logs may show this to be Android related but very unsure. Full logs attached.
Let me know if you need anything else. 
[log1.txt](https://github.com/copperhead/bugtracker/files/645427/log1.txt)

12-12 09:13:11.053  4982  5412 E WifiScanner: listener cannot be found
12-12 09:13:11.061 13498 13498 E wpa_supplicant: PNO: In assoc process
12-12 09:13:11.062  4982  5415 E SupplicantWifiScannerImpl: PNO state change to true failed
12-12 09:13:11.062  4982  5415 E SupplicantWifiScannerImpl: Failed to start PNO scan
12-12 09:13:11.067  4982  5412 E WifiConnectivityManager: PnoScanListener onFailure: reason: -1 description: pno scan failed
12-12 09:13:13.944  4982  5412 E WifiScanner: listener cannot be found
12-12 09:13:13.952  4982  5415 E SupplicantWifiScannerImpl: Failed to start scan, freqs=null
12-12 09:13:13.962  4982  5412 E WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
12-12 09:13:13.975  4982  5415 E SupplicantWifiScannerImpl: Failed to start scan, freqs=null
12-12 09:13:13.975  4982  5412 E WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
12-12 09:13:15.970  4982  5415 E SupplicantWifiScannerImpl: Failed to start scan, freqs=null
12-12 09:13:15.972  4982  5412 E WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
12-12 09:13:18.635  4982  5415 E SupplicantWifiScannerImpl: Failed to start scan, freqs=null
12-12 09:13:18.637  3944  5499 E fpc_fingerprint_hal: capture_image failed -4
12-12 09:13:18.643  3944  5499 E fpc_fingerprint_hal: do_identify failed -4
12-12 09:13:18.983  4982  5415 E SupplicantWifiScannerImpl: Failed to start scan, freqs=null
12-12 09:13:18.984  4982  5412 E WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
12-12 09:13:20.982  4982  5415 E SupplicantWifiScannerImpl: Failed to start scan, freqs=null
12-12 09:13:20.984  4982  5412 E WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
12-12 09:13:23.991  4982  5415 E SupplicantWifiScannerImpl: Failed to start scan, freqs=null
12-12 09:13:23.991  4982  5412 E WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
12-12 09:13:23.991  4982  5412 E WifiConnectivityManager: Failed to successfully start single scan for 5 times
12-12 09:13:43.230  5593  5593 E RichInputConnection: Unable to connect to the editor to retrieve text.
12-12 09:13:43.237  5593  5593 E RichInputConnection: Unable to connect to the editor to retrieve text.
12-12 09:14:08.651  4982  5415 E SupplicantWifiScannerImpl: Failed to start scan, freqs=null
12-12 09:14:09.269  4982  5415 E SupplicantWifiScannerImpl: Failed to start scan, freqs=null
12-12 09:14:13.995  4982  5415 E SupplicantWifiScannerImpl: Failed to start scan, freqs=null
12-12 09:14:13.997  4982  5412 E WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
12-12 09:14:18.665  4982  5415 E SupplicantWifiScannerImpl: Failed to start scan, freqs=null
12-12 09:14:19.016  4982  5415 E SupplicantWifiScannerImpl: Failed to start scan, freqs=null
12-12 09:14:19.018  4982  5412 E WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
12-12 09:14:24.033  4982  5415 E SupplicantWifiScannerImpl: Failed to start scan, freqs=null
12-12 09:14:24.035  4982  5412 E WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
12-12 09:14:29.045  4982  5415 E SupplicantWifiScannerImpl: Failed to start scan, freqs=null
12-12 09:14:29.046  4982  5412 E WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
12-12 09:14:29.091 13498 13498 E wpa_supplicant: PNO: In assoc process
12-12 09:14:29.091  4982  5415 E SupplicantWifiScannerImpl: PNO state change to true failed
12-12 09:14:29.091  4982  5415 E SupplicantWifiScannerImpl: Failed to start PNO scan
12-12 09:14:29.092  4982  5412 E WifiConnectivityManager: PnoScanListener onFailure: reason: -1 description: pno scan failed
12-12 09:14:31.060  4982  5415 E SupplicantWifiScannerImpl: Failed to start scan, freqs=null
12-12 09:14:31.062  4982  5412 E WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
12-12 09:14:34.095  4982  5412 E WifiScanner: listener cannot be found
12-12 09:14:34.101 13498 13498 E wpa_supplicant: PNO: In assoc process
12-12 09:14:34.102  4982  5415 E SupplicantWifiScannerImpl: PNO state change to true failed
12-12 09:14:34.102  4982  5415 E SupplicantWifiScannerImpl: Failed to start PNO scan
12-12 09:14:34.103  4982  5412 E WifiConnectivityManager: PnoScanListener onFailure: reason: -1 description: pno scan failed
12-12 09:14:36.083  4982  5415 E SupplicantWifiScannerImpl: Failed to start scan, freqs=null
12-12 09:14:36.085  4982  5412 E WifiConnectivityManager: SingleScanListener onFailure: reason: -1 description: Scan failed
12-12 09:14:36.085  4982  5412 E WifiConnectivityManager: Failed to successfully start single scan for 5 times
12-12 09:14:39.106  4982  5412 E WifiScanner: listener cannot be found
12-12 09:14:39.115 13498 13498 E wpa_supplicant: PNO: In assoc process
12-12 09:14:39.116  4982  5415 E SupplicantWifiScannerImpl: PNO state change to true failed
12-12 09:14:39.117  4982  5415 E SupplicantWifiScannerImpl: Failed to start PNO scan
12-12 09:14:39.121  4982  5412 E WifiConnectivityManager: PnoScanListener onFailure: reason: -1 description: pno scan failed
12-12 09:14:44.127  4982  5412 E WifiScanner: listener cannot be found
12-12 09:14:44.137 13498 13498 E wpa_supplicant: PNO: In assoc process
12-12 09:14:44.139  4982  5415 E SupplicantWifiScannerImpl: PNO state change to true failed
12-12 09:14:44.139  4982  5415 E SupplicantWifiScannerImpl: Failed to start PNO scan
12-12 09:14:44.141  4982  5412 E WifiConnectivityManager: PnoScanListener onFailure: reason: -1 description: pno scan failed
12-12 09:14:49.146  4982  5412 E WifiScanner: listener cannot be found
12-12 09:14:49.157 13498 13498 E wpa_supplicant: PNO: In assoc process
12-12 09:14:49.158  4982  5415 E SupplicantWifiScannerImpl: PNO state change to true failed
12-12 09:14:49.159  4982  5415 E SupplicantWifiScannerImpl: Failed to start PNO scan
12-12 09:14:49.163  4982  5412 E WifiConnectivityManager: PnoScanListener onFailure: reason: -1 description: pno scan failed
12-12 09:14:54.167  4982  5412 E WifiScanner: listener cannot be found
12-12 09:14:54.176 13498 13498 E wpa_supplicant: PNO: In assoc process
12-12 09:14:54.177  4982  5415 E SupplicantWifiScannerImpl: PNO state change to true failed
12-12 09:14:54.177  4982  5415 E SupplicantWifiScannerImpl: Failed to start PNO scan
12-12 09:14:54.179  4982  5412 E WifiConnectivityManager: PnoScanListener onFailure: reason: -1 description: pno scan failed
12-12 09:14:59.185  4982  5412 E WifiScanner: listener cannot be found
12-12 09:14:59.196 13498 13498 E wpa_supplicant: PNO: In assoc process
12-12 09:14:59.197  4982  5415 E SupplicantWifiScannerImpl: PNO state change to true failed
12-12 09:14:59.197  4982  5415 E SupplicantWifiScannerImpl: Failed to start PNO scan
12-12 09:14:59.201  4982  5412 E WifiConnectivityManager: PnoScanListener onFailure: reason: -1 description: pno scan failed
12-12 09:15:01.502  4982  5412 E WifiHAL : Failed to register get pkt fate response; result = -22
12-12 09:15:01.503  4982  5412 E WifiNative-HAL: getTxPktFatesNative returned -22
12-12 09:15:01.504  4982  5412 E WifiHAL : Failed to register get pkt fate response; result = -22
12-12 09:15:01.504  4982  5412 E WifiNative-HAL: getRxPktFatesNative returned -22
12-12 09:15:03.497  4982  5412 E WifiHAL : Failed to register get pkt fate response; result = -22
12-12 09:15:03.497  4982  5412 E WifiNative-HAL: getTxPktFatesNative returned -22
12-12 09:15:03.497  4982  5412 E WifiHAL : Failed to register get pkt fate response; result = -22
12-12 09:15:03.498  4982  5412 E WifiNative-HAL: getRxPktFatesNative returned -22
12-12 09:15:04.207  4982  5412 E WifiScanner: listener cannot be found

**Comment by thestinger** [comment]
Can you try with MAC randomization disabled? In Settings -> Wireless & networks -> More. Might need to reboot after. It's probably not the cause but it's one of the few things that we change related to this.

There's no toggle for scanning MAC randomization (it's always enabled where supported i.e. 6P and 9) but it's even less likely to be related to that.

**Comment by zongo** [comment]
Disable MAC randomization 
Rebooted 
Tried to connect to same EAP network and failed as before. 
Logs attached

[log2.txt](https://github.com/copperhead/bugtracker/files/645546/log2.txt)

**Comment by zongo** [comment]
Set MAC randomization again. 
Rebooted the device.
Tried to connect to WPA2  a couple of times and failed with authentication error. 
Enabled USB debug mode and tried to connect to WPA2 network and successfully connected with same password as before. 
Expected result: Expect to connect the first time with no delays and no error on WPA2. 
I do not know if enabling USB debug made any difference. 
Logs attached. 
[log3.txt](https://github.com/copperhead/bugtracker/files/645568/log3.txt)

**Comment by zongo** [comment]
Could that be an issue ? 
https://code.google.com/p/android/issues/detail?id=211134
Would like to be able to change Wi-Fi frequency band

**Comment by zongo** [comment]
Different issue but linked to problem connecting to Wifi WPA2 and possibly EAP network. Sorry for the issue being so confusing but I did not experience this under Marshmallow. 
When trying to connect to AP WPA2, it is not possible as AP is blacklisted. Is this an expected behaviour ? 

12-12 13:53:39.691  4969  5404 E WifiQualifiedNetworkSelector:: zongo:80:49:71:16:00:37 is in blacklist.
12-12 13:54:40.428  4969  5404 E WifiQualifiedNetworkSelector:: zongo:80:49:71:16:00:37 is in blacklist.
12-12 13:55:17.615  4969  5404 E WifiQualifiedNetworkSelector:: zongo:80:49:71:16:00:37 is in blacklist.
12-12 13:55:27.643  4969  5404 E WifiQualifiedNetworkSelector:: zongo:80:49:71:16:00:37 is in blacklist.
12-12 13:55:57.656  4969  5404 E WifiQualifiedNetworkSelector:: zongo:80:49:71:16:00:37 is in blacklist.
12-12 13:56:07.655  4969  5404 E WifiQualifiedNetworkSelector:: zongo:80:49:71:16:00:37 is in blacklist.

**Comment by zongo** [comment]
Solved TLS version issue between Client and Radio. Update Radius to accept TLS1.2 and connection is happening. This is for Wireless AP using EAP. 
Apologies for the trouble.

**Comment by zongo** [comment]
Solved
