### ISSUE TITLE
wifi disconnects

### ISSUE THREAD

**Issue by canary5** [copperhead/bugtracker#531]
Just installed latest 12.12.16 build. Device 5x. Have wifi discinnexted every few mins.
http://pastebin.com/FjsTkTVb

**Comment by thestinger** [comment]
This appears to be an upstream problem. CopperheadOS doesn't make any relevant changes.

**Comment by b52** [comment]
I have similar issues with certain wifis as well.

**Comment by thestinger** [comment]
This is specific to the 5X among the supported devices but it would be interesting to see if it occurs on the Pixel and Pixel XL which have a WiFi card from the same family and a different version of the same qcacld-2.0 driver.

**Comment by d0s1s** [comment]
Hi,
I've been testing a personal build with this kernel https://github.com/DirtyUnicorns/android_kernel_lge_bullhead/commits/n7x and wifi problems are gone. Could you take a look to this source?
Thanks.
Best regards.

**Comment by thestinger** [comment]
Nope, no time to spend on this. If you want problems to be fixed, you need to do the work.

**Comment by thestinger** [comment]
Qualcomm / Google may get around to fixing it soon. I'm not devoting any time to fixing their horrid out-of-tree WiFi driver. It has zero chance of ever landing upstream and I'd rather just wait it out, similar to all of the other issues with that driver like it breaking when the MAC is changed preventing MAC randomization on those devices.

**Comment by d0s1s** [comment]
Hi,
In my case I fix the problem setting "Enable Unscheduled Automatic Power Save delivery" in Unifi Ubiquiti AC AP (only affects the 5Ghz channel).
Anyway it's not a CopperheadOS specific bug, it's a stock bug. I will try to debug the issue in my free time and find the commit in DirtyUnicorns kernel source that fixes it.
Best regards.

**Comment by thestinger** [comment]
It might be a missing commit resulting in it not being broken. This used to work until perhaps 7.1.1.

**Comment by thestinger** [comment]
Closing in favour of https://github.com/copperhead/bugtracker/issues/568 which is more generic, as was done for the other upstream qcacld-2.0 bug.
