### ISSUE TITLE
DNS-over-TLS (RFC7858)

### ISSUE THREAD

**Issue by spacekitteh** [copperhead/bugtracker#536]
[RFC7858](https://tools.ietf.org/html/rfc7858)

From my limited understanding, Bionic appears to implement Android's DNS lookup mechanism. Thus it must be investigated if this is even possible without separating out [the libresolv-ish parts from libc](https://github.com/android/platform_bionic/tree/master/libc/dns) in order to link to a TLS lib. 

[Here seems to be the meat of the implementation](https://github.com/android/platform_bionic/blob/master/libc/dns/net/getaddrinfo.c).

Some items of interest:

* [`android_getaddrinfo_proxy`](https://github.com/android/platform_bionic/blob/master/libc/dns/net/getaddrinfo.c#L403) for doing DNS lookup over a proxy
* [Linux kernel module for DTLS](https://github.com/ktls/af_ktls)

[Related upstream issue/feature request](https://code.google.com/p/android/issues/detail?id=230562)

**Comment by thestinger** [comment]
It definitely shouldn't involve code in the kernel.

**Comment by spacekitteh** [comment]
Indeed, it is merely an example of a complete-ish implementation at a low level. Do the external deps use Bionic for their libc as well?

**Comment by thestinger** [comment]
Everything Android uses Bionic. If you wanted to bundle BoringSSL into Bionic you could.

**Comment by spacekitteh** [comment]
As a workaround in the meantime, perhaps including a simple dns-over-tls-supporting resolver app and forward all requests to it might be acceptable?

**Comment by thestinger** [comment]
It can likely just be done in netd because DNS requests are likely already proxied to netd from everywhere else by default and preventing apps from shooting themselves in the foot by going out of the way to change that isn't necessary.

**Comment by thestinger** [comment]
Note the NetdClient loading in Bionic.

**Comment by stensonb** [comment]
fair warning: I know nothing about android development or the android ecosystem...

why not use [dnscrypt-proxy](https://dnscrypt.org/), and a local dns cache?

**Comment by spacekitteh** [comment]
Dnscrypt is only for authentication, not privacy.

**Comment by thestinger** [comment]
They might be interested in this upstream which would be a way of getting it done, not sure. Since DNS queries are usually followed by connecting to the resolved IP, it won't hide much other than hosts with multiple / many hostnames and in terms of authentication DNS should be untrusted either way. Authentication might be more useful in terms of mitigating denial of service a compromised DNS server, by falling back to a different server if authentication fails, but it's a marginal benefit.

**Comment by spacekitteh** [comment]
It is important for anonymity, like when using VPNs and Tor, for example.

**Comment by thestinger** [comment]
The DNS should be going over the VPN / Tor already.

**Comment by spacekitteh** [comment]
True enough

**Comment by thestinger** [comment]
This is being implemented upstream so we'll just wait for it. It's a very low priority for us since the IP addresses are still leaked and TLS SNI leaks the domain being requested so there's not much really being hidden.

**Comment by thestinger** [comment]
https://android-review.googlesource.com/#/q/topic:dns-dev-opt+(status:open+OR+status:merged)
