### ISSUE TITLE
Adding nightime dim and color shift feature

### ISSUE THREAD

**Issue by LibreAnne** [copperhead/bugtracker#537]
Hello. A security minded friend suggested I use Copperhead instead of Cyanogenmod as that one is not too safe he said. I love copperhead so far. Thank you for making it. But the one thing I really miss from Cyanogenmod was the ability for the screen to shift to different color temperature at night.

I know on Linux this app is called Redshift, but there does not seem to be an app in  F-Droid with this functionality! Is it possible to add this to Copperhead OS?

**Comment by thestinger** [comment]
No, it's not going to be implemented. It will be included via a hardware accelerated implementation of the Pixel and Pixel XL along with later devices.

**Comment by thestinger** [comment]
Apps implementing this via an overlay will work fine on CopperheadOS but it's not going to be implemented in the OS and this isn't a support platform.

**Comment by LibreAnne** [comment]
That was a feature request not asking for support. The feature seemed built in to Cyanogenmod which is why I asked as I thought it would be done similarly here. I am sorry I don't understand the technicality enough to properly describe it.

**Comment by thestinger** [comment]
I just couldn't tell if you were asking for it to be included or if you wanted to know if apps implementing it will work. CopperheadOS on the Pixel / Pixel XL and later will have this via hardware support so it'll be included, but not for the 5X/6P where Google found driver support to be too buggy so it could only be done via a software overlay and we don't want that.

**Comment by zongo** [comment]
As an example, I used f-lux with custom rom which worked properly with
root. Giving root is what I am now trying to avoid.

**Comment by LibreAnne** [comment]
@thestinger Ok. Thank you for explaining.
