### ISSUE TITLE
disable bluetooth by default

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#540]

**Comment by e-lektryk** [comment]
I was supprised when intalled copperhead OS on fresh phone and after installation Bluetooth was enabled. I hope this is exact what I would like to report, if not please consider this for next enhancement.

**Comment by thestinger** [comment]
If you want it to happen soon, please submit a patch. Asking for issues to be prioritized doesn't accomplish anything.

**Comment by thestinger** [comment]
Implemented by https://github.com/CopperheadOS/platform_frameworks_base/pull/4.
