### ISSUE TITLE
CopperheadOS wallpaper

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#542]
There should be a custom wallpaper instead of the AOSP defaults. It needs to properly support all of the supported screen sizes and we need to have the ability to expand it to other sizes in the future. It's not clear exactly what we want yet. Using the logo seemed nice but it handles moving between workspaces and screen rotation poorly. It would be better to have a wallpaper not based around having something in the centre.

**Comment by xmr-eric** [comment]
It could simply be the COS boot logo. That looks good enough to start with until a real designer comes along, and would be quick to implement.

**Comment by thestinger** [comment]
I won't be working on this. I have a lot of important stuff to do.

**Comment by reclaimer** [comment]
The ‘glitchy’ logo shown as the device starts would be perfect! I don't mind making the images, if you send me the animation for the logo.

**Comment by bjoernfan** [comment]
@kxpvcr It looks like it is available here: https://github.com/copperhead/branding/blob/master/copperhead_vector.svg

**Comment by thestinger** [comment]
This is implemented for most devices now, just not the Pixel 2 XL. It can be improved and extended to the Pixel 2 XL later.
