### ISSUE TITLE
Secure Voice Calling App? Orbot? Orwall?

### ISSUE THREAD

**Issue by BobsUncle** [copperhead/bugtracker#545]
What voice app can I use on copperhead that provides same gold standard level of security as Signal? Preferably something where I can setup the server and host. 

The documentation only provides recommendations for apps that are text based. Any suggestions please?

**Comment by thestinger** [comment]
This issue tracker isn't used as a support platform, try https://www.reddit.com/r/CopperheadOS/ instead.
