### ISSUE TITLE
Randomize number of "dots" per character on password/pin unlock screen

### ISSUE THREAD

**Issue by e-lektryk** [copperhead/bugtracker#547]
When someone watch when owner type pin/password could see what is password lenght. This could ease password guessing.

**Comment by thestinger** [comment]
I don't want to implement this. If someone is watching the password being typed, well... they are watching the password being typed. I don't think the number of dots will be what they are aiming to watch and it doesn't all fit on one screen for a good password.

**Comment by e-lektryk** [comment]
To clarify, when you type password, you expect some kind of feedback every key, I cannot imagine person counting number of "dots" on screen to double check the password lenght. Especially when password is quite long.
