### ISSUE TITLE
Animated circles around digits could reveal PIN

### ISSUE THREAD

**Issue by e-lektryk** [copperhead/bugtracker#548]
Even when user types password quick, animated circles around selected digits can show the exact digit which was typed to anyone secretly watching user.

**Comment by thestinger** [comment]
Not planning to change the keyboard UX, particularly if it reduces the usability of strong passphrases.

**Comment by e-lektryk** [comment]
One more comment, January or February update has even worsen situation. Now up to two digits are visible for a moment on logon screen.

**Comment by thestinger** [comment]
There's a setting Security -> Show passwords, if that's what you mean. Turn it off.
