### ISSUE TITLE
flash-all.bat does not have correct path to fastboot tool

### ISSUE THREAD

**Issue by e-lektryk** [copperhead/bugtracker#551]
For advanced user change of this .bat file is trivial, but for begginers it does not work just from the box.
Tested angler-factory-2016.12.25.22.27.39.tar.xz with android-studio-bundle-145.3537739-windows.exe

**Comment by thestinger** [comment]
It's not our script and we don't control Android Studio. Talk to Google. For beginners, we sell devices with the OS preloaded. No interest in making the installation process even easier than it already is. It's far easier than installing even beginner-friendly distributions like Ubuntu already. There are plenty of instructions covering flashing stock factory images around the internet too, and that's identical to CopperheadOS.
