### ISSUE TITLE
[question] Should I install updates 2016.X.X if I already have 2017.01.X?

### ISSUE THREAD

**Issue by 1337hax** [copperhead/bugtracker#553]
I have already installed update 2017.01.04.(...). However, on System Updates menu I see available updates 2016.12.25 and 2016.12.7 labelled as "New" and available to download. When this 2016.X were released, I have not applied them, because I was in foreign country and didn't wanted to risk that upgrade would damage something :)

Should I apply them or would it mean downgrading to previous version?

**Comment by darknetj** [comment]
@1337hax don't worry about previous versions - only update to the newest

**Comment by 1337hax** [comment]
OK, thanks for quick response! I will close the issue.
