### ISSUE TITLE
webview crash

### ISSUE THREAD

**Issue by zongo** [copperhead/bugtracker#555]
nexus 6P 
build N4F26J2017.01.04.05.44.59
Issue: Webview crashing intermittently when on amazon seeing the content of basket and exiting to pay. Issue happens inside Amazon app. 
Issue is not reproducible every time.  full logs attached.

01-08 15:23:59.516 30095 30130 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 30130 (Chrome_FileThre)
01-08 15:23:59.520   374   374 W         : debuggerd: handling request: pid=30095 uid=10096 gid=10096 tid=30130
01-08 15:23:59.791  1165  1165 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-08 15:23:59.791  1165  1165 F DEBUG   : Build fingerprint: 'Android/aosp_angler/angler:7.1.1/N4F26J/2017.01.04.05.44.59:user/release-keys'
01-08 15:23:59.791  1165  1165 F DEBUG   : Revision: '0'
01-08 15:23:59.791  1165  1165 F DEBUG   : ABI: 'arm'
01-08 15:23:59.792  1165  1165 F DEBUG   : pid: 30095, tid: 30130, name: Chrome_FileThre  >>> com.amazon.mShop.android.shopping <<<
01-08 15:23:59.792  1165  1165 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
01-08 15:23:59.811  1165  1165 F DEBUG   : Abort message: '[FATAL:crash_micro_dump_manager_android.cc(81)] Renderer process crash detected (code 11). Terminating browser.
01-08 15:23:59.811  1165  1165 F DEBUG   : '
01-08 15:23:59.811  1165  1165 F DEBUG   :     r0 00000000  r1 000075b2  r2 00000006  r3 00000008
01-08 15:23:59.811  1165  1165 F DEBUG   :     r4 d607205c  r5 00000006  r6 d6072000  r7 0000010c
01-08 15:23:59.811  1165  1165 F DEBUG   :     r8 eb9c7000  r9 d5de6f34  sl 00000000  fp d9990480
01-08 15:23:59.811  1165  1165 F DEBUG   :     ip 00000004  sp d5de6a80  lr eb99e0a7  pc eb9a0940  cpsr 200f0010
01-08 15:23:59.835  1165  1165 F DEBUG   : 
01-08 15:23:59.835  1165  1165 F DEBUG   : backtrace:
01-08 15:23:59.836  1165  1165 F DEBUG   :     #00 pc 0004f940  /system/lib/libc.so (tgkill+12)
01-08 15:23:59.836  1165  1165 F DEBUG   :     #01 pc 0004d0a3  /system/lib/libc.so (pthread_kill+34)
01-08 15:23:59.836  1165  1165 F DEBUG   :     #02 pc 0001d951  /system/lib/libc.so (raise+10)
01-08 15:23:59.836  1165  1165 F DEBUG   :     #03 pc 000192cf  /system/lib/libc.so (__libc_android_abort+36)
01-08 15:23:59.836  1165  1165 F DEBUG   :     #04 pc 000166ec  /system/lib/libc.so (abort+4)
01-08 15:23:59.836  1165  1165 F DEBUG   :     #05 pc 002b6151  /system/app/webview/webview.apk (offset 0x55c1000)
01-08 15:23:59.836  1165  1165 F DEBUG   :     #06 pc 002c30a1  /system/app/webview/webview.apk (offset 0x55c1000)
01-08 15:23:59.836  1165  1165 F DEBUG   :     #07 pc 013e5ae1  /system/app/webview/webview.apk (offset 0x55c1000)
01-08 15:23:59.836  1165  1165 F DEBUG   :     #08 pc 002b6beb  /system/app/webview/webview.apk (offset 0x55c1000)
01-08 15:23:59.836  1165  1165 F DEBUG   :     #09 pc 002c703b  /system/app/webview/webview.apk (offset 0x55c1000)
01-08 15:23:59.836  1165  1165 F DEBUG   :     #10 pc 002c757d  /system/app/webview/webview.apk (offset 0x55c1000)
01-08 15:23:59.836  1165  1165 F DEBUG   :     #11 pc 002c781b  /system/app/webview/webview.apk (offset 0x55c1000)
01-08 15:23:59.836  1165  1165 F DEBUG   :     #12 pc 002c8781  /system/app/webview/webview.apk (offset 0x55c1000)
01-08 15:23:59.836  1165  1165 F DEBUG   :     #13 pc 002d5f97  /system/app/webview/webview.apk (offset 0x55c1000)
01-08 15:23:59.836  1165  1165 F DEBUG   :     #14 pc 00987097  /system/app/webview/webview.apk (offset 0x55c1000)
01-08 15:23:59.836  1165  1165 F DEBUG   :     #15 pc 0098716f  /system/app/webview/webview.apk (offset 0x55c1000)
01-08 15:23:59.836  1165  1165 F DEBUG   :     #16 pc 002ea3cd  /system/app/webview/webview.apk (offset 0x55c1000)
01-08 15:23:59.836  1165  1165 F DEBUG   :     #17 pc 002e6e33  /system/app/webview/webview.apk (offset 0x55c1000)
01-08 15:23:59.836  1165  1165 F DEBUG   :     #18 pc 0004caaf  /system/lib/libc.so (_ZL15__pthread_startPv+22)
01-08 15:23:59.837  1165  1165 F DEBUG   :     #19 pc 00019ca1  /system/lib/libc.so (__start_thread+6)

[logcat.txt](https://github.com/copperhead/bugtracker/files/692176/logcat.txt)

**Comment by thestinger** [comment]
Likely just caused by either enabling the multiprocess WebView or an upstream memory corruption bug. Someone will need to narrow down the cause. I need clear evidence that it's a CopperheadOS bug.

**Comment by thestinger** [comment]
Does this still happen with Chromium 56?

**Comment by zongo** [comment]
Issue has not appeared under chromium 56. I think it can be closed now.
