### ISSUE TITLE
associated MAC randomization with the qcacld-2.0 driver (Qualcomm Atheros)

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#556]
This is the WiFi driver used on the Nexus 5X, Pixel and Pixel XL. In the past, Nexus devices all used Broadcom WiFi where MAC randomization worked properly. Nexus 6P and Nexus 9 use Broadcom.

Full MAC randomization completely breaks WiFi authentication and had to be disabled.

Scanning MAC randomization mostly works, but it occasionally triggers the same symptom, apparently during sleep - but not always. It has also been disabled.

**Comment by thestinger** [comment]
Scanning MAC randomization with proper firmware/driver support to avoid non-MAC identifiers is coming in Android O for Qualcomm WiFi on the 5X and Pixels: https://android-developers.googleblog.com/2017/04/changes-to-device-identifiers-in.html.

**Comment by thestinger** [comment]
Someone apparently implemented this via WCNSS but they didn't seem willing to publish code for it.

**Comment by ScottyBauer** [comment]
Where did you hear about that

**Comment by thestinger** [comment]
There's apparently a /sys interface able to set the MAC address (with root).

**Comment by thestinger** [comment]
@ScottyBauer See https://github.com/saleemrashid/changemac.
