### ISSUE TITLE
The screen is flickering in boot animation

### ISSUE THREAD

**Issue by d0s1s** [copperhead/bugtracker#562]
Hi,

I want to report an issue on Nexus 5X: The screen is flickering in CopperheadOS boot animation.

Currently with latest N4F26J.2017.01.17.23.45.11 release (in previous 2017 release CopperheadOS boot animation was flickering too).

Best regards.

**Comment by thestinger** [comment]
The boot animation is meant to be that way: https://en.wikipedia.org/wiki/Glitch_art.

**Comment by d0s1s** [comment]
O.K.
Thanks.
