### ISSUE TITLE
Nexus 6p looses mobile connectivity, though Internet is still working

### ISSUE THREAD

**Issue by vanitasvitae** [copperhead/bugtracker#564]
Hi
Im running latest CopperheadOS on my Nexus 6p.
The phone often loses mobile connectivity, meaning I can neither call people, nor can they call me (not available). Same goes for SMS. Mobile internet is working without a flaw though.

Because I don't often call other people, I often only recognize that the connection dropped after several days. I should note, that the signal indicator on the top right looks as usual, so no indication about missing connection there. Toggling airplane mode on and off resolves the issue, until the connection drops again (after some hours I guess)

Is this a problem with my phone, the OS or my sim card provider?

**Comment by thestinger** [comment]
That definitely seems like an issue with the mobile provider.

**Comment by kittenpirate** [comment]
What carrier are you using?

**Comment by vanitasvitae** [comment]
@kittenpirate Drillisch
