### ISSUE TITLE
Chromium showing really tiny text on sites after last update

### ISSUE THREAD

**Issue by craftyguy** [copperhead/bugtracker#573]
I see ultra small text on websites after the last update

![screenshot_20170129-194322](https://cloud.githubusercontent.com/assets/1474209/22411744/e50fa50e-e65b-11e6-9c56-f37afb5225f2.png)

**Comment by thestinger** [comment]
You can work around this by clearing data. Chromium isn't maintained by us and this isn't caused by one of our changes. It's an upstream issue.

**Comment by craftyguy** [comment]
Do you have a link to the upstream issue?

**Comment by thestinger** [comment]
Nope, but perhaps they'll fix it before they officially release Chrome 56 for Android rather than only the WebView.

**Comment by marmeladema** [comment]
I had the same problem and clearing only Chromium cache did not solved it.
You actually have to clear **all** datas.
Thanks for the quick fix anyway :)

**Comment by craftyguy** [comment]
> You actually have to clear all datas.

Right. Which is silly requiring users to experience data loss to resolve an issue. 

> Nope, but perhaps they'll fix it before they officially release Chrome 56 for Android rather than only the WebView.

 Do you know if this issue is caused by running a newer webview with a different chromium version?

**Comment by thestinger** [comment]
> Do you know if this issue is caused by running a newer webview with a different chromium version?

It's not related to the WebView. It's an upstream Chromium bug.

**Comment by craftyguy** [comment]
How do you know if you don't know of the actual upstream bug?

**Comment by thestinger** [comment]
The fact that it occurs with an unmodified build of Chromium 56 on stock Android.
