### ISSUE TITLE
add notification to reboot when A/B updates finish installation

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#574]

**Comment by thestinger** [comment]
Not planning on enhancing the old update app further. CopperheadOS lacks the resources to maintain it, so there's only going to be the legacy update in the current state and a new simplified updater for A/B devices only without a user interface beyond a notification when updates are complete to reboot.

**Comment by arlolra** [comment]
Did you close this by mistake?

**Comment by thestinger** [comment]
No, it's closed because it was filed about the old updater.

**Comment by arlolra** [comment]
Hmm, the title and labels are throwing me off then.

**Comment by thestinger** [comment]
There's an old updater where initial support for A/B updates was added but it's being replaced by a new updater because it was determined that the old updater is a hopeless cause.

**Comment by arlolra** [comment]
Thanks for clarifying ... and sorry for questioning.
