### ISSUE TITLE
Silent sms protection

### ISSUE THREAD

**Issue by root-io** [copperhead/bugtracker#575]
Would be nice if there is some kind of protection or detection against silent sms

**Comment by bunsim** [comment]
Is this truly a threat though? Seems like it's going to be pretty trivial anyway for the cell carrier to track you down, silent SMS or not. Adding minimally useful security theater would probably be worse than doing nothing, as it increases the attack surface even if just by a little bit.

**Comment by thestinger** [comment]
There's no meaningful 'protection' against this beyond displaying / storing them as regular messages. I wouldn't mind doing that if it can be done without enabling modem diagnostics, etc. but rather just wiring it up to be treated more like a regular SMS. I don't plan on devoting any time to this though, and I'm not sure it would really accomplish much so the patch would need to be very minimal / uninvasive. I think that should be the case as long as the functionality doesn't require modem diag.

**Comment by thestinger** [comment]
Sending a non-silent SMS message with spam accomplishes the same thing, and SMS spam is very real. I don't really see the point especially when there are other ways of accomplishing the same thing without SMS. If you don't want your carrier to know where you are, turn on airplane mode which still allows you to use WiFi.
