### ISSUE TITLE
flash-all.sh needs re-enabling flashing after every reboot-bootloader

### ISSUE THREAD

**Issue by gagzkrim** [copperhead/bugtracker#576]
Hi,

I have just bought a nexus 5X and tried to install CopperHead on it, and had little trouble understanding why it wouldn't work.
0215011db6654d8f
In the end I figured I would do the things in flash-all.sh, adding `fastboot flashing unlock` after every single `fastboot reboot-bootloader`, and it worked :)

Maybe that could be added somehow in the process, or maybe I did something in the wrong way?

I followed https://copperhead.co/android/docs/install

Here are some info of my phone, now that copperhead is installed :
> PRODUCT_NAME - bullhead
> VARIANT - bullhead LGH791 16GB
> HW VERSION - rev_1.0
> BOOTLOADER VERSION - BHZ11h
> BASEBAND VERSION - M8994F-2.6.36.2.20

And here are the messages I got before I "found" the trick :

> $ ./flash-all.sh
> target reported max download size of 536870912 bytes
> sending 'bootloader' (4603 KB)...
> OKAY [  0.291s]
> writing 'bootloader'...
> OKAY [  0.194s]
> finished. total time: 0.485s
> rebooting into bootloader...
> OKAY [  0.020s]
> finished. total time: 0.321s
> target reported max download size of 536870912 bytes
> sending 'radio' (56614 KB)...
> OKAY [  2.708s]
> writing 'radio'...
> FAILED (remote: device is locked. Cannot flash images)
> finished. total time: 2.723s
> rebooting into bootloader...
> OKAY [  0.020s]
> finished. total time: 0.271s
> target reported max download size of 536870912 bytes
> archive does not contain 'boot.sig'
> archive does not contain 'recovery.sig'
> archive does not contain 'system.sig'
> archive does not contain 'vendor.sig'
> wiping userdata...
> Creating filesystem with parameters:
>     Size: 11773390848
>     Block size: 4096
>     Blocks per group: 32768
>     Inodes per group: 8176
>     Inode size: 256
>     Journal blocks: 32768
>     Label: 
>     Blocks: 2874363
>     Block groups: 88
>     Reserved block group size: 703
> Created filesystem with 11/719488 inodes and 84965/2874363 blocks
> wiping cache...
> Creating filesystem with parameters:
>     Size: 100663296
>     Block size: 4096
>     Blocks per group: 32768
>     Inodes per group: 6144
>     Inode size: 256
>     Journal blocks: 1024
>     Label: 
>     Blocks: 24576
>     Block groups: 1
>     Reserved block group size: 7
> Created filesystem with 11/6144 inodes and 1422/24576 blocks
> --------------------------------------------
> Bootloader Version...: BHZ11h
> Baseband Version.....: M8994F-2.6.33.2.14
> Serial Number........: xxxxxxxxxxxxxxxx
> --------------------------------------------
> checking product...
> OKAY [  0.020s]
> checking version-bootloader...
> OKAY [  0.020s]
> checking version-baseband...
> FAILED
> 
> Device version-baseband is 'M8994F-2.6.33.2.14'.
> Update requires 'M8994F-2.6.36.2.20'.
> 
> finished. total time: 0.129s

thanks for the job :)

**Comment by thestinger** [comment]
This isn't required, you're doing something wrong like using an incompatible / old fastboot.

**Comment by thestinger** [comment]
The CopperheadOS flash-all.sh script is *identical* to the one used by Google's factory images. It's not our script and works for everyone else.

**Comment by gagzkrim** [comment]
Hi,

I use the fastboot and adb from platform-tools, downloaded from google's
website :
`$ ./fastboot --version
fastboot version 0e9850346394-android
$ ./adb version
Android Debug Bridge version 1.0.36
Revision 0e9850346394-android`

Thing is that after each `reboot-bootloader` the device is "flashing
locked" again, I don't know why though!


Thank you!
