### ISSUE TITLE
Chromium 56 from January/February update does not render pages correctly (small font)

### ISSUE THREAD

**Issue by e-lektryk** [copperhead/bugtracker#578]
After January/February update, lots of webpages (i.e duckduckgo) does not rendere correctly. Some fonts on the webpage has height of 1-2 pixels making it totally unreadable. This looks like common Chrome/Chromium issue, I have seen many people reporting this issue since 2014. Since I do not see option to update chromium independently, please revert chromium in next update.

**Comment by thestinger** [comment]
> After January/February update, lots of webpages (i.e duckduckgo) does not rendere correctly. Some fonts on the webpage has height of 1-2 pixels making it totally unreadable.

You can work around the problem by backing up whatever data you have in Chromium and then using Settings -> Apps -> Chromium -> Data -> Clear data.

> Since I do not see option to update chromium independently, please revert chromium in next update.

That's not going to happen, older versions are not secure. It's mandatory to keep it updated.

**Comment by e-lektryk** [comment]
Hi removing all data from settings->apps helped. Previously I have tried only removing all data from Chromium menu, without luck.
