### ISSUE TITLE
screen turns black when dialing a call; issue with proximity sensor with screen protector

### ISSUE THREAD

**Issue by kxp6500** [copperhead/bugtracker#579]
Hello, I am a non-technical new user of Copperhead on a Nexus 6P. If my posts don't belong here, I apologize. I have an issue with the screen turning black when I make a call. Researching the issue, it is a common bug related to the proximity sensor and having a screen protector. Someone made a patch [https://forum.xda-developers.com/nexus-6/development/mod-fix-proximity-sensor-5-1-rom-t3069031](url), but I am not sure if I can or should use it. Could the developers of Copperhead incorporate this patch into the operating system directly? Maybe it already is in there, and I just have to find a different screen protector, or do without. The issue is discussed in detail at [https://productforums.google.com/forum/#!category-topic/nexus/nexus-6/mIRwBP4Hx_Y](url). Thanks.

**Comment by thestinger** [comment]
I don't want to change the standard sensitivity. Screen protectors aren't something that I want to worry about. These kinds of non-security-related decisions are entirely upstream Android decisions, unless there's something tied to us not having Play Services which isn't the case here.

**Comment by kxp6500** [comment]
I realize that you are a programmer and not a customer service or marketing person, but I gotta tell you, I found the tone of your response unnecessarily rude.

I solved the problem on my own. The screen protector I had initially bought didn't have a notch cut out for the proximity sensor. I bought a new one with the notch, and everything is fine. At the time, I was not aware that the defective screen protector was the cause of my issue.

**Comment by thestinger** [comment]
I don't think it's rude to say an issue is out-of-scope. Google tuned this value based on testing and we aren't in a position to second guess their chosen compromise. These kinds of changes aren't in-scope for CopperheadOS. Only bugs uncovered / caused by our changes are in-scope for this bug tracker. If it's something that impacts stock Android, it's not really in-scope.
