### ISSUE TITLE
“waiting for any device” when attempting ‘flash-all.sh’

### ISSUE THREAD

**Issue by bignose-debian** [copperhead/bugtracker#581]
Following the instructions at https://copperhead.co/android/docs/install I am attempting to run ‘./flash-all.sh’. The command hangs with:

```
$ ./flash-all.sh
< waiting for any device >
```

This is a Nexus 5X, recovery is Team Win, the device is OEM unlocked.

Sending files (e.g. CyanogenMod) to the device with ‘adb’ works fine.

What have I missed in the instructions, to allow me to continue?

**Comment by thestinger** [comment]
The issue tracker isn't going to be used for support.

**Comment by thestinger** [comment]
https://www.reddit.com/r/copperheados

**Comment by bignose-debian** [comment]
Which issue tracker is used for support requests?

**Comment by bignose-debian** [comment]
Also, that contradicts the instructions:

> Bugs (or feature requests) should be reported to the issue tracker on GitHub.

https://copperhead.co/android/docs/install

**Comment by thestinger** [comment]
It's not a bug or a feature request. It's a support request, and we only provide support to customers now. If you want support without paying for it then you need to ask the community in https://www.reddit.com/r/copperheados or IRC.
