### ISSUE TITLE
System update should warn users with low battery

### ISSUE THREAD

**Issue by anantshri** [copperhead/bugtracker#582]
I suppose there should be a warning to users with <25% battery and not plugged to charging that the process would be better run with >25% power to avoid complete shutdown during update process.

I have not faced it but i suppose if the update process is interrupted then it can render the device bricked.

**Comment by thestinger** [comment]
Note that updates are going to work differently with the new update infrastructure. There's no reboot and the device shutting off while it's happening isn't a problem.

**Comment by anantshri** [comment]
for A/B updates does existing users on older devices 5x,6p etc need to do any additional step.

**Comment by thestinger** [comment]
A/B updates are only for new devices.

**Comment by thestinger** [comment]
Not planning on enhancing the old update app further. CopperheadOS lacks the resources to maintain it, so there's only going to be the legacy update in the current state and a new simplified updater for A/B devices only without a user interface beyond a notification when updates are complete to reboot.
