### ISSUE TITLE
Danish text correction

### ISSUE THREAD

**Issue by knutztar** [copperhead/bugtracker#583]
Is it possible to include Danish as a text correction language for AOSP keyboard? 
I can see that multiple languages is preinstalled under Add-On dictionaries, but Danish is not one of them.

**Comment by thestinger** [comment]
Extending the AOSP keyboard isn't in scope for CopperheadOS, but useful uninvasive patches to it will be accepted. I don't know what has to be done to add a language and it's not something that Copperhead is going to work on. A patch doing it with a clear and reproducible explanation of how the dictionary was added could be merged.
