### ISSUE TITLE
nexus 5x screen blank during call.

### ISSUE THREAD

**Issue by anantshri** [copperhead/bugtracker#584]
During entire call from dialing a number, screen never returns back till the other party cuts the call and power key is pressed again.
both when recieving a call and while dialing out.

Note: i have not checked at AOSP if its an upstream bug, also not in a position to reflash AOSP to verify right now.

**Comment by thestinger** [comment]
Sounds like your proximity sensor is broken or blocked. Do you have a screen protector attached?

**Comment by anantshri** [comment]
I have screen protector but the proximity sensor is not blocked. Will investigate further on this.

**Comment by thestinger** [comment]
It doesn't cover the proximity sensor? It might see the screen protector.

**Comment by anantshri** [comment]
it looks like it was indeed my screen protector. Thanks for the tip issue resolved for now by removing screenguard.
