### ISSUE TITLE
Nexus 5x Flashlght not working?

### ISSUE THREAD

**Issue by n3xus5x** [copperhead/bugtracker#597]
the flashlight does not turn on when pressing the torch from drop down menu. flash works in camera and video recording. same issue on 2 seperate nexus 5x with latest update of copperhead OS

**Comment by thestinger** [comment]
It works here. Are you using CopperheadOS unmodified with a locked bootloader?

**Comment by thestinger** [comment]
I need information in order to proceed with this.

**Comment by n3xus5x** [comment]
Sorry late reply. yes im using Unmodified CopperheadOS with locked boot loader fingerprint: 0AA1-7043-4D5F on boot. (both Devices)

im not sure if there is anyway to see a log as to what happens when i press the flashlight?

Also installed multiple flashlight apps also cant trigger the light on. Camera apps do work. i can use Open Camera with flash on with no issues. 
Supa head scratching moment any advice on how to diagnose?

**Comment by thestinger** [comment]
Can you update to the latest release if you haven't already, and then try there?

**Comment by n3xus5x** [comment]
ok updating now to 2017.02.23.07.20.31

**Comment by n3xus5x** [comment]
Amazing update Fixed it!! thanks

**Comment by thestinger** [comment]
Try rebooting though, and see if it shows up as greyed out on the second boot. It should work though, because I worked around the upstream problem, but it may show up as unavailable before clicking it.
