### ISSUE TITLE
noise: after update to 3.30.0 sending messages not working

### ISSUE THREAD

**Issue by greycanary** [copperhead/bugtracker#600]
Hi,

didn't know where to file a bug report - hopefully this is the right place!

Since I updated Noise from 3.29.2 to 3.30.0 it doesn't send any encrypted signal messages anymore! Receiving  Messages works fine though!

It says I should activate SMS-Support and/or register Signal again to send encrypted Signal Messages (instead of SMS).

Same thing at another device - both devices run CyanogenMod 13 / Android 6.

**Comment by thestinger** [comment]
Did you accept the notice asking you to enable video / voice support? It will ask you to register again and not doing that might break it.

**Comment by thestinger** [comment]
Anyway, it's essentially an unmodified Signal now so I disabled the issue tracker there and I don't plan on taking bug reports for it.

**Comment by thestinger** [comment]
I think I know what's wrong with the transition but it's a bit late to change that now.

**Comment by thestinger** [comment]
https://github.com/copperhead/Noise/commit/f3d3de95d31f065d21feac175fc9660e3ee6499c

**Comment by thestinger** [comment]
There a new Signal 3.30.2 anyway so it's now part of that.
