### ISSUE TITLE
Noise unregister

### ISSUE THREAD

**Issue by Cj-Malone** [copperhead/bugtracker#602]
I'm trying to unregister my phone from Noise ( Noise > Settings > Advanced > Noise messages and calls ) but there's then a toast with "Error connecting to server."

I don't know if this is an upstream issue with Signal or an issue with Noise, it does seem that Signal just had an issue with this and GPS. ( https://github.com/WhisperSystems/Signal-Android/issues/6018 ) but I've had bad experiences with Signal and Moxie so I thought I'd check here first.

**Comment by thestinger** [comment]
Noise no longer has significant changes to the Signal code so it's highly unlikely it's related to Noise. Soon it won't have any changes at all. This bug tracker also isn't for tracking Noise issues.
