### ISSUE TITLE
Noise crashes initiating call, Signal does not

### ISSUE THREAD

**Issue by vvug** [copperhead/bugtracker#605]
Cable is affected by this bug, affecting self-compiled versions of Signal:

https://github.com/WhisperSystems/Signal-Android/issues/6355

The bug does not affect the official Signal builds.

**Comment by thestinger** [comment]
We don't make any changes to Signal, so it doesn't make sense to report issues here. Noise is simply a rebranded code and is explicitly not going to carry any patches to the code anymore. This is also the issue tracker for CopperheadOS and Noise isn't part of CopperheadOS.

**Comment by vvug** [comment]
@thestinger I know, but as Noise always crashes when starting a call, while Signal never crashes, and the source is the same, then the problem is clearly with your build process.

If you don't want to see these bugs reported here just open the issue tracker for Noise. Where do you expect people reporting them?

**Comment by thestinger** [comment]
It's not my code, so I don't really want to receive bug reports for it. I disabled the issue tracker once having a fork with changes was no longer necessary.

> then the problem is clearly with your build process.

It's not my build process. It's the standard build process they provide. You said yourself that you run into the problem with your own builds of Signal.

If Noise is going to create maintenance / support work, I can just stop providing it and have people download the Signal web site builds that update themselves and require unknown sources enabled. I am only providing a more convenient option under the condition that it's not taking much time.

**Comment by thestinger** [comment]
I would rather just redistribute their Play builds via our F-Droid repository if it was permitted...
