### ISSUE TITLE
GSM coverage in the US sucks. We need a verizon phone (with voice support, not just LTE!)

### ISSUE THREAD

**Issue by ballo** [copperhead/bugtracker#607]
Is CopperheadOS only for hipsters in the bay area? 

AT&T has simply given up trying to cover non-metro areas. Their coverage for voice is no better than 10 years ago. 

Coupled with the fact that smartphone antennas tend to suck, this makes non-Verizon phones unusable for much of this country. Some of us use phones primarily as, well, a phone. 

I realize that Verizon phones also tend to be locked, but many have been unlocked. 

![Coverage Map](http://static1.businessinsider.com/image/56e1cccedd0895750d8b45b1-2000-1053/coverage-map-1%202.png)

**Comment by thestinger** [comment]
Our phones aren't carrier locked.
