### ISSUE TITLE
Nexus 5x ends up at the "Encryption unsuccessful" screen right after install

### ISSUE THREAD

**Issue by sebastianbeyer** [copperhead/bugtracker#610]
Hi,
I just tried to install `bullhead-factory-2017.03.28.23.38.21.tar.xz` but now my 5x starts, shows the spinning Copperhead logo and then ends up on the "encryption uncsuccessful" screen. There I have the option to reset the phone (factory reset), but this only leads to some reboots and then again to the same screen.
I have checked the signature of the build and also the bootloader fingerprint matches.
Any ideas?

**Comment by sebastianbeyer** [comment]
Okai, I tried the previous release `bullhead-factory-2017.03.18.04.46.03.tar.xz` and with that it worked!

**Comment by sebastianbeyer** [comment]
hm... okai, I did the update, then locked the bootloader and I am back where I started: "encryption unsuccessful" :-/

**Comment by sebastianbeyer** [comment]
Okai, the way to go is: unlock bootloader -> install `2017.03.18.04.46.03` -> lock bootloader -> then update to most recent `2017.03.28.23.38.21`!

**Comment by thestinger** [comment]
I've installed the latest release on a Nexus 5X several times along with doing several factory resets and bootloader locks / unlocks and I've been unable to reproduce this problem. You'll need to provide more information on how to reproduce this or logs from the crash.

**Comment by thestinger** [comment]
Is this a North America Nexus 5X or an International one? Is it 32GB or 128GB? I'm testing on a Nexus 5X North America 32GB with no luck at reproducing this problem. Those are the only ones that we ever sold and the only one that is tested.

**Comment by thestinger** [comment]
Is this a North America Nexus 5X or an International one? Is it 16GB or 32GB? I'm testing on a Nexus 5X North America 16GB with no luck at reproducing this problem. Those are the only ones that we ever sold and the only one that is tested.

**Comment by packetgod** [comment]
This just happened on a brand new 6p 64GB North America trying to build with N4F26T.2017.03.28.23.38.21  I'm going to try the process with the older version and see if that works.

**Comment by thestinger** [comment]
What do you mean by 'to build with'?

**Comment by packetgod** [comment]
I just mean I'm installing that version.  And just to report my experience on the 6P is exactly the same as sebastianbeyer, I installed the previous version, it worked fine then I did the OTA update and all was good.  

Just to note that on my first try with installing the current version I missed locking the bootloader on the first try and went back to lock it after the first boot, not sure if that could have caused the issue with encryption.  I also rebooted after getting the error message a few times and then tried a wipe and nothing would get me past the encryption unsuccessful message.

**Comment by thestinger** [comment]
I'll probably make a new release with a recent change rolled back, although it's hard to see how it could cause this + I can't replicate the issue.

**Comment by thestinger** [comment]
This likely doesn't happen for the latest release. It's not fixed, but rather the hardening uncovering the issue was removed for the time being.

**Comment by sebastianbeyer** [comment]
Okai, I also have a EU 5X with 32GB, if that still matters.
