### ISSUE TITLE
flash-all script flashes recovery but leaves devices with no usable recovery partion on nexus 6p

### ISSUE THREAD

**Issue by xlCHINCHlx** [copperhead/bugtracker#614]
Please forgive me if this an user error. . . 

I fallow install instructions from your website (unlock bootloader - run flash-all - relock bootloader) on first boot i set up adb and try to boot to recovery to sideload the ota update but there is no functioning recovery partition. I just get the dead android icon.  Since the flash-all script couldnt get recovery to stick I wrote my own flash-all that unlocks bootloader, flashes bootloader, radio, boot, vendor, system, and recovery then relocks bootloader to save the needless reboots. it flashed fine as expected but after attempting "adb reboot recovery"  once again no usable recovery partition.  Any ideas?  To reproduce on nexus 6p fallow the install instructions and try to boot to recovery.   I also noticed after converting to file based encryption everything goes as expected but the file based encryption doesnt seem to "stick" and in dev options it gives option to convert again.   So is the wipe from the attempted file based encryption conversion some how wiping the recovery partition?  Idk I dont get it im hoping you can set me straight.  Ive flashed this nexus a few hundred times and done a ton of dum stuff with it, but i fear even powering it on with no recovery. Any advice would be much appreciated. Thanks guys, sorry to bug you.

**Comment by xlCHINCHlx** [comment]
Also quick side question (sorry)

I noticed the rom is a 7.1.2 rom, isnt that still beta or am i mistaken?

**Comment by thestinger** [comment]
This is working as intended. Just like with stock, the recovery menu isn't shown by default. It's not a bug and we don't handle support here.

File-based encryption is an unsupported demo on the Nexus 5X and 6P. It's a bad idea to use stuff hidden in developer options without fully understanding it.
