### ISSUE TITLE
Ability to stop app from starting

### ISSUE THREAD

**Issue by edpotter** [copperhead/bugtracker#621]
I am a very happy user of CopperheadOS.

There are apps that I don't trust but that I find useful (like FB, Instagram, Skype, Google maps). I would like these apps to run while I use them, but not in the background since they would likely be collecting various info on me and wasting my data & battery to do it.

The problem is that most of these apps start themselves on boot or have other hooks for starting themselves, meaning that even if I stop them, they come back.

Would it be possible for Copperhead to have an "only interactive" or "disable non-interactive startup" flag for apps? Alternatively, would it be possible to list the apps that start on startup, with a mechanism to disable certain ones?

**Comment by thestinger** [comment]
Swiping away apps in recent apps isn't the same thing as closing them. It would be possible to have a feature giving you what you want, but what you're proposing doesn't really fit into how things work. For this to be left open as an issue, it needs a clear design that works. I think it's also worth noting that there will be no result from simply filing a feature request unless you're willing to write the code or pay for it to be developed. There are more than enough feature requests open already to absorb a huge amount of development time, and many are fairly high priority.

I suggest using the existing multi-user feature for this.
