### ISSUE TITLE
Tethering broken on Nexus 5X with default T-Mobile APN (for some users)

### ISSUE THREAD

**Issue by craftyguy** [copperhead/bugtracker#623]
CopperheadOS Release: 2017.04.06.23.05.54

Carrier: T-Mobile USA

It appears that USB, Wifi, and bluetooth tethering do not work on the Nexus 5x with CopperheadOS. Devices connecting to the Nexus 5x receive an IP, but are unable to reach IPs outside the phone. I'm guessing something with the routing table is screwed up on the device. I wasn't able to find any upstream bugs on this, which is why I filed it here. Let me know what other info you need to diagnose this.

**Comment by thestinger** [comment]
It works here with Rogers and other carriers, so it's not a carrier-independent issue.

**Comment by craftyguy** [comment]
Could be a carrier specific issue then? The options available for debugging this on 'production' COS seem to be quite limited, and there's at least one other on reddit who recently reported the exact same issue, so I would appreciate if you knew of a way to move forward with figuring this out..

**Comment by thestinger** [comment]
It will require making builds of the operating system to narrow down the cause and perhaps building just plain AOSP with android-prepare-vendor to compare it with that. It's not something I can do since I don't have access to T-Mobile. They might be intentionally doing something to break tethering, or it may just be the usual T-Mobile issues related to their IPv6 that have never been diagnosed / debugged. There's not going to be progress without someone able and willing to debug issues like this with access to it. It's just another US carrier  quirk with no way for us to confirm it or make progress on it.

**Comment by craftyguy** [comment]
Well, I did offer to help, I just don't have the expertise to do everything you just said..

**Comment by thestinger** [comment]
All I could do is make builds for testing with more and more features disabled until it's just AOSP, some of which will require a fresh flash of the device. If it occurs with AOSP + android-prepare-vendor then it's not an issue that's in scope. There are features that could feasibly cause this so there's some more targeted stuff to test before rolling everything back to AOSP though.

I've tried to do this before, and there hasn't been follow through with testing the builds and reporting back even within a few days so it doesn't work as a way of narrowing it down. It can't really work well compared to someone debugging it themselves with access to it regardless.

**Comment by craftyguy** [comment]
So just because it didn't work once with someone else, you'd rather nop?

Well, at least this ticket will let US users of your software know that this feature is broken, regardless of 'who is at fault', because I guess that won't be determined.

**Comment by thestinger** [comment]
No I'm just saying I'm uneasy about investing time in that.

And this isn't broken for "US users". It's broken for your specific T-Mobile setup.

**Comment by craftyguy** [comment]
If you want to be super pedantic, it's broken for at least two of your T-Mobile US users, and quite possibly more since I'm not really doing anything fancy here..

**Comment by thestinger** [comment]
Are you using the standard T-Mobile APN or a custom configured one?

**Comment by craftyguy** [comment]
Yes, using the standard t-mobile APN.

I figured it out though, the standard APN is missing the 'dun' APN type. When I added that, tethering worked. Do you modify or ship a different APN config from AOSP in COS? It might be worth correcting that to save others the trouble. I'm guessing the APNs you tested were properly configured.

**Comment by thestinger** [comment]
We ship the APN configuration from AOSP which AFAIK matches stock Android.

**Comment by thestinger** [comment]
Using 'dun' isn't a proper solution to this.

**Comment by craftyguy** [comment]
Go on... Why not?

**Comment by thestinger** [comment]
Using a legacy protocol to work around an undiagnosed problem with the standard one isn't a solution.

**Comment by craftyguy** [comment]
I didn't know that was a legacy protocol. Not everyone has the same level of understanding of this stuff as you do. Currently using dun is the only way I can get tethering to work. If you have other suggestions, I would happily try them out.

**Comment by thestinger** [comment]
My suggestion is for someone with access to T-Mobile that's able to replicate this or other problems that have been reported to narrow down whether it's caused by CopperheadOS changes or with a regular build of AOSP. If it's caused by CopperheadOS, it's straightforward to narrow down the cause to a specific feature. No programming knowledge is required for any of that, only rolling back commits with Git and building.

If it's caused by AOSP, that's more problematic and it will require debugging work to figure out what's going wrong. Maybe it's something wrong with how android-prepare-vendor works, which should be reported to https://github.com/anestisb/android-prepare-vendor/issues.

It can't be assumed that this is a CopperheadOS issue without doing that. That's what the unconfirmed tag really means: not confirmed to be a CopperheadOS issue (I meant to use that originally not non-security-related).

**Comment by thestinger** [comment]
It also can't be known whether this is a bug or something else without something looking into it. For example, it might be that there's missing functionality from Google Play or vendor blobs that aren't included for the standard T-Mobile APN configuration to work. CopperheadOS doesn't have everything that's in stock. Adding more blobs to support carrier features is different than narrowing down, debugging and fixing an actual bug.

**Comment by 211217613** [comment]
I can follow up when I get back to the US. I have a spare N5X and T-Mobile service. I can install COS and try to dupliate craftguys problem.

**Comment by thestinger** [comment]
It needs to be checked if it's a problem in an AOSP build with android-prepare-vendor. I don't need someone to confirm if it occurs in CopperheadOS. Either way, the real need is for someone willing to dedicate time to working on resolving it.

**Comment by 211217613** [comment]
I have a few free days I can spend on it. I'm somewhat familiar with preparing AOSP builds but not with android-prepare-vendor. I'll check out the link you have to anestisb's github and set something up.

**Comment by thestinger** [comment]
This is addressed by the upcoming release.

On the other hand, whatever issues there are preventing the proper modern APNs from working for at least some people are not solved. Help is needed to resolve those issues. It's important for that to happen before the legacy APNs stop working.

**Comment by thestinger** [comment]
@craftyguy If you have some time to test some builds for me, let me know. There's a possible workaround for the default APN not working but I need someone able to test it.

**Comment by craftyguy** [comment]
I can do this if it's possible to do so without losing data on my device (e.g. having to reinstall COS or user apps)

**Comment by thestinger** [comment]
You won't lose any data. It will be an update you can sideload. Can you come on IRC when you have some time?

**Comment by thestinger** [comment]
I can just do the builds for you, signed with our keys, essentially, and give you update zips.

**Comment by thestinger** [comment]
As far as I know, the tethering issues are resolved. If you still have problems you should make sure your APN settings are reset to the standard configuration. Non-standard configurations aren't supported.

**Comment by thestinger** [comment]
I only need data points on carrier compatibility for Pixel phones and soon 2nd generation Pixel phones unless it's a regression on Nexus devices. I'm aware that AOSP and CopperheadOS don't offer the same carrier compatibility as stock Android. It could have been resolved, but I struggled to even get people to do testing or report back and it's too late: it's August, Android 8.0 is being released, and the 2 year partial end-of-life for Nexus devices is September.

**Comment by thestinger** [comment]
Bugs and regressions of carrier compatibility are still in-scope for Nexus devices but existing compatibility issues that are shared with AOSP like this aren't bugs so they're no longer in scope now that the 2 year period of device-specific feature work for Nexus devices is coming to a close. August and September will be dedicated to migrating to Android 8.0 and September 2017 is the 2 year partial end-of-life for Nexus devices. Android 8.0 porting will be the last bit of device-specific feature work for them. October will be the release of 2nd generation Pixel phones, and then 1st and 2nd generation Pixel phones will be the devices receiving active device-specific feature work with Nexus devices only receiving device-independent features and bug / security fixes until their final EOL in September 2018.
