### ISSUE TITLE
VolDown + Power for 10 seconds does not power off, it restarts

### ISSUE THREAD

**Issue by Rudd-O** [copperhead/bugtracker#625]
According to what little documentation I could find online, Volume down plus Power button for ten seconds should power the phone off.  Instead, it restarts the phone.

This is happening with CopperheadOS latest nightly.

**Comment by thestinger** [comment]
This isn't part of CopperheadOS, it's a hardware feature.

**Comment by Rudd-O** [comment]
Does it power off the phone for you, or reboot it?

I ask in re: https://twitter.com/dragosr/status/860752473555836929

**Comment by thestinger** [comment]
You aren't stating which device you're using and this is a hardware feature, not an OS feature.

**Comment by Rudd-O** [comment]
Nexus 5X.  Again, in your experience, do Nexus 5X devices reboot when the button combo is used, or power off?

**Comment by thestinger** [comment]
They reboot, the advice there is nonsense.

**Comment by Rudd-O** [comment]
K.
