### ISSUE TITLE
Wi-Fi going off and on every few minutes when phone screen is off

### ISSUE THREAD

**Issue by Rudd-O** [copperhead/bugtracker#626]
Latest Copperhead NIGHTLY, Nexus 5X.

I recently installed Tasker on the phone and set up a task that beeps one sound when the phone's Wi-Fi connection goes away, and another sound when the phone-s Wi-Fi connection is restored.  I did this because I needed to figure out why there was *so much cellular data use*, even when the phone was.

Sure enough, the phone shuts off Wi-Fi and turns it back on almost immediately (2 seconds or so).  This happens anywhere from every minute to every six minutes.  (Naturally, apps with ongoing connections will continue those connections, because data is not suspended until all apps have moved to Wi-Fi).

Other devices on the network do not experience this, at all.  I must stress this — _only the  phone_ experiences this issue.

My router says this:

```
Sun May 14 11:13:49 2017 daemon.info hostapd: wlan0: STA <mac of phone> IEEE 802.11: disconnected due to excessive missing ACKs
Sun May 14 11:13:51 2017 daemon.info hostapd: wlan0: STA <mac of phone> IEEE 802.11: authenticated
Sun May 14 11:13:51 2017 daemon.info hostapd: wlan0: STA <mac of phone> IEEE 802.11: associated (aid 2)
```

There's an OpenWrt bug open about this: https://dev.openwrt.org/ticket/19648 .  I find it unlikely that, if this was a legit OpenWrt bug, it would only be happening with my phone.

What other information is needed to diagnose the problem?

Thank you in advance.

**Comment by Rudd-O** [comment]
I've worked around the problem temporarily by disabling lack of ACKs from the phone (while it sleeps)  with:

```
  option disassoc_low_ack '0'
```

in the iface config of `/etc/config/wireless` in my router.

This doesn't actually solve the bug, tho.  It's just a workaround explained here:

https://github.com/enyone/tplink-archer-c7-openwrt/blob/master/README.md

**Comment by thestinger** [comment]
I don't think this is a CopperheadOS issue rather than a generic issue that will also occur with that router and the WiFi chip / driver used by the Nexus 5X. There are lots of reports like this for qcacld-2.0 upstream. We don't make any changes directly related to stuff like this.
