### ISSUE TITLE
Latest firmware broke cellular data on Nexus 5X

### ISSUE THREAD

**Issue by KillerCrocs** [copperhead/bugtracker#627]
Hello. A few weeks ago I updated my phone (Nexus 5X) to the latest firmware and have found that 2G, 3G, 4G, and LTE connections were inconsistent. Now, I don't live in the biggest town so I figured it might have just been spotty service from T-Mobile. With that said, I recently got back from my visit to New York City and I'm fairly certain that T-Mobile offers good service in NYC. Knowing this, I began trying to fix my data issues. I reset network settings, went to a store and swapped out Sim Cards, messed around with (and reset to default) to APN settings, etc. My problems are still on going. 

Now in terms of what my phone is doing. I can maintain a perfect cellular connection, meaning phone calls and SMS still work perfectly fine. ONLY my data is failing to connect. Randomly, however, it will randomly manage to connect to LTE networks. Once it does this it maintains the connection until it either drops, i restart phone, or I put it into airplane mode (basically anything to reset the network connections). Once it drops the data connection it can take days before it ever reconnects. 

I can't figure out what it is, and I haven't seen anything posted on here about people having similar situations. Now I have not factory reset my phone, only because I'd have to back up a number of things and reset them (which would be time consuming so I'm saving that for last). I figured I'd try and post the issue on here because if it is a problem with the latest update then it'll only ever get fixed in time if its reported. Sorry for the long message, trying to be detailed!

- _Steps to reproduce:_ Unknown, seems random.
- _Copperhead OS Version:_ Android version is 7.1.2, last update installed was OTA update on May 1st.
- _Device Model:_  Nexus 5X
- _ADB Logcat (Only with errors):_ 

> --------- beginning of system
> 08-08 06:19:03.772   376   383 E vold    : Failed to chmod /data/system_ce/0: No such file or directory
> 08-08 06:19:03.772   376   383 E vold    : Failed to chmod /data/misc_ce/0: No such file or directory
> 08-08 06:19:03.772   376   383 E vold    : Failed to chmod /data/media/0: No such file or directory
> 08-08 06:19:08.179   767   835 E LocalDisplayAdapter: Default and active color mode is no longer available! Reverting to first available mode.
> 08-08 06:19:10.043   767   767 E PackageManager: There should probably be exactly one storage manager; found 0: matches=[]
> 08-08 06:19:10.044   767   767 E PackageManager: There should probably be exactly one setup wizard; found 0: matches=[]
> 08-08 06:19:10.736   767   833 E VoldConnector: Error handling '662 /data -1 -1': java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.DropBoxManager.addText(java.lang.String, java.lang.String)' on a null object reference
> 08-08 06:19:10.741   767   767 E PersistentDataBlockService: not able to find package 
> 08-08 06:19:10.741   767   767 E PersistentDataBlockService: android.content.pm.PackageManager$NameNotFoundException: 
> 08-08 06:19:10.741   767   767 E PersistentDataBlockService: 	at android.app.ApplicationPackageManager.getPackageUidAsUser(ApplicationPackageManager.java:256)
> 08-08 06:19:10.741   767   767 E PersistentDataBlockService: 	at com.android.server.PersistentDataBlockService.getAllowedUid(PersistentDataBlockService.java:105)
> 08-08 06:19:10.741   767   767 E PersistentDataBlockService: 	at com.android.server.PersistentDataBlockService.<init>(PersistentDataBlockService.java:96)
> 08-08 06:19:10.741   767   767 E PersistentDataBlockService: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
> 08-08 06:19:10.741   767   767 E PersistentDataBlockService: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
> 08-08 06:19:10.741   767   767 E PersistentDataBlockService: 	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:93)
> 08-08 06:19:10.741   767   767 E PersistentDataBlockService: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:766)
> 08-08 06:19:10.741   767   767 E PersistentDataBlockService: 	at com.android.server.SystemServer.run(SystemServer.java:340)
> 08-08 06:19:10.741   767   767 E PersistentDataBlockService: 	at com.android.server.SystemServer.main(SystemServer.java:222)
> 08-08 06:19:10.741   767   767 E PersistentDataBlockService: 	at java.lang.reflect.Method.invoke(Native Method)
> 08-08 06:19:10.741   767   767 E PersistentDataBlockService: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:882)
> 08-08 06:19:10.741   767   767 E PersistentDataBlockService: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)
> 08-08 06:19:10.745   767   833 E VoldConnector: Error handling '662 /cache 88076288 9064376': java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.DropBoxManager.addText(java.lang.String, java.lang.String)' on a null object reference
> 08-08 06:19:10.767   767   810 E AppIdleHistory: Unable to read app idle file for user 0
> 08-08 06:19:11.239   767   767 E WallpaperManagerService: Invalid wallpaper data
> 08-08 06:19:11.239   767   767 E WallpaperManagerService: Unable to apply new wallpaper
> 08-08 06:19:11.520   767   767 E LockSettingsService: Unable to acquire GateKeeperService
> 08-08 06:19:11.522   767   767 E LockSettingsStorage: Cannot read file java.io.FileNotFoundException: /data/system/gatekeeper.password.key: open failed: ENOENT (No such file or directory)
> 08-08 06:19:11.522   767   767 E LockSettingsStorage: Cannot read file java.io.FileNotFoundException: /data/system/password.key: open failed: ENOENT (No such file or directory)
> 08-08 06:19:11.523   767   767 E LockSettingsStorage: Cannot read file java.io.FileNotFoundException: /data/system/gatekeeper.pattern.key: open failed: ENOENT (No such file or directory)
> 08-08 06:19:11.523   767   767 E LockSettingsStorage: Cannot read file java.io.FileNotFoundException: /data/system/gatekeeper.gesture.key: open failed: ENOENT (No such file or directory)
> 08-08 06:19:11.523   767   767 E LockSettingsStorage: Cannot read file java.io.FileNotFoundException: /data/system/gesture.key: open failed: ENOENT (No such file or directory)
> 08-08 06:19:11.711   767   834 E BluetoothManagerService: Fail to bind to: Intent { act=android.bluetooth.IBluetooth }
> 08-08 06:19:11.712   767   767 E InputMethodManagerService: Ignoring updateSystemUiLocked due to an invalid token. uid:1000 token:null
> 08-08 06:19:11.764   376   383 E vold    : Failed to chmod /data/system_ce/0: No such file or directory
> 08-08 06:19:11.764   376   383 E vold    : Failed to chmod /data/misc_ce/0: No such file or directory
> 08-08 06:19:11.764   376   383 E vold    : Failed to chmod /data/media/0: No such file or directory
> 08-08 06:19:12.339   767   767 E LocationManagerService: no geocoder provider found
> 08-08 06:19:12.590   767  2563 E ActivityThread: Failed to find provider info for call_log
> 08-08 06:19:13.190   767  1691 E ActivityThread: Failed to find provider info for com.android.calendar
> 08-08 06:19:13.191   767  1691 E ActivityThread: Failed to find provider info for com.android.calendar
> 08-08 06:19:13.621  1997  2721 E ActivityThread: Failed to find provider info for user_dictionary
> 08-08 06:19:14.222  2025  2796 E ActivityThread: Failed to find provider info for com.android.contacts
> 08-08 06:19:16.421   767  3043 E BootReceiver: Error reading /data/system/last-header.txt
> 08-08 06:19:16.421   767  3043 E BootReceiver: java.io.FileNotFoundException: /data/system/last-header.txt (No such file or directory)
> 08-08 06:19:16.421   767  3043 E BootReceiver: 	at java.io.FileInputStream.open(Native Method)
> 08-08 06:19:16.421   767  3043 E BootReceiver: 	at java.io.FileInputStream.<init>(FileInputStream.java:146)
> 08-08 06:19:16.421   767  3043 E BootReceiver: 	at android.os.FileUtils.readTextFile(FileUtils.java:263)
> 08-08 06:19:16.421   767  3043 E BootReceiver: 	at com.android.server.BootReceiver.getPreviousBootHeaders(BootReceiver.java:121)
> 08-08 06:19:16.421   767  3043 E BootReceiver: 	at com.android.server.BootReceiver.getBootHeadersToLogAndUpdate(BootReceiver.java:143)
> 08-08 06:19:16.421   767  3043 E BootReceiver: 	at com.android.server.BootReceiver.logBootEvents(BootReceiver.java:163)
> 08-08 06:19:16.421   767  3043 E BootReceiver: 	at com.android.server.BootReceiver.-wrap2(BootReceiver.java)
> 08-08 06:19:16.421   767  3043 E BootReceiver: 	at com.android.server.BootReceiver$1.run(BootReceiver.java:93)
> 08-08 06:19:17.644  3045  3095 E ActivityThread: Failed to find provider info for call_log
> 08-08 06:19:18.636  2483  3144 E ActivityThread: Failed to find provider info for com.android.contacts
> 08-08 06:19:25.572   767   810 E RemotePrintSpooler: Error pruning approved print services.
> 08-08 06:19:25.572   767   810 E RemotePrintSpooler: java.util.concurrent.TimeoutException: Cannot get spooler!
> 08-08 06:19:25.572   767   810 E RemotePrintSpooler: 	at com.android.server.print.RemotePrintSpooler.bindLocked(RemotePrintSpooler.java:633)
> 08-08 06:19:25.572   767   810 E RemotePrintSpooler: 	at com.android.server.print.RemotePrintSpooler.getRemoteInstanceLazy(RemotePrintSpooler.java:602)
> 08-08 06:19:25.572   767   810 E RemotePrintSpooler: 	at com.android.server.print.RemotePrintSpooler.pruneApprovedPrintServices(RemotePrintSpooler.java:515)
> 08-08 06:19:25.572   767   810 E RemotePrintSpooler: 	at com.android.server.print.UserState.prunePrintServices(UserState.java:996)
> 08-08 06:19:25.572   767   810 E RemotePrintSpooler: 	at com.android.server.print.UserState.<init>(UserState.java:159)
> 08-08 06:19:25.572   767   810 E RemotePrintSpooler: 	at com.android.server.print.PrintManagerService$PrintManagerImpl.getOrCreateUserStateLocked(PrintManagerService.java:822)
> 08-08 06:19:25.572   767   810 E RemotePrintSpooler: 	at com.android.server.print.PrintManagerService$PrintManagerImpl.-wrap0(PrintManagerService.java)
> 08-08 06:19:25.572   767   810 E RemotePrintSpooler: 	at com.android.server.print.PrintManagerService$PrintManagerImpl$3.run(PrintManagerService.java:843)
> 08-08 06:19:25.572   767   810 E RemotePrintSpooler: 	at android.os.Handler.handleCallback(Handler.java:751)
> 08-08 06:19:25.572   767   810 E RemotePrintSpooler: 	at android.os.Handler.dispatchMessage(Handler.java:95)
> 08-08 06:19:25.572   767   810 E RemotePrintSpooler: 	at android.os.Looper.loop(Looper.java:154)
> 08-08 06:19:25.572   767   810 E RemotePrintSpooler: 	at android.os.HandlerThread.run(HandlerThread.java:61)
> 08-08 06:19:28.679   767  2806 E CryptdConnector: NDC Command {9 cryptfs checkpw [scrubbed]} took too long (4321ms)
> 05-18 14:58:55.978  4333  4382 E LocalDisplayAdapter: Default and active color mode is no longer available! Reverting to first available mode.
> 05-18 14:59:00.750  4333  4333 E PersistentDataBlockService: not able to find package 
> 05-18 14:59:00.750  4333  4333 E PersistentDataBlockService: android.content.pm.PackageManager$NameNotFoundException: 
> 05-18 14:59:00.750  4333  4333 E PersistentDataBlockService: 	at android.app.ApplicationPackageManager.getPackageUidAsUser(ApplicationPackageManager.java:256)
> 05-18 14:59:00.750  4333  4333 E PersistentDataBlockService: 	at com.android.server.PersistentDataBlockService.getAllowedUid(PersistentDataBlockService.java:105)
> 05-18 14:59:00.750  4333  4333 E PersistentDataBlockService: 	at com.android.server.PersistentDataBlockService.<init>(PersistentDataBlockService.java:96)
> 05-18 14:59:00.750  4333  4333 E PersistentDataBlockService: 	at java.lang.reflect.Constructor.newInstance0(Native Method)
> 05-18 14:59:00.750  4333  4333 E PersistentDataBlockService: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
> 05-18 14:59:00.750  4333  4333 E PersistentDataBlockService: 	at com.android.server.SystemServiceManager.startService(SystemServiceManager.java:93)
> 05-18 14:59:00.750  4333  4333 E PersistentDataBlockService: 	at com.android.server.SystemServer.startOtherServices(SystemServer.java:766)
> 05-18 14:59:00.750  4333  4333 E PersistentDataBlockService: 	at com.android.server.SystemServer.run(SystemServer.java:340)
> 05-18 14:59:00.750  4333  4333 E PersistentDataBlockService: 	at com.android.server.SystemServer.main(SystemServer.java:222)
> 05-18 14:59:00.750  4333  4333 E PersistentDataBlockService: 	at java.lang.reflect.Method.invoke(Native Method)
> 05-18 14:59:00.750  4333  4333 E PersistentDataBlockService: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:882)
> 05-18 14:59:00.750  4333  4333 E PersistentDataBlockService: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)
> 05-18 14:59:01.337  4333  4333 E WallpaperManagerService: Invalid wallpaper data
> 05-18 14:59:01.337  4333  4333 E WallpaperManagerService: Unable to apply new wallpaper
> 05-18 14:59:02.579  4333  4333 E LockSettingsStorage: Cannot read file java.io.FileNotFoundException: /data/system/gatekeeper.gesture.key: open failed: ENOENT (No such file or directory)
> 05-18 14:59:02.579  4333  4333 E LockSettingsStorage: Cannot read file java.io.FileNotFoundException: /data/system/gesture.key: open failed: ENOENT (No such file or directory)
> 05-18 14:59:02.893  4333  4333 E InputMethodManagerService: Ignoring updateSystemUiLocked due to an invalid token. uid:1000 token:null
> 05-18 14:59:02.992  4333  4333 E WallpaperManagerService: Invalid wallpaper data
> 05-18 14:59:02.992  4333  4333 E WallpaperManagerService: Unable to apply new wallpaper
> 05-18 14:59:04.103  4333  4711 E NetdConnector: NDC Command {5 softap fwreload wlan0 STA} took too long (984ms)
> 05-18 14:59:04.185  4333  4333 E NetdConnector: NDC Command {6 strict enable} took too long (1020ms)
> 05-18 14:59:04.242  5286  5663 E ActivityThread: Failed to find provider info for user_dictionary
> 05-18 14:59:04.269  5298  5667 E ActivityThread: Failed to find provider info for com.android.contacts
> 05-18 14:59:04.647  4333  4333 E LocationManagerService: no geocoder provider found
> 05-18 14:59:04.864  5298  5811 E ActivityThread: Failed to find provider info for com.android.contacts
> 05-18 14:59:04.916  4333  5822 E ActivityThread: Failed to find provider info for call_log
> 05-18 14:59:05.127  4333  4751 E ActivityThread: Failed to find provider info for com.android.calendar
> 05-18 14:59:05.129  4333  4751 E ActivityThread: Failed to find provider info for com.android.calendar
> 05-18 14:59:06.536  5755  5966 E ActivityThread: Failed to find provider info for com.android.contacts
> --------- beginning of main
> 05-18 14:59:10.969  6406  6754 E NfcAdaptation: NfcAdaptation::Initialize: ver=NFCDROID-AOSP_N_00.01 nfa=NFA_PI_1.03.66+
> 05-18 14:59:11.045  6406  6754 E NxpHal  : i2c_fragmentation_status existing
> 05-18 14:59:11.056  6406  6754 E NxpFwDnld: Freeing Mem for Dnld Context..
> 05-18 14:59:11.330  5755  5755 E ImsServiceSub: handleSrvStatusUpdate tracker is null so not updating global VT capability
> 05-18 14:59:11.911  6743  6743 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:12.247  6787  6787 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:13.476  4333  4366 E BatteryStatsService: no controller energy info supplied
> 05-18 14:59:13.497  4333  4366 E BatteryStatsService: modem info is invalid: ModemActivityInfo{ mTimestamp=55761 mSleepTimeMs=14289 mIdleTimeMs=-17475 mTxTimeMs[]=[89, 17, 22, 0, 0] mRxTimeMs=2888 mEnergyUsed=0}
> 05-18 14:59:13.709  6854  6854 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:14.072  4333  6441 E ActivityManager: applyOptionsLocked: Unknown animationType=0
> 05-18 14:59:14.416  4333  5657 E WifiHAL : Few pkt stats messages missed: rcvd = 0, prev = 0
> 05-18 14:59:14.809  4333  6918 E BootReceiver: Can't log boot events
> 05-18 14:59:14.809  4333  6918 E BootReceiver: java.io.FileNotFoundException: /dev/fscklogs/log (Permission denied)
> 05-18 14:59:14.809  4333  6918 E BootReceiver: 	at java.io.FileInputStream.open(Native Method)
> 05-18 14:59:14.809  4333  6918 E BootReceiver: 	at java.io.FileInputStream.<init>(FileInputStream.java:146)
> 05-18 14:59:14.809  4333  6918 E BootReceiver: 	at android.os.FileUtils.readTextFile(FileUtils.java:263)
> 05-18 14:59:14.809  4333  6918 E BootReceiver: 	at com.android.server.BootReceiver.addFsckErrorsToDropBox(BootReceiver.java:311)
> 05-18 14:59:14.809  4333  6918 E BootReceiver: 	at com.android.server.BootReceiver.logBootEvents(BootReceiver.java:203)
> 05-18 14:59:14.809  4333  6918 E BootReceiver: 	at com.android.server.BootReceiver.-wrap2(BootReceiver.java)
> 05-18 14:59:14.809  4333  6918 E BootReceiver: 	at com.android.server.BootReceiver$1.run(BootReceiver.java:93)
> 05-18 14:59:15.185  4333  5650 E BatteryStatsService: no controller energy info supplied
> 05-18 14:59:15.202  4333  5650 E BatteryStatsService: modem info is invalid: ModemActivityInfo{ mTimestamp=57467 mSleepTimeMs=14289 mIdleTimeMs=-17475 mTxTimeMs[]=[89, 17, 22, 0, 0] mRxTimeMs=2888 mEnergyUsed=0}
> 05-18 14:59:15.569  6919  6919 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:15.985  4333  4711 E WifiNative-HAL: setBssidBlacklist cmd 0 size 0
> 05-18 14:59:16.011  4333  4711 E WifiStateMachine: Did not find remoteAddress {192.168.1.254} in /proc/net/arp
> 05-18 14:59:16.167  4333  5828 E GnssLocationProvider: requestTime failed
> 05-18 14:59:16.678  6942  6942 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:16.957  6966  6966 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:17.057  3293  4590 E Netd    : netlink response contains error (File exists)
> 05-18 14:59:18.525  7062  7062 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:19.411  3293  4590 E Netd    : netlink response contains error (File exists)
> 05-18 14:59:19.823  7062  7062 E ActivityThread: Service com.android.email.service.EmailBroadcastProcessorService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@e0748c2 that was originally bound here
> 05-18 14:59:19.823  7062  7062 E ActivityThread: android.app.ServiceConnectionLeaked: Service com.android.email.service.EmailBroadcastProcessorService has leaked ServiceConnection com.android.emailcommon.service.ServiceProxy$ProxyConnection@e0748c2 that was originally bound here
> 05-18 14:59:19.823  7062  7062 E ActivityThread: 	at android.app.LoadedApk$ServiceDispatcher.<init>(LoadedApk.java:1336)
> 05-18 14:59:19.823  7062  7062 E ActivityThread: 	at android.app.LoadedApk.getServiceDispatcher(LoadedApk.java:1231)
> 05-18 14:59:19.823  7062  7062 E ActivityThread: 	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1450)
> 05-18 14:59:19.823  7062  7062 E ActivityThread: 	at android.app.ContextImpl.bindService(ContextImpl.java:1422)
> 05-18 14:59:19.823  7062  7062 E ActivityThread: 	at android.content.ContextWrapper.bindService(ContextWrapper.java:636)
> 05-18 14:59:19.823  7062  7062 E ActivityThread: 	at com.android.emailcommon.service.ServiceProxy.setTask(ServiceProxy.java:181)
> 05-18 14:59:19.823  7062  7062 E ActivityThread: 	at com.android.emailcommon.service.ServiceProxy.test(ServiceProxy.java:224)
> 05-18 14:59:19.823  7062  7062 E ActivityThread: 	at com.android.email.service.EmailServiceUtils.isServiceAvailable(EmailServiceUtils.java:160)
> 05-18 14:59:19.823  7062  7062 E ActivityThread: 	at com.android.email.provider.AccountReconciler.reconcileAccountsInternal(AccountReconciler.java:171)
> 05-18 14:59:19.823  7062  7062 E ActivityThread: 	at com.android.email.provider.AccountReconciler.reconcileAccounts(AccountReconciler.java:115)
> 05-18 14:59:19.823  7062  7062 E ActivityThread: 	at com.android.email.service.EmailBroadcastProcessorService.reconcileAndStartServices(EmailBroadcastProcessorService.java:305)
> 05-18 14:59:19.823  7062  7062 E ActivityThread: 	at com.android.email.service.EmailBroadcastProcessorService.onBootCompleted(EmailBroadcastProcessorService.java:295)
> 05-18 14:59:19.823  7062  7062 E ActivityThread: 	at com.android.email.service.EmailBroadcastProcessorService.onHandleIntent(EmailBroadcastProcessorService.java:130)
> 05-18 14:59:19.823  7062  7062 E ActivityThread: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
> 05-18 14:59:19.823  7062  7062 E ActivityThread: 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 05-18 14:59:19.823  7062  7062 E ActivityThread: 	at android.os.Looper.loop(Looper.java:154)
> 05-18 14:59:19.823  7062  7062 E ActivityThread: 	at android.os.HandlerThread.run(HandlerThread.java:61)
> 05-18 14:59:20.131  7114  7114 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:21.360  7146  7146 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:21.729  3293  4590 E Netd    : netlink response contains error (No such file or directory)
> 05-18 14:59:22.725  7214  7214 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:24.322  7269  7269 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:25.206  4333  6245 E BatteryStatsService: no controller energy info supplied
> 05-18 14:59:25.999  7310  7310 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:26.576  7310  7310 E AtFwd AutoBoot: AtFwd Auto Boot Started Successfully
> 05-18 14:59:27.284  4333  5650 E UserRestrictionsUtils: Unknown restriction: null
> 05-18 14:59:27.991  7342  7342 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:28.656  4333  4761 E BatteryStatsService: no controller energy info supplied
> 05-18 14:59:29.928  7380  7380 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:32.597  7417  7417 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:34.763  7449  7449 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:36.019  7449  7449 E GMPM    : GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.
> 05-18 14:59:36.019  7449  7449 E GMPM    : Scheduler not set. Not logging error/warn.
> 05-18 14:59:36.056  7449  7489 E GMPM    : Uploading is not possible. App measurement disabled
> 05-18 14:59:37.565  4333  4356 E BatteryStatsService: no controller energy info supplied
> 05-18 14:59:38.803  4333  5650 E UserRestrictionsUtils: Unknown restriction: null
> 05-18 14:59:38.809  4333  4355 E UserRestrictionsUtils: Unknown restriction: null
> 05-18 14:59:38.855  7539  7539 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:38.974  5755  5755 E PhoneInterfaceManager: [PhoneIntfMgr] getAllowedCarriers: Empty response
> 05-18 14:59:39.005  5755  5755 E PhoneInterfaceManager: [PhoneIntfMgr] getAllowedCarriers: Empty response
> 05-18 14:59:41.800  7585  7585 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:44.264  7628  7628 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:45.709  7628  7628 E FORESEE_SDK_LIB   : Not initializing ForeSee SDK; Android version is not supported
> 05-18 14:59:45.817  7628  7628 E WebViewFactory: can't load with relro file; address space not reserved
> 05-18 14:59:47.596  7689  7689 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:49.976  7720  7720 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:52.735  7795  7795 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:54.662  7819  7819 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:57.922  7857  7857 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 14:59:59.030  7857  7857 E GMPM    : GoogleService failed to initialize, status: 10, Missing an expected resource: 'R.string.google_app_id' for initializing Google services.  Possible causes are missing google-services.json or com.google.gms.google-services gradle plugin.
> 05-18 14:59:59.031  7857  7857 E GMPM    : Scheduler not set. Not logging error/warn.
> 05-18 14:59:59.092  7857  7888 E GMPM    : Uploading is not possible. App measurement disabled
> 05-18 14:59:59.763  7857  7896 E SQLiteLog: (21) misuse at line 136010 of [fc49f556e4]
> 05-18 14:59:59.766  7857  7896 E SQLiteLog: (21) misuse at line 136010 of [fc49f556e4]
> 05-18 14:59:59.767  7857  7896 E SQLiteLog: (21) misuse at line 136010 of [fc49f556e4]
> 05-18 14:59:59.795  7857  7896 E SQLiteLog: (283) recovered 18 frames from WAL file /data/user/0/com.plexapp.android/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db-wal
> 05-18 15:00:03.219  7940  7940 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 15:00:05.448  8004  8004 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 15:00:07.675  8042  8042 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 15:00:09.565  4333  5650 E ActivityManager: applyOptionsLocked: Unknown animationType=0
> 05-18 15:00:11.219  5755  5755 E PhoneInterfaceManager: [PhoneIntfMgr] getAllowedCarriers: Empty response
> 05-18 15:00:11.464  7819  7856 E ~!ETPushService          : Error waiting for ETPush to be initialized. Our error was: Error waiting for configureSdk() to be called. Our error was: Waiting for configureSdk() to be called timed out.  Did you forget to call configureSdk()?
> 05-18 15:00:11.464  7819  7856 E ~!ETPushService          : com.exacttarget.etpushsdk.ETException: Error waiting for ETPush to be initialized. Our error was: Error waiting for configureSdk() to be called. Our error was: Waiting for configureSdk() to be called timed out.  Did you forget to call configureSdk()?
> 05-18 15:00:11.464  7819  7856 E ~!ETPushService          : 	at com.exacttarget.etpushsdk.ETPush.a(SourceFile:198)
> 05-18 15:00:11.464  7819  7856 E ~!ETPushService          : 	at com.exacttarget.etpushsdk.ETPushService.onHandleIntent(SourceFile:148)
> 05-18 15:00:11.464  7819  7856 E ~!ETPushService          : 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
> 05-18 15:00:11.464  7819  7856 E ~!ETPushService          : 	at android.os.Handler.dispatchMessage(Handler.java:102)
> 05-18 15:00:11.464  7819  7856 E ~!ETPushService          : 	at android.os.Looper.loop(Looper.java:154)
> 05-18 15:00:11.464  7819  7856 E ~!ETPushService          : 	at android.os.HandlerThread.run(HandlerThread.java:61)
> 05-18 15:00:13.512  8220  8220 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 15:00:15.791  8251  8251 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 15:00:19.058  5755  5755 E PhoneInterfaceManager: [PhoneIntfMgr] getAllowedCarriers: Empty response
> 05-18 15:00:31.389  4333  4366 E BatteryStatsService: no controller energy info supplied
> 05-18 15:00:44.317  8336  8336 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 15:00:49.630  4333  4385 E libEGL  : call to OpenGL ES API with no current context (logged once per thread)
> 05-18 15:02:22.006  8251  8420 E Email   : Error while copying downloaded message.com.android.emailcommon.mail.MessagingException: Unable to open body
> 05-18 15:04:01.264  4333  4366 E BatteryStatsService: no controller energy info supplied
> 05-18 15:04:16.291  4333  8474 E LocSvc_eng: E/int loc_eng_inject_time(loc_eng_data_s_type &, GpsUtcTime, int64_t, int): log_eng state error: instance not initialized
> 05-18 15:07:24.660  4333  4366 E BatteryStatsService: no controller energy info supplied
> 05-18 15:10:24.623  4333  4366 E BatteryStatsService: no controller energy info supplied
> 05-18 15:13:24.651  4333  4366 E BatteryStatsService: no controller energy info supplied
> 05-18 15:16:24.652  4333  4366 E BatteryStatsService: no controller energy info supplied
> 05-18 15:16:40.008  5755  5755 E PhoneInterfaceManager: [PhoneIntfMgr] getAllowedCarriers: Empty response
> 05-18 15:16:42.905  8782  8782 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 15:16:43.383  4333  5650 E BatteryStatsService: no controller energy info supplied
> 05-18 15:17:41.806  4333  4366 E BatteryStatsService: no controller energy info supplied
> 05-18 15:18:29.746  4333  5650 E BatteryStatsService: no controller energy info supplied
> 05-18 15:19:42.793  9072  9072 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
> 05-18 15:19:46.181  9111  9111 E Typeface: Error mapping font file /system/fonts/DroidSansFallback.ttf
>

**Comment by thestinger** [comment]
If you're a customer, please use the customer support system for this. Help can't be provided for carrier issues like this via the bug tracker. It's a troubleshooting / customer support issue first and foremost rather than a bug to be dealt with on this issue tracker.

This isn't tied to any recent CopperheadOS update. Carriers vary by region and make changes over time. T-Mobile has never worked well with CopperheadOS. The default APNs are supposed to work, but they're made for stock where there are extra proprietary carrier apps that we aren't bundling. T-Mobile doesn't exist in Canada, and no one has ever invested time in working on support for non-Canadian carriers. The issues aren't caused by changes made by CopperheadOS and also occur with an AOSP build made in the same way. That makes it out-of-scope for this tracker. It's in-scope in terms of what we care about, but our focus is on improving this for Pixel and Pixel XL devices right now and it isn't something that we track here since it's not caused by bugs.
