### ISSUE TITLE
Speaker phone causing garbled audio

### ISSUE THREAD

**Issue by chrisohara** [copperhead/bugtracker#633]
When switching from speaker phone to handset mode on the Nexus 6p the audio becomes distant and garbled for about 10 seconds.  This occurs on every call when switching from the speaker to the handset mode.. it would appear that the microphone isn't switching over properly.  If holding the phone up to your ear, it doesn't pick up the audio, but will pick up the audio as if it was still on speaker mode.

**Comment by thestinger** [comment]
I expect it's an upstream issue rather than a CopperheadOS problem. Fixing every bug in Android and driver / hardware issues it has on specific devices isn't realistically in scope for CopperheadOS. It's only in scope if a CopperheadOS feature uncovers / triggers / causes the issue.

**Comment by chrisohara** [comment]
Unfortunately I do not have two Nexus 6p's to be able test this on.  I would need a default Nexus 6p to test this and a Copperhead OS one to test it.  Unfortunately I only have one phone which is why I was hoping you may have two to test and ensure it is a Nexus 6p problem instead of a copperhead OS problem.

**Comment by thestinger** [comment]
Nope, we're not able to confirm if this is an issue on AOSP.

**Comment by thestinger** [comment]
I can't keep open bugs that are likely AOSP issues. There are lots of AOSP issues, and Google has many developers to work on them while we have one.

**Comment by thestinger** [comment]
I can't replicate it at all. Maybe a hardware issue.

**Comment by chrisohara** [comment]
No worries.  I understand the need to close the issue.  I will continue to use my Bluetooth instead of speaker phone.  Thank you for testing.
