### ISSUE TITLE
Impress Remote crashes on next animation

### ISSUE THREAD

**Issue by thelifeofjay** [copperhead/bugtracker#642]
Further information to come: this is a placeholder while I debug.

**Steps to reproduce:**
Attach to WiFi -> Click next animation on slide -> Resets application

**Application Version:** Impress Remote (v 2.3.0 F-Droid)
**Device Model:** Nexus 5X
**CopperheadOS Version:** Release N2G47X.2017.06.06.00.02.24
**ADB Logcat**: https://paste.xinu.at/nONuh1/

**Comment by thestinger** [comment]
Looks like an app bug. Why is it enabling strict mode in production and then violating it?

> 06-19 12:45:32.231 24514 24514 E MessageQueue-JNI: android.os.NetworkOnMainThreadException

Needs to be shown that it doesn't happen on the same version of AOSP because I don't see an OS issue.

**Comment by thelifeofjay** [comment]
@thestinger I'll get logcat output from AOSP shortly
