### ISSUE TITLE
Can't change "Silence alarm after" in clock settings

### ISSUE THREAD

**Issue by sdukhovni** [copperhead/bugtracker#646]
When I go into the settings of the built-in clock app on CopperheadOS, and change "Silence alarm after" to "Never", the setting goes back to the default "10 minutes" after closing and reopening the app.

**Comment by thestinger** [comment]
This is an upstream AOSP issue, not a CopperheadOS issue.

**Comment by regagain** [comment]
I reported this issue on the Android issue tracker some time ago: https://issuetracker.google.com/issues/37138380 (note: sadly, it seems a google account is required to view this page).

**Comment by thestinger** [comment]
If someone provides a clean patch, I'll apply it.

**Comment by thestinger** [comment]
Since it's an upstream issue not caused by or uncovered by a CopperheadOS feature, I'm going to close this issue. It doesn't make sense for us to have an issue filed for every upstream bug. As I said, I'll accept a patch fixing the problem.
