### ISSUE TITLE
PERMISSIONS_REVIEW_REQUIRED Bluetooth and WiFi toggle controls are half-baked / broken

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#655]
These can be disabled for now as a quick solution to go back to how things were before.

**Comment by thestinger** [comment]
The feature has been disabled for these components in the development branch until it's improved for them.

**Comment by theGrower** [comment]
Verifying I have the problem on 6P. Among others.

**Comment by thestinger** [comment]
It's confirmed as an upstream issue and resolved in the CopperheadOS development branch now.

**Comment by thestinger** [comment]
This is worked around by N2G48B.2017.07.06.18.26.24.
