### ISSUE TITLE
various bugs with update N2G48B.2017.07.06.00.04.39 release

### ISSUE THREAD

**Issue by theGrower** [copperhead/bugtracker#656]
K-9 and ProtonMail app will not load email content. 
Built in WiFi network sign in page (web view?) Will not load log in page. 
Quick toggle controls for WiFi and Bluetooth broken ( I know there is another post for this).

Overall data connection slowed as well.

**Comment by thestinger** [comment]
Please file separate issues for each problem: https://github.com/copperhead/bugtracker#reporting-issues. Going to need more details too.
