### ISSUE TITLE
ProtonMail APK will no longer load emails after update: N2G48B.2017.07.06.00.04.39 release

### ISSUE THREAD

**Issue by theGrower** [copperhead/bugtracker#658]
emails will be fetched into the app from server; however, upon attempting to open the email no content will be loaded. The email remains a blank space. The "Display Images" button does not work either.

**Comment by thestinger** [comment]
Please upgrade to N2G48B.2017.07.06.18.26.24 and try there.

**Comment by theGrower** [comment]
Upgraded and still having the same problem. Tried to clear data and cache and them sign back in and still will not load the emails. I'll have to get logs tomorrow.

**Comment by thestinger** [comment]
Need to know if the included Chromium app is working for you. You can't have it disabled, for example.

**Comment by theGrower** [comment]
After enabling Chromium for a different issue, the email is now loading ... I don't understand.

**Comment by thestinger** [comment]
Chromium provides the WebView. There were previously two copies of Chromium, one for the browser and one for the WebView. There's no longer a redundant copy of it.

**Comment by theGrower** [comment]
Ah Ha! I get it! Thank you good sir!
