### ISSUE TITLE
SIP not working

### ISSUE THREAD

**Issue by greatuser2** [copperhead/bugtracker#662]
I tried sip calling in the default phone app and in ring over udp on Nexus 5x. The phone app gives me a "Server error. Try again later." error when calling and Ring can't register (with sip). I used a sip account that works great on my computer and other computers. I first experienced this issue on June the 9th (it may have appeared earlier) and sip was working on previous versions of Copperhead os.

**Comment by mke208** [comment]
It works fine for me on copperheados-nougat-mr2-release built from source.
Android native SIP client is quite dumb (cannot choose codecs, it does not seem to support SIP SRV records, etc) but integratio is nice ... Have you tried Linphone sip client ?

**Comment by greatuser2** [comment]
It looks like something has changed since I made some tests a few weeks ago. Sorry for not having re-tested everything right before submitting the bug. I'm going to test a bit more and post back if something goes wrong.

**Comment by mke208** [comment]
My device is Pixel XL, you said you have the issue on N5X. Different devices might experience different issues ...

**Comment by greatuser2** [comment]
I have tested it again. 
I tried to use Linphone with a Linphone SIP account. It worked with TLS transport. However, with TCP or UDP transport, I had a "failed to register error". I had the same result with another UDP-only account.

The mistake I made in my first comment is that the default phone app gives me "Server error" message when trying to call over sip.

**Comment by mke208** [comment]
In Linphone you can go to Settings -Network and toggle 'use random ports'.
If it uses port 5060 it conflicts with the native SIP client ...

**Comment by greatuser2** [comment]
This option was already enabled. Disabling it didn't make things better.

**Comment by thestinger** [comment]
If you have a VPN enabled (including a non-VPN app based on intercepting traffic / DNS via VPN service), try turning it off.

**Comment by mke208** [comment]
So the SIP client registers with the server, but you cannot call ?

**Comment by greatuser2** [comment]
I had no VPN or similar app enabled.
As far as I know, the default phone app doesn't indicate if it is registered (I think that it registers only when calling). Linphone and Ring don't register.

**Comment by mke208** [comment]
It does register if you enable "Receive incoming calls". When you enable this option and go to "Sip Accounts",it should say "Receiving calls" under the account if registered, or some error if not.
Does your SIP provider by any chance use SIP SRV records, and did you try to put the SIP server's IP address instead of domain name under the account settings ?

**Comment by greatuser2** [comment]
I have enabled "Receive incoming calls" and it registered successfully and I could even make and receive calls! It still doesn't work without incoming calls enabled.
For some reason, Linphone now registers with the Linphone sip account but not on the other one whose server has no domain name but only an ip address.

**Comment by thestinger** [comment]
I don't think this is a CopperheadOS issue. It would need to be confirmed that this doesn't occur for you on a fresh install of stock Android but does on a fresh install of CopperheadOS.

**Comment by mke208** [comment]
Correct, it might be an issue with the OP's sip server or setup. SiP takes into account a lot of things, like router/firewall set-up, different authentication schemes, some providers blocking it, etc. Maybe at some point Google will improve Android's native sip calling to add SRV, ZRTP and other features, but that's beyond the scope of this project.
