### ISSUE TITLE
Missed call notification LED

### ISSUE THREAD

**Issue by mke208** [copperhead/bugtracker#663]
Speaking of the previous SIP issue, can someone else check if the notification LED blinks on missed call ? 
Mine does not seem to ... 
Device Pixel XL copperheados-nougat-mr2-release
Blink Notification Light is enabled, Linphone and other apps do make the LED blink

Edited for more clarification and details:
Android native sip client, phone in plane mode and over WiFi. When you have a missed call, the "Missed Call" notification is shown, but the LED is not blinking even if "blink notification light" active in settings. 
I cannot confirm this behavior with "regular" calls as i only use the phone with data and SIP calling, and i normally use Linphone. On Linphone the missed call notification makes the LED blink btw. 
Identical behavior on another device running LineageOS 7.0.2, so i guess this is an upstream issue, and obviously of very low importance, as the native android SIP calling is quite primitive anyway, with lots of missing features for a modern SIP client, but maybe someone cares.  

Off topic: you can make a change to device/*/*/liblight/lights.c and set
#define LIGHTS_SUPPORT_BATTERY 1
you get a nice red blinking light when battery is low and different colors when charging, it works on Pixel XL and i am pretty sure it will work on all devices.

**Comment by greatuser2** [comment]
Checked on Nexus 5x with "regular" calls. The LED doesn't blink.

**Comment by thestinger** [comment]
The notification LED only blinks if an app requests it for a notification. This is working as they intended, the same way as stock Android. It's not within the scope of this issue tracker.
