### ISSUE TITLE
Missed calls in Noise

### ISSUE THREAD

**Issue by sdukhovni** [copperhead/bugtracker#664]
I'm trying to use Noise to video call Signal users, but when I call them, I get "recipient unavailable" after a few rings, and when they call me I just see "missed call" in the chat log but never get a chance to pick up the call.

**Comment by thestinger** [comment]
This issue tracker doesn't cover Noise, and Noise doesn't make any changes to the Signal code anyway. If you're convinced it's a problem with Noise, you can use Signal instead.
