### ISSUE TITLE
Majority of web browsers not working after a recent update.

### ISSUE THREAD

**Issue by kittenpirate** [copperhead/bugtracker#679]
Running a Nexus 6p with the latest OS version.

With the exception of Icecat, other browsers aren't loading anything. This started recently but i'm not sure eactly when. BeHe & Firefox Klar are both browsers that are affected by this new problem. BeHe was working fine and one day it just stopped loading after an update. The status bar on affected browsers hangs in the same place. I've tried uninstalling and reinstalling the browsers but nothing is working. I want to get off Icecat because it is old but It is the only thing that is loading.

**Comment by thestinger** [comment]
If you've disabled Chromium, you can't do that. There used to be two whole builds of Chromium, one providing the WebView apk and the other providing the Chromium browser. There's now a single one providing both so if you disable it you don't have the WebView and most apps render web content with the Chromium WebView.
