### ISSUE TITLE
Disabling com.qualcomm.atfwd?

### ISSUE THREAD

**Issue by JusticeRage** [copperhead/bugtracker#693]
Hi!
While playing with DNS logging on my network, then NetMonitor on the phone, I have noticed that `com.qualcomm.atfwd` sends data to `telemetry.nvidia.com` which I don't really like. Based on the [information](https://forum.xda-developers.com/moto-g/help/com-qualcomm-atfwd-service-bloatware-t2820010) I have found, this service is used to cast the device's screen over WiFi, a feature I have no use for. However, the app cannot be disabled.
Would you consider allowing this APK to be disabled, or removing it completely from the distribution if it isn't used?

**Comment by thestinger** [comment]
See https://www.reddit.com/r/CopperheadOS/comments/6sunpd/system_connected_to_something_like/dlfoxv4/. Net Monitor is wrongly attributing all UID 1000 app connections to atfwd. Even then, I doubt any UID 1000 app is making a connection to `telemetry.nvidia.com` themselves. Apps can make network requests through APIs exposed by other apps. For example, DownloadManager can be used to perform async downloads by apps with the INTERNET permission.

**Comment by JusticeRage** [comment]
Thanks for clarifying this and apologies for the misguided report.
I'll still have to look deeper into this, because I don't see any legitimate app, system or otherwise, which should send telemetry data to Nvidia.

**Comment by thestinger** [comment]
If it's attributed to atfwd, that means it's an app with uid 1000, but it's probably done by another app via an API. For example, maybe you have a game installed that uses an NVIDIA library doing this.

Net Monitor can accurately get data on all the outgoing connections but it can't always meaningfully attribute it to the real sources. I filed an issue about this, but the solution is probably just fixing the output to show all possible apps that could have made the connection, and in this case I don't think any of them made it directly but rather another app did it through them. For example, via DownloadManager.

https://github.com/SecUSo/privacy-friendly-netmonitor/issues/40

**Comment by thestinger** [comment]
Maybe there's a way to retrieve DownloadManager logs via adb, I'll have a look for you because I'm curious about it.

**Comment by JusticeRage** [comment]
Le me know if you need a list of my installed apps! There shouldn't be any game in the list.
