### ISSUE TITLE
add back Nexus 6P support for Android Oreo

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#702]

**Comment by poshul** [comment]
I have a 6P and would be happy to help with this endevour. Please let me know what needs to happen.

**Comment by thestinger** [comment]
The first step is adding back support to https://github.com/anestisb/android-prepare-vendor similar to https://github.com/anestisb/android-prepare-vendor/pull/82.

**Comment by poshul** [comment]
As of 794db59bb5afad7c840822e3b26d85dc8ce23731 android-prepare-vendor works for both naked and full config, and compiles a copperhead image successfully.

**Comment by thestinger** [comment]
This is available again but it doesn't fully work yet. Thanks for working on android-prepare-vendor to get most of this done.
