### ISSUE TITLE
nexus 5x crashed, now won't boot

### ISSUE THREAD

**Issue by ntouvaris** [copperhead/bugtracker#712]
hello there,
messenger crashed on my nexus 5x and now won't boot pass the google screen.
i got into recovery wiped data and cache with no luck.
i also tried this https://forum.xda-developers.com/nexus-5x/help/req-help-to-unbrick-t3251740/page2 and this https://drive.google.com/file/d/0Bz6x7k-VkpUJam5Mc1hKa09PVGc/view but when i try to sideload the OTA (copperhead or official) the process stops at 3%.

> akiss-MBP:platform-tools akis$ ./adb sideload bullhead-ota_update-2017.08.21.00.41.27.zip 
opening 'bullhead-ota_update-2017.08.21.00.41.27.zip'...
connecting...
serving: 'bullhead-ota_update-2017.08.21.00.41.27.zip'  (~3%)    * failed to read command: Undefined error: 

> 0

i don't care much about the data as i have a recent backup.
just want to have a working phone again.

any ideas are welcome

**Comment by ntouvaris** [comment]
i forgot to mention that my device is locked.
fast boot flashing unlock and fast boot gem unlock won't work.

**Comment by thestinger** [comment]
> just want to have a working phone again.

This appears to be a hardware failure. It's not something that can be filed here as a bug.
