### ISSUE TITLE
Secondary PIN that opens Guest Account

### ISSUE THREAD

**Issue by Nutomic** [copperhead/bugtracker#730]
As described in this post:

https://crimethinc.com/2017/09/01/smart-phone-feature-request-guest-mode-a-proposal-for-data-privacy-while-phone-sharing

**Comment by thestinger** [comment]
And then what happens when this realize you did this since it will be obvious? I don't think this is a good solution for this.

**Comment by thestinger** [comment]
A duress password is a feature that will be considered, but it needs to be implemented in a good way. It should only be an open issue here once there's a proper plan for it already. Enhancements filed here need to be actionable issues, not open ended ideas.

**Comment by Nutomic** [comment]
Okay that makes sense.
