### ISSUE TITLE
If i wipe via 30 wrong password inputs, do i get a brick?

### ISSUE THREAD

**Issue by tirlbk** [copperhead/bugtracker#735]
What do I get? 

Currently I have nothing but a guest acct because the bootloader is locked and I forgot owner's password, which means I cannot enable USB debug or use adb, etc.

**Comment by thestinger** [comment]
No, it just does a factory reset. It doesn't work like this anymore on current generation devices with the new encryption format. There's no anti-theft protection for CopperheadOS on Nexus phones if you have a boot password set, since it can't retrieve whether it *should* wipe.

**Comment by thestinger** [comment]
Not the right place to ask questions though.

**Comment by thestinger** [comment]
I don't really understand the question since you say a guest account works anyway, implying no boot password, in which case you can't wipe without the password.

**Comment by tirlbk** [comment]
I have the boot password, just not the lock screen pattern. I can only access a guest account, which cannot enable USB debug / dev options.

This is a Nexus 5 2016.06.06 version. (Yes, I know, deprecated.)

 Sorry for the wrong place... Not used to github on a phone. 

A factory reset would be great because the phone is almost a brick as is. I'd like to recover the data but it seems not doable so a reset would be great.

**Comment by thestinger** [comment]
If it's a Nexus 5 just fastboot flashing unlock it. We haven't supported the Nexus 5 for a long time.

> Sorry for the wrong place... Not used to github on a phone.

GitHub issue tracker isn't for support.
