### ISSUE TITLE
LTE (recommended) doesn't work on 5X

### ISSUE THREAD

**Issue by mople71** [copperhead/bugtracker#742]
**Steps to reproduce:** open *Preferred network type* and tap *LTE (recommended)*

**Expected behavior**: option *LTE (recommended)* should already be selected and should be activated upon selecting

**What really happens:** option *LTE (recommended)* is not selected by default and turns on *LTE only* upon selecting

**Comment by thestinger** [comment]
I'll try to get it fixed for the next release.

**Comment by thestinger** [comment]
Resolved by the latest release along with the DeskClock issues: https://www.reddit.com/r/CopperheadOS/comments/717ag3/copperheados_opr41706230062017091921_release/.
