### ISSUE TITLE
Update angler-ota_update-2017.09.19.22 download repeatedly fails

### ISSUE THREAD

**Issue by clayt0nk** [copperhead/bugtracker#745]
Currently running N2G48C.2017.08.21.00.41.27 on a Nexus 6P.

Whether direct or over VPN, the download seems to be reliably clobbered about 3/4 through. I have had this phone for most of a year now(?) and previous updates have given me zero problems.

This one seems to be particularly big. I also live in China, where the network generally sucks.

The biggest issue really is the inability to resume an interrupted download.

Any suggestions? Can I wget it and then sideload?

**Comment by thestinger** [comment]
> This one seems to be particularly big.

You've probably only been using the incremental updates before and there isn't one for the upgrade to Oreo because it's so large.

> The biggest issue really is the inability to resume an interrupted download.

One of the reasons that a new Updater was developed for Pixels.

> Any suggestions? Can I wget it and then sideload?

Sure, you can do that.
