### ISSUE TITLE
android-prepare-vendor broken ?

### ISSUE THREAD

**Issue by xbtc-im** [copperhead/bugtracker#761]
android-prepare-vendor script does not create device-vendor-marlin.mk correctly,
more specific this part:

# Standalone symbolic links
PRODUCT_PACKAGES += \
    wcd9320_anc.bin__wcd9320_anc.bin \
    wcd9320_mad_audio.bin__wcd9320_mad_audio.bin \
    mbhc.bin__wcd9320_mbhc.bin

Obviously, the build will be broken and will not boot ...

The .mk file taken from your previous vendor folder that used to be hosted on github contains the following:

# Standalone symbolic links
PRODUCT_PACKAGES += \
    wcd9320_anc.bin__wcd9320_anc.bin \
    wcd9320_mad_audio.bin__wcd9320_mad_audio.bin \
    mbhc.bin__wcd9320_mbhc.bin \
    toybox_vendor__acpi \
    toybox_vendor__base64 \
    toybox_vendor__basename \
    toybox_vendor__blockdev \
    toybox_vendor__cal \
    toybox_vendor__cat \
    toybox_vendor__chcon \
    toybox_vendor__chgrp \
    toybox_vendor__chmod \
    toybox_vendor__chown \
    toybox_vendor__chroot \
    toybox_vendor__chrt \
    toybox_vendor__cksum \
    toybox_vendor__clear \
    toybox_vendor__cmp \
    toybox_vendor__comm \
    toybox_vendor__cp \
    toybox_vendor__cpio \
    toybox_vendor__cut \
    toybox_vendor__date \
    toybox_vendor__df \
    toybox_vendor__dirname \
    toybox_vendor__dmesg \
    toybox_vendor__dos2unix \
    toybox_vendor__du \
    toybox_vendor__echo \
    toybox_vendor__env \
    toybox_vendor__expand \
    toybox_vendor__expr \
    toybox_vendor__fallocate \
    toybox_vendor__false \
    toybox_vendor__file \
    toybox_vendor__find \
    toybox_vendor__flock \
    toybox_vendor__free \
    toybox_vendor__getenforce \
    toybox_vendor__getprop \
    toybox_vendor__groups \
    toybox_vendor__head \
    toybox_vendor__hostname \
    toybox_vendor__hwclock \
    toybox_vendor__id \
    toybox_vendor__ifconfig \
    toybox_vendor__inotifyd \
    toybox_vendor__insmod \
    toybox_vendor__ionice \
    toybox_vendor__iorenice \
    toybox_vendor__kill \
    toybox_vendor__killall \
    toybox_vendor__ln \
    toybox_vendor__load_policy \
    toybox_vendor__log \
    toybox_vendor__logname \
    toybox_vendor__losetup \
    toybox_vendor__ls \
    toybox_vendor__lsmod \
    toybox_vendor__lsof \
    toybox_vendor__lsusb \
    toybox_vendor__md5sum \
    toybox_vendor__microcom \
    toybox_vendor__mkdir \
    toybox_vendor__mknod \
    toybox_vendor__mkswap \
    toybox_vendor__mktemp \
    toybox_vendor__modinfo \
    toybox_vendor__modprobe \
    toybox_vendor__more \
    toybox_vendor__mount \
    toybox_vendor__mountpoint \
    toybox_vendor__mv \
    toybox_vendor__netstat \
    toybox_vendor__nice \
    toybox_vendor__nl \
    toybox_vendor__nohup \
    toybox_vendor__od \
    toybox_vendor__paste \
    toybox_vendor__patch \
    toybox_vendor__pgrep \
    toybox_vendor__pidof \
    toybox_vendor__pkill \
    toybox_vendor__pmap \
    toybox_vendor__printenv \
    toybox_vendor__printf \
    toybox_vendor__ps \
    toybox_vendor__pwd \
    toybox_vendor__readlink \
    toybox_vendor__realpath \
    toybox_vendor__renice \
    toybox_vendor__restorecon \
    toybox_vendor__rm \
    toybox_vendor__rmdir \
    toybox_vendor__rmmod \
    toybox_vendor__runcon \
    toybox_vendor__sed \
    toybox_vendor__sendevent \
    toybox_vendor__seq \
    toybox_vendor__setenforce \
    toybox_vendor__setprop \
    toybox_vendor__setsid \
    toybox_vendor__sha1sum \
    toybox_vendor__sha224sum \
    toybox_vendor__sha256sum \
    toybox_vendor__sha384sum \
    toybox_vendor__sha512sum \
    toybox_vendor__sleep \
    toybox_vendor__sort \
    toybox_vendor__split \
    toybox_vendor__start \
    toybox_vendor__stat \
    toybox_vendor__stop \
    toybox_vendor__strings \
    toybox_vendor__swapoff \
    toybox_vendor__swapon \
    toybox_vendor__sync \
    toybox_vendor__sysctl \
    toybox_vendor__tac \
    toybox_vendor__tail \
    toybox_vendor__tar \
    toybox_vendor__taskset \
    toybox_vendor__tee \
    toybox_vendor__time \
    toybox_vendor__timeout \
    toybox_vendor__top \
    toybox_vendor__touch \
    toybox_vendor__tr \
    toybox_vendor__true \
    toybox_vendor__truncate \
    toybox_vendor__tty \
    toybox_vendor__ulimit \
    toybox_vendor__umount \
    toybox_vendor__uname \
    toybox_vendor__uniq \
    toybox_vendor__unix2dos \
    toybox_vendor__uptime \
    toybox_vendor__usleep \
    toybox_vendor__uudecode \
    toybox_vendor__uuencode \
    toybox_vendor__vmstat \
    toybox_vendor__wc \
    toybox_vendor__which \
    toybox_vendor__whoami \
    toybox_vendor__xargs \
    toybox_vendor__xxd \
    toybox_vendor__yes \
    eglSubDriverAndroid_64.so__eglSubDriverAndroid.so \
    libEGL_adreno_64.so__libEGL_adreno.so \
    libGLESv1_CM_adreno_64.so__libGLESv1_CM_adreno.so \
    libGLESv2_adreno_64.so__libGLESv2_adreno.so \
    libq3dtools_adreno_64.so__libq3dtools_adreno.so \
    libq3dtools_esx_64.so__libq3dtools_esx.so \
    eglSubDriverAndroid_32.so__eglSubDriverAndroid.so \
    libEGL_adreno_32.so__libEGL_adreno.so \
    libGLESv1_CM_adreno_32.so__libGLESv1_CM_adreno.so \
    libGLESv2_adreno_32.so__libGLESv2_adreno.so \
    libq3dtools_adreno_32.so__libq3dtools_adreno.so \
    libq3dtools_esx_32.so__libq3dtools_esx.so

A lot more links ... The weird thing is that android-prepare-vendor creates the makefile for Sailfish correctly ... 

Replacing the links part in device-vendor-marlin.mk resulted in a successful build ... 

Am i missing something ?

**Comment by thestinger** [comment]
It's working fine here, and this isn't where android-prepare-vendor is maintained.

https://github.com/anestisb/android-prepare-vendor

**Comment by xbtc-im** [comment]
what OS are you using ? mine is ubuntu 16.04 lts. for me the links part is always broken. And since you forked it, prepare-vendor is maintained here ...

**Comment by thestinger** [comment]
No, it's not maintained here or meaningfully forked. It's part of source tree so that the android-prepare-vendor revision used to build our releases is tagged as part of them.

**Comment by xbtc-im** [comment]
Weird. Sailfish is ok, marlin not, and only for the links part. I will look into it, if i find something i will let you know. 
Meanwhile, since i do appreciate your work, do you take donations ?

**Comment by xbtc-im** [comment]
never mind, i did not pay attention. 
https://blockchain.info/tx/ce6c831ab22466a219798864bd36a314df0647d3f0c4865be3361c3d50d981b7

**Comment by thestinger** [comment]
Ah maybe you're running into the fact that the sailfish vendor file setup is a bit weird. Note that it puts some sailfish files in the marlin directory too.

**Comment by thestinger** [comment]
It makes this too:

```
android-prepare-vendor/sailfish/opr3.170623.008/vendor/google_devices/
└── marlin
    ├── BoardConfigVendor.mk
    └── device-vendor-sailfish.mk
```

**Comment by xbtc-im** [comment]
yes i guess i missed that. my bad.

**Comment by thestinger** [comment]
The documentation could be improved but I needed to get it updated quickly so it doesn't cover all of the fine details for this yet and just uses marlin as an example.

**Comment by xbtc-im** [comment]
Well, you are 1 or two working on this project ... i guess you have done enough already... it's open source but you have to think a bit for yourself :)

**Comment by xbtc-im** [comment]
Is the paid version of CopperheadOS any different from the github version ? Obviously except the signing keys .... ?

**Comment by thestinger** [comment]
No.

**Comment by xbtc-im** [comment]
Alright. Would you be interested, maybe at some point in the future, in some cooperation ? Ideas, investments maybe ?

**Comment by xbtc-im** [comment]
We deal in cryptocurrency, and obviously your project goes very well with us. Right now we use CopperheadOS on a few devices, in house, nothing commercial, but in the future ,who knows ?

**Comment by thestinger** [comment]
You should talk to contact james.donaldson@copperhead.co about that.

**Comment by xbtc-im** [comment]
Well maybe you could forward this to him. This thread is pretty clear i guess ...
