### ISSUE TITLE
Update Notification ignores DND setting

### ISSUE THREAD

**Issue by Gamer1204** [copperhead/bugtracker#763]
Hello,

The last 2 weeks I have had 3 update notification for the copperhead OS making sound even though I had Do Not Disturb on. I checked the notification settings and it is said to the highest notification priority, but the "ignore DND settings" is set to false. I lowered the priotity hoping it won't wake me up again, but I fear that it just ignored the "ignore DND settings".

I am using the NExus 5x(Bullhead) with the latest software(obviously not before the notifications).

Cheers,
Gamer1204

**Comment by thestinger** [comment]
That's because it uses `setCategory(Notification.CATEGORY_SYSTEM)` and those bypass the zen mode. We'll consider changing it now that notification channels exist.
