### ISSUE TITLE
Play Services Network Requests on Android O Builds

### ISSUE THREAD

**Issue by securesearch** [copperhead/bugtracker#768]
Noticed that alongside the Google connectivity check that was also present in builds based on Android N, Android O builds also attempt to connect to *play.googleapis.com* every time a network interface is enabled. Haven't narrowed down the process making the requests, but just seems unnecessary when CopperheadOS does not use or need Play services.

**Comment by xbtc-im** [comment]
that's in frameworks/base/services/core/java/com/android/server/connectivity/NetworkMonitor.java
private static final String DEFAULT_OTHER_FALLBACK_URLS =
"http://play.googleapis.com/generate_204";

all connectivitycheck servers are there ... they can be changed from source or maybe an user configurable option could be added at some point ...

**Comment by thestinger** [comment]
https://copperhead.co/android/docs/usage_guide#default-connections-made-by-copperheados

**Comment by thestinger** [comment]
@xbtc-im They are user configurable via adb shell but I doubt you want to point them at something else, it wouldn't improve privacy. It would only make the device behave uniquely instead of fetching the same URLs as billions of other devices. They are empty GET requests.

**Comment by thestinger** [comment]
They also need to return a 204 status, not something else. It detects captive portals from the captive portal sending a 200 request, etc. instead.

**Comment by xbtc-im** [comment]
Yes, it expects a 204 No Content. As far as i know captive portal detection can even be disabled via adb shell, but it can prove useful for captive portals, splash pages, spent data plans, etc.  It works as intended.

**Comment by thestinger** [comment]
The internet connectivity checking is also used to fall back to other networks when once isn't providing working internet access.
