### ISSUE TITLE
Latest Changelog

### ISSUE THREAD

**Issue by razaborg** [copperhead/bugtracker#779]
Hi,

I have a working CopperheadOS version  (build n° OPR6.170623.017.2017.09.19.22 ) and I wanted some information about the latest OTA before upgrading, so I looked up for a changelog...

Here is the changelog of the latest version : https://update.copperhead.co/changelog/2017.09.24.15.txt

> Release notes for Copperhead OS #2017.09.24.15
>---
>- Add bullet point here
>- Another bullet...

And there is no place where we can find the actual diff of the latest OTA. 
What are the patched things ? What are the new stuff brought by this update ?

**Comment by thestinger** [comment]
update.copperhead.co is an obsolete server that's not used anymore and 2017.09.24.15 is far from the latest version. I don't know why you're looking there.

The changelogs are posted on Reddit if you don't want to diff the tags in the Git repositories.

https://www.reddit.com/user/strncat/submitted/
