### ISSUE TITLE
add Pixel 2 XL support

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#781]

**Comment by poshul** [comment]
I'm looking at getting one of the 2 XL's what is the status of support? Is there anything specific I could do to help?

**Comment by thestinger** [comment]
I don't know since I don't have one. I know a build completes, I don't know if it boots or what problems it will have. I only have a non-XL Pixel 2 and the Pixel 2 and Pixel 2 XL are much different from each other this year, unlike the Pixel and Pixel XL where I could fairly safely assume the XL works based on the smaller one works.

**Comment by thestinger** [comment]
There will be porting work once it actually boots too.

**Comment by thestinger** [comment]
This is implemented now.
