### ISSUE TITLE
Security Enhancement: Quick Settings message preview

### ISSUE THREAD

**Issue by ricorselt** [copperhead/bugtracker#798]
When enabling 'Screen Security' in Noise, I am unable to take screenshots of message content and the message list. However, I am still able to take screenshots of messages and their content from the Android Quick Settings drop-down menu(sliding down from the top while unlocked). Would it be possible to have CopperheadOS not show message previews in the Quick Settings menu and make that the default setting? 

Thank you.

**Comment by sigenc** [comment]
You can turn them off under the Settings in Noise

**Comment by ricorselt** [comment]
Embarrassing I didn't notice this. Thank you @sigenc.
