### ISSUE TITLE
Flashing full image - not enough space

### ISSUE THREAD

**Issue by jo3l33** [copperhead/bugtracker#802]
Hi, 
I am just flashing latest full image of Copperhead on new Nexus 5X. Device is unlocked. Image extracted. Running flash-all.bat on win 7 getting error of not enough space. Disk has over 25gb free space, 10gb swap, 14gb RAM. Tried redownload the latest image - didn't help. 

What may I try to flash sucessfully ? Thank you very much for help! 
![copperhead](https://user-images.githubusercontent.com/19603866/33455470-76b3caa2-d61c-11e7-96dd-4672b9841be2.jpg)

**Comment by thestinger** [comment]
You need to ask in https://www.reddit.com/r/CopperheadOS/, support isn't offered here.
