### ISSUE TITLE
Phone app silently crashing when opening details of some calls (missed, incoming, outgoing)

### ISSUE THREAD

**Issue by xTMxTM** [copperhead/bugtracker#803]
Running CopperheadOS 2017.11.20.01 release on Nexus 5X. Does not seem to be linked to specific contacts as some entries of the same contact work and some not. Phone app just closes without any notice.

**Comment by thestinger** [comment]
You'll need to provide logs from `adb logcat`.

**Comment by thestinger** [comment]
You'll need to try the latest release based on Android 8.1 since it has a new version of the Telephony infrastructure and Dialer so it's substantially different.

**Comment by xTMxTM** [comment]
Problem is gone with 8.1
