### ISSUE TITLE
Hidden ESSID WiFi Connectivity Problem - 2017.12.07.19 Legacy Device

### ISSUE THREAD

**Issue by cypherpunkglobal** [copperhead/bugtracker#806]
Post-update to release 2017.12.07.19 (8.1) I can no longer get a legacy Copperhead device I use to connect (both manually and automatically to saved networks) to WiFi networks with hidden ESSIDs. 

There are networks I need to access which I don't manage that are configured in this way. The device connects to and discovers networks which broadcast ESSIDs just fine. I have reset network settings, rebooted multiple times, checked logcat for references to wifi errors and found nothing.

I have been trying to work out whether I can get the device to connect manually using adb with "am" and an intent to perhaps remedy the situation permanently or at least get some more data to debug the problem, but it would seem that the documentation I found is either irrelevant or outdated.

According to https://developer.android.com/things/hardware/wifi-adb.html (realize that it is now start-service not startservice)

	am start-service -n com.google.wifisetup/.WifiSetupService -a WifiSetupService.Connect -e ssid <network_ssid> -e passphrase <network_pass> --ez hidden true

would be the way to connect manually to a hidden wifi network via adb. This does not work, however.

However, since

	$ service list | grep -e wifi -e Wifi                                                                                       

	wifip2p: [android.net.wifi.p2p.IWifiP2pManager]
	rttmanager: [android.net.wifi.IRttManager]
	wifiscanner: [android.net.wifi.IWifiScanner]
	wifi: [android.net.wifi.IWifiManager]
	wificond: []

suggests that "com.google.wifisetup" isn't present on CopperheadOS, I presume one of the above services (or another?) could be used with an appropriate intent to connect, but I have not been able to find the relevant documentation.

Would be great if someone could check if this issue is reproducible, and perhaps point me in the right direction. 

I realize not broadcasting ESSIDs does not really hide APs at all, but as I said, I don't manage the networks, and the documentation I found suggests Android should be able to connect to such networks, so this would seem like a bug. I hope I haven't just overlooked something, and realize that to be sure it isn't a configuration issue a full factory reset is necessary, but I am not able to do this at this time.

**Comment by thestinger** [comment]
It's probably an upstream issue and not something that we're likely to do any work on.

**Comment by thestinger** [comment]
If someone else identifies a fix we can apply that but Google might fix it before anyone else gets to it, or it might just sit here like this for a long time like many other issues.

**Comment by cypherpunkglobal** [comment]
Would you happen to know which service (instead of com.google.wifisetup) can currently be sent an intent via adb am to connect to a specific AP and the relevant parameters? Or if not, know of the relevant documentation, or where in the source to look?

**Comment by thestinger** [comment]
No, I don't know anything about this.

**Comment by thestinger** [comment]
Is this still an issue on the current release?

**Comment by thestinger** [comment]
I'll need feedback to know if I should keep this open.
