### ISSUE TITLE
Couldn't find remote ref ... OPM1.171019.011.2017.12.07.19

### ISSUE THREAD

**Issue by EnSec4Git** [copperhead/bugtracker#807]
When building Copperhead from source, on the first step for compiling for Nexus 5X, upon trying to `repo init -u https://github.com/CopperheadOS/platform_manifest.git -b refs/tags/OPM1.171019.011.2017.12.07.19`, I receive the following error: `fatal: Couldn't find remote ref refs/tags/OPM1.171019.011.2017.12.07.19`.
The TAG_NAME I use is from https://copperhead.co/android/downloads .
When I checked a list of both releases and tags at https://github.com/CopperheadOS/platform_manifest/tags , I cannot see a tag with such name.
Please advise.

**Comment by thestinger** [comment]
You'll need to wait for the next release or build the development branch. I don't have the usual infrastructure set up for Nexus devices on Oreo yet so there are no tags.
