### ISSUE TITLE
Apply for the Pineapple Fund

### ISSUE THREAD

**Issue by sigenc** [copperhead/bugtracker#810]
Hey strncat,

visit this site and please apply.

https://pineapplefund.org/

Sorry for posting this here. Can't remember my reddit acc.

**Comment by thestinger** [comment]
We're not a charity.

**Comment by sigenc** [comment]
Doesn't matter. 


> The Pineapple Fund supports a diverse range of charitable causes worldwide. If you're doing anything worthwhile, we invite you to apply!
> 
> Your organization should be a registered nonprofit organization in your country. **_In exceptional circumstances, we may make exceptions. You're welcome to apply._**
> 
> We will transfer the donation 'in-kind' via bitcoin. Don't know how to accept and convert? We can help!
>

**Comment by sigenc** [comment]
I and many other think, what you do is very important for humanity. If it was my wallet, be sure i would give you a living worth of btc's just to continue your work. I feel so sorry that there are people stealing your time and making money with it. Nobody even seems to cares to donate big money for what you do. I can't code or have the ability to contribute in any other way than ideas. I would try to explain to that person why it is important that you stay motivated with what you do and explain why it is important to have such hardened devices. 

Big respect for keeping up the work even with all that bullshit around you. I'm still on the official build for Nexus 6p, but as soon as Pixel 2 hits the stage im in for buying it directly from you.

Thank you
