### ISSUE TITLE
Copperhead brick phone / no sim card unlock

### ISSUE THREAD

**Issue by beli3ver** [copperhead/bugtracker#811]
Hi,

for two days I get a OTA update for copperhead. After the Installation I cannot unlock my sim card. I always get a error.
I changed the sim tested it with others phones there it works.
I tried to install lineage, but there it didn't works too.

So i installed the factory image from here

https://developers.google.com/android/images

But no chance, the phone could not unlock the sim card.
So my question what could I do to fix it?
Is there a special Firmware for that ?
Thanks

**Comment by thestinger** [comment]
The issue tracker isn't used for customer support.
