### ISSUE TITLE
Nexus 5x Support for a separate encryption password

### ISSUE THREAD

**Issue by no1tuta** [copperhead/bugtracker#812]
Hello. I keep reading how copperhead is supposed to have support for setting a different disk encryption password than the lockscreen. This feature is not available is any of the builds for the Nexus 5x that I have used.

There is no menu entry under security >encryption & credentials > Encryption. It only says "encrypt phone" and "Encrypted".

in the copperhead os documentation, it says that there should be an option here
https://copperhead.co/blog/2015/07/08/android-encryption-password

**Comment by thestinger** [comment]
> in the copperhead os documentation, it says that there should be an option here

No, it doesn't. You're linking to a blog post from 2015, not our documentation.

**Comment by thestinger** [comment]
This feature is incompatible with the improved encryption implementation on Pixel phones and later so it wasn't ported to Nougat. It hasn't been around for a year. The documentation explains that: https://copperhead.co/android/docs/technical_overview#past-features.

If you want to work on implementing https://github.com/copperhead/bugtracker/issues/451 for AOSP, you can do that. So far, there hasn't been anyone that has started work on it and we have much higher priorities than implementing brand new major features.
