### ISSUE TITLE
Can't built latest Pixel XL tag

### ISSUE THREAD

**Issue by Rudd-O** [copperhead/bugtracker#862]
```
ANDROID_BUILD_ID=OPM2.171019.029
ANDROID_BUILD_SPEC=marlin-stable-release-user
ANDROID_BUILD_TAG=OPM2.171019.029.2018.04.19.04
ANDROID_BUILD_TIME=2018.04.19.04
...
...
...
Fetchremote: Not Found
fatal: repository 'https://bitbucket.org/copperhead-security/platform_external_chromium/' not found
error: Cannot fetch platform_external_chromium
```

**Comment by thestinger** [comment]
See https://www.reddit.com/r/CopperheadOS/comments/8e9m42/no_longer_going_to_be_distributing_chromium/.

You need to manually point the manifest at https://github.com/CopperheadOS/platform_external_chromium and put a Chromium build there per the new building documentation.
