### ISSUE TITLE
Nexus 5X Restore Stock Factory Rom 

### ISSUE THREAD

**Issue by peterpanuk** [copperhead/bugtracker#863]
Hi all, 

I'm sorry to ask this question, but I'm really struggling to get my Nexus 5X to boot into Copperhead after install.  The install seems to go ok, but there was error when flashing vendor.img and userdata.img 

The phone now boots to the google boot logo, then loops back to either the "Unlocked Bootloader" or the Custom OS message.  (depending on the locked state of the bootloader) 

I cannot get into recovery, as the phone just loops back as described above when selecting it from the bootloader option. 

I think the problem was a old version of fastboot, but I have now updated ADB/Fastboot and still the install does not seem to work.  

Can anyone advise me on how to restore the phone back to stock os or maybe give tips to where I'm going wrong on my Copperhead install. 

Thanks in advance.

**Comment by thestinger** [comment]
Please use https://www.reddit.com/r/CopperheadOS/ for getting community support. The issue tracker is only for tracking bugs and planned enhancements.

Going back to stock is the same process with the images from https://developers.google.com/android/images. You'll need flashing factory images to work to do that.
