### ISSUE TITLE
Nexus 6P newbie Secure Boot installation

### ISSUE THREAD

**Issue by idistech** [copperhead/bugtracker#864]
Hi All, 
Firstly , very impressed and great project. Well done. Were keen to help and support.

Weve been experimenting with 2 Nexus 6Ps using the latest flash builds.. two minor questions..
i) after the flash_all.sh , ( which all seems to go well ), the device immediately reboots, and we dont get a chance to lock the bios quick enough, leading to the boot up error that the OS has been changed. Is there something / step in the instructions we are missing that we should do.. need to stop the process after the flash_all , so we can do the lock ?
ii) The OS seems to work well, weve had a couple of reboots, but that might be from initail start up/ first time config - now doing for trials...
The only 'thing' - and its very minor, the start up graphic flickers as it rotates.. Its very "80's" retro, and its really not a big issue, but just wondered if that was known feature.

As a secure device, we want to lock down the apk's that can be installed ( possibly using a private repo ? ) - has anyone else had this experience.. FDROID is great, but we would like to add/restrict VPN client, Mail client etc

Many Thanks 

G

**Comment by pintopwnie** [comment]
ii) The Copperhead logo flickering is normal.
