### ISSUE TITLE
WiFi won't re-connect

### ISSUE THREAD

**Issue by pintopwnie** [copperhead/bugtracker#865]
Steps to reproduce: Connect to WiFi successfully. Turn WiFi off a few hours and turn it back on. WiFi will attempt to connect to SSID and then it reverts to show the WiFi SSID as "saved." Since it's in the "Saved Networks" it will attempt to reconnect. It tries again and shows "connecting to SSID" then it drops again and reverts to show WiFI SSID as "saved." This cycle continues until phone is restarted and then it connects successfully. 

CopperheadOS version: Kernel 4.4.131-gfc8255902ece version 5.0.30080 
Device Model: Pixel 2

**Comment by xbtc-im** [comment]
What AP/Router are you using ? is it by any chance a TP-LINK ?

**Comment by xbtc-im** [comment]
You can try to play with the radio channel / encryption schemes for the wifi network ... Does the problem appear on other access points too, or only on that particular one ?

**Comment by pintopwnie** [comment]
I don't think this addresses the fact that if I re-start the phone, it has no problems connecting. Either way, I'll try messing with the channels later today.

**Comment by pintopwnie** [comment]
Confirmed the issue with 2 other routers. ASUS, Microtik and DD-WRT. All produce the same results on different channels. Any help would be appreciated. May be linked to another issue (No 5Ghz connectivity).

**Comment by pintopwnie** [comment]
@xbtc-im you were right. All of the routers I tried supported the dynamic frequency and it was enabled by default. Once you change the setting, the WiFi connects automatically again.

**Comment by xbtc-im** [comment]
Interesting, as DFS only applies to the 5GHz band. You can try to set a channel that does not require DFS in your country, and also scan for overlapping. I always try to use fixed , non-DFS channels for my setups.
