### ISSUE TITLE
No 5Ghz connectivity

### ISSUE THREAD

**Issue by pintopwnie** [copperhead/bugtracker#866]
Steps to reproduce: Attempt to connect to 5Ghz WiFi. Phone does not see the WiFi. Only sees 2.4Ghz.

CopperheadOS version: Kernel 4.4.131-gfc8255902ece version 5.0.30080
Device Model: Pixel 2

**Comment by pintopwnie** [comment]
Pixel 2 does not support Dynamic Frequency channels. Set it to channel 44 (5220Mhz) with 20Mhz width and it sees it now.

**Comment by xbtc-im** [comment]
Weird, as my Pixel 2 XL also sees the DFS channels (MikroTik APs). The only problem is that when the AP shows "Radar detected" (which is weird as i'm not aware of any weather radar nearby, it might be from the planes flying above) it shuts down the radio and kicks off the clients ... Maybe the regulatory domain set on the APs is different from the one set on the phone ? Anyways DFS channels are better avoided if possible ...
