### ISSUE TITLE
complete Nexus 5 binary blobs for the AOSP port

### ISSUE THREAD

**Issue by thestinger** [copperhead/bugtracker#88]
The binary blobs provided by Google are incomplete. The CyanogenMod blobs can be used as a reference to figure out what's missing but Google's factory image should be used as the source. It may not make sense to include everything. It would be best to decide on a case-by-case basis.

**Comment by smaeul** [comment]
The two libraries needed to make QSEECOMD happy are librpmb.so and libssd.so, both present in the factory image in /system/lib.

**Comment by thestinger** [comment]
Those aren't the only missing components and the extraction process needs to be automated if any of the missing pieces are going to be included. The Nexus 5 is on the backburner as it's a legacy device and Google *may* be ending support soon, resulting in CopperheadOS ending support.

**Comment by thestinger** [comment]
Nexus 5 support is winding down as 7.0 approaches so further work on it isn't going to happen.
